### ISSUE TITLE
Git repository not listed on netlib web pages

### ISSUE THREAD

**Issue by hjmjohnson** [Reference-LAPACK/lapack#10]
The online web pages located at:

http://www.netlib.org/lapack/#_browse_download_lapack_routines_with_on_line_documentation_browser

http://www.netlib.org/blas/#_svn_access

Are linking to the SVN repository.

I did a google search with the following query 
           site:http://www.netlib.org/ "icl.cs.utk.edu/svn/lapack-dev/lapack/trunk"

Hans

**Comment by julielangou** [comment]
This is now official! We are using Git! Thank you @hjmjohnson 
LAPACK and BLAs webpages have been updated.

**Comment by hjmjohnson** [comment]
@julielangou I don't know if you thought about this already or not, but I am concerned about having two separate repositories to maintain.

Why is there a "lapack-release" and a "lapack" project on github.  This is unconventional.

I would expect that there is only one project.  The items on "lapack-release" under the branches sections should really be "releases".

Would you be interested in merging these two repositories into one functional repository?  That allows for less long-term maintenance, and less overall burden for future developers.

With two separate repositories, there are two sets of issue trackers to watch, and two sets of pull requests to watch.

Let me know if you are interested in merging these two repositories.  I can help do that next week.  (See https://github.com/InsightSoftwareConsortium/ITK as an example of how releases work).

Hans

**Comment by langou** [comment]
Je pense que cela est une bonne idée. En effet regarde le site web ITK qu’il nous montre. Julien.

**Comment by vladimir-ch** [comment]
To add an extra vote, I agree with @hjmjohnson . There should be only one repository, lapack, and the releases should be just branches in that repository, named for example `release.lapack-3.6.1`.

Theoretically no merging is necessary, just create the branch tags in the `lapack` repository and delete `lapack-release`, but the last two commits in `lapack-release` are not in `lapack` (although their contents somehow in part is).

**Comment by julielangou** [comment]
As you can see, we are still discovering GitHub.
LAPACK repository structure was influenced by OpenMpi gitbug repository structure.
I am open to any modifications.
