### ISSUE TITLE
vectorization of lapack routines.

### ISSUE THREAD

**Issue by AjaySingh40** [Reference-LAPACK/lapack#1003]
I am new to Lapack and trying to  know  whether vectorization of Lapack routine is possible like BLAS routines. If possible it would be great if someone can give me idea for the same.
Thank You.

**Comment by pradeeptrgit** [comment]
AMD's LAPACK implementation, AOCL-LAPACK, has vectorized implementation for few functions of LAPACK. You can refer in links below.
Repo: https://github.com/amd/libflame
Directory containing vectorized code: https://github.com/amd/libflame/tree/master/src/lapack/x86

**Comment by AjaySingh40** [comment]
Thank You for your response. 
Is there any update for vectorization on ARM.

**Comment by pradeeptrgit** [comment]
Not aware of any ARM based vectorization

**Comment by AjaySingh40** [comment]
I went through some of the routines of LAPACK , they rely on BLAS routines for basic algebraic operations.  It has just wrapper routines that call other routines. According to these statement can we conclude that vectorizing BLAS will do the job and it doesn't make sense to vectorize Lapack routines (As vectorization gives performance when we to heavy/complex operations/calculations), correct me if I am wrong.
Thank You.

**Comment by AjaySingh40** [comment]
Thanks  @langou will try it.

**Comment by AjaySingh40** [comment]
I tried running different examples of lapack on sve implemented blas library. I am getting error in LAPACKE_ssyev() routine when the size is greater than 64(N>64), while it runs without any issue in case of blas without sve. What could be the cause of it? 
Time measured: 0.042 seconds.
The algorithm failed to compute eigenvalues.
LAPACKE_ssyev (row-major, high-level) Example Program Results for 65
Thank You.
