### ISSUE TITLE
line duplication in latest 3.7.0 causes failure of shared lib creation

### ISSUE THREAD

**Issue by balducci** [Reference-LAPACK/lapack#105]
hello,

while creating the shared version of latest lapack (3.7.0), I get:

   liblapack.a(ztplqt.o): In function `ztplqt_':
   ztplqt.f:(.text+0x0): multiple definition of `ztplqt_'
   liblapack.a(ztplqt.o):ztplqt.f:(.text+0x0): first defined here
   liblapack.a(ztplqt2.o): In function `ztplqt2_':
   ztplqt2.f:(.text+0x0): multiple definition of `ztplqt2_'
   liblapack.a(ztplqt2.o):ztplqt2.f:(.text+0x0): first defined here
   liblapack.a(ztpmlqt.o): In function `ztpmlqt_':
   ztpmlqt.f:(.text+0x0): multiple definition of `ztpmlqt_'
   liblapack.a(ztpmlqt.o):ztpmlqt.f:(.text+0x0): first defined here

Actually, I can find a duplicate line in both SRC/Makefile and
SRC/CMakeLists.txt:

SRC/Makefile:
   ...
   ztplqt.o ztplqt2.o ztpmlqt.o \    <===== DUP
   zgelqt.o zgelqt3.o zgemlqt.o \
   zgetsls.o zgeqr.o zlatsqr.o zlamtsqr.o zgemqr.o \
   zgelq.o zlaswlq.o zlamswlq.o zgemlq.o \
   ztplqt.o ztplqt2.o ztpmlqt.o \    <===== DUP
   ...

SRC/CMakeLists.txt:
   ...
   ztplqt.f ztplqt2.f ztpmlqt.f    <===== DUP
   zgelqt.f zgelqt3.f zgemlqt.f
   zgetsls.f zgeqr.f zlatsqr.f zlamtsqr.f zgemqr.f
   zgelq.f zlaswlq.f zlamswlq.f zgemlq.f
   ztplqt.f ztplqt2.f ztpmlqt.f    <===== DUP
   ...

Removing the line duplication fixes everything for me.

ciao
gabriele

**Comment by langou** [comment]
Thanks for the issue report. This is fixed. Cheers, Julien.
