### ISSUE TITLE
Convention for symbols in quadruple precision

### ISSUE THREAD

**Issue by amontoison** [Reference-LAPACK/lapack#1072]
With @nimgould, we recently updated our Fortran code for linear solvers (HSL) and optimization solvers (GALAHAD) to be modular and easily compiled with various precision and integer types.

The issue we face is that we need BLAS and LAPACK routines compiled in quadruple precision, and we typically don’t use the standard symbols for single and double precision.
Long ago, `GotoBLAS` introduced `q*` prefixes for real quadruple precision routines, which aligns well with `s*` for single and `d*` for double precision.

However, I’m unsure what prefix would be appropriate for complex quadruple precision routines (`x*`, `w*`?).

`Reference-LAPACK` provides a `make.inc` file to compile routines in quadruple precision using compiler-dependent flags like `-freal-8-real-16` with `gfortran`, but the symbols remain unchanged.

It would be fantastic to have some guidance on an informal convention from the community to establish a consistent approach moving forward.

**Comment by martin-frbg** [comment]
GotoBLAS has/had "x" for the corresponding complex functions. But as far as I can tell, neither were ever provided in earnest except possibly on the Itanium architecture, and they were never exposed through cblas.h.

**Comment by langou** [comment]
The choice of "q" and "x" sounds great to me.
