### ISSUE TITLE
CMAKE with Visual Studio Build Tools not working

### ISSUE THREAD

**Issue by fborges22** [Reference-LAPACK/lapack#1083]
When I try to build with Visual Studio Build Tools and Intel Fortran Compiler 2025 on Windows, it is not working to use CMAKE -B_BUILD. I am getting this error below.

```
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.26100.
-- Checking if build type is 'Coverage'
-- Checking if build type is 'Coverage': 0
-- Build Index-64 API as extended API with _64 suffix: ON
-- Build tests: OFF
-- Build deprecated routines: OFF
-- Build single precision real: ON
-- Build double precision real: ON
-- Build single precision complex: ON
-- Build double precision complex: ON
-- Using supplied NETLIB BLAS implementation
-- The Fortran compiler identification is unknown
CMake Error at BLAS/CMakeLists.txt:1 (enable_language):
  No CMAKE_Fortran_COMPILER could be found.

-- Configuring incomplete, errors occurred!
```

**Comment by adam-sim-dev** [comment]
Are you using Intel oneAPI 2025?

**Comment by fborges22** [comment]
> Are you using Intel oneAPI 2025? It's not supported by cmake yet.

Yes. I am using the Intel oneAPI 2025. I noticed that when I runned the winget upgrade --all command that package was upgraded to the newest version. I am gonna try to lower the version of oneAPI to try again.

**Comment by adam-sim-dev** [comment]
> > Are you using Intel oneAPI 2025? It's not supported by cmake yet.
> 
> Yes. I am using the Intel Fortran Compiler 2025. I noticed that when I runned the winget upgrade --all command that package was upgraded to the newest version. I am gonna try to lower the version of oneAPI to try again.

https://gitlab.kitware.com/cmake/cmake/-/issues/26415

You can link to mkl.

**Comment by fborges22** [comment]
I downgraded to the 2024 version and did that instructions on the link but I am getting these errors:

```
PS D:\Contrib\lapack> cmake -B build -T fortran=ifx -DCMAKE_Fortran_COMPILER="c:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/ifx.exe" -DCMAKE_INSTALL_PREFIX="D:/_INSTALL/Lapack"
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.26100.
-- The C compiler identification is MSVC 19.42.34435.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking if build type is 'Coverage'
-- Checking if build type is 'Coverage': 0
-- Build Index-64 API as extended API with _64 suffix: ON
-- Build tests: OFF
-- Build deprecated routines: OFF
-- Build single precision real: ON
-- Build double precision real: ON
-- Build single precision complex: ON
-- Build double precision complex: ON
-- Using supplied NETLIB BLAS implementation
-- The Fortran compiler identification is unknown
Intel(R) Fortran Compiler for applications running on Intel(R) 64, Version 2024.1.0 Build 20240308
Copyright (C) 1985-2024 Intel Corporation. All rights reserved.

-- Detecting Fortran compiler ABI info
CMake Error: Generator: execution of make failed. Make command was: devenv.com CMAKE_TRY_COMPILE.sln /build Debug /project cmTC_f2a53
-- Detecting Fortran compiler ABI info - failed
-- Check for working Fortran compiler: c:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/ifx.exe
CMake Error: Generator: execution of make failed. Make command was: devenv.com CMAKE_TRY_COMPILE.sln /build Debug /project cmTC_8cd27
-- Check for working Fortran compiler: c:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/ifx.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.31/Modules/CMakeTestFortranCompiler.cmake:59 (message):
  The Fortran compiler

    "c:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/ifx.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: 'D:/Contrib/lapack/build/CMakeFiles/CMakeScratch/TryCompile-f9vexr'

    Run Build Command(s): devenv.com CMAKE_TRY_COMPILE.sln /build Debug /project cmTC_8cd27
    no such file or directory
    Generator: execution of make failed. Make command was: devenv.com CMAKE_TRY_COMPILE.sln /build Debug /project cmTC_8cd27




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  BLAS/CMakeLists.txt:1 (enable_language)


-- Configuring incomplete, errors occurred!
```

**Comment by fborges22** [comment]
Recently, I tried to install the full Visual Studio instance instead of Visual Studio Build Tools and the latest version of oneAPI HPC and it worked. It could be interesting to add support for Visual Studio Build Tools too.

**Comment by adam-sim-dev** [comment]
> Recently, I tried to install the full Visual Studio instance instead of Visual Studio Build Tools and the latest version of oneAPI HPC and it worked. It could be interesting to add support for Visual Studio Build Tools too.

You can also link to intel MKL.

**Comment by fborges22** [comment]
Will intel MKL work in with Visual Studio Build Tools with Windows Server 2025 Core installation?

**Comment by adam-sim-dev** [comment]
> Will intel MKL work in with Visual Studio Build Tools with Windows Server 2025 Core installation?

I do not know. I mean if you installed intel oneapi toolkit, you can link to mkl, and do not need to compile reference lapack.

**Comment by fborges22** [comment]
Okay, I will try to create an VM to test this configuration and I will keep you informed.

**Comment by fborges22** [comment]
> > Will intel MKL work in with Visual Studio Build Tools with Windows Server 2025 Core installation?
> 
> I do not know. I mean if you installed intel oneapi toolkit, you can link to mkl, and do not need to compile reference lapack.

That worked :D Thanks a lot for the assistance. Indeed it was not necessary to build the reference LAPACK for my builds.
