### ISSUE TITLE
LAPACKE: bad transpose in ?laswp_work

### ISSUE THREAD

**Issue by vladimir-ch** [Reference-LAPACK/lapack#110]
For row-major matrices the function uses `lda_t = max(1,lda)` which is wrong, it should use the number of rows. The number of rows is however not readily available, only the lower bound can be extracted from `ipiv`. The lower bound should be enough for the purpose of the function (to do the matrix copy), and it seems to me that it is actually the only way to implement this function at all.

As a side note, an issue with the number of rows that is not directly available in `lapacke_?laswp` has arisen before. In 834c77d1a4f44529db3da798dee8d99ff2790770 it was handled by omitting the NaN check.

**Comment by langou** [comment]
Hi @vladimir-ch 

See fix of @echeresh in #118 
```
-        lapack_int lda_t = MAX(1,lda);
 +        lapack_int lda_t = MAX(1,k2);
 +        lapack_int i;
 +        for( i = k1; i <= k2; i++ ) {
 +            lda_t = MAX( lda_t, ipiv[k1 + ( i - k1 ) * ABS( incx ) - 1] );
 +        }
```
