### ISSUE TITLE
LAPACKE build problem with mingw

### ISSUE THREAD

**Issue by martin-frbg** [Reference-LAPACK/lapack#111]
Over at OpenBLAS we received a report https://github.com/xianyi/OpenBLAS/issues/1056 stating that mingw fails to build LAPACKE as the list of object files in LAPACKE/src/Makefile is too long for the ar on that platform to handle. Would you consider a PR to split the object list as it is currently done in https://github.com/xianyi/OpenBLAS/blob/develop/lapack-netlib/LAPACKE/src/Makefile ?

**Comment by langou** [comment]
Hi @martin-frbg, 

That would work with me. I reviewed the patch from @xianyi in OpenBLAS. Good with me.  So, yes, please, we would be very happy to get a PR to fix this issue. Please. 

In the Makefile, is it possible to add a comment that would read something like: 
> Note: we use multiple `SRC_OBJA`, `SRC_OBJB`, etc, instead of a single `SRC_OBJ` to allow `build` with `mingw` (argument list too long for the `msys` `ar`)
? (So as to avoid that, in a few days, someone (me?) decides to merge all these SRC_OBJA, etc into a single SRC_OBJ.

Cheers, 
Julien
