### ISSUE TITLE
Exposing auxiliary routines in lapacke.h?

### ISSUE THREAD

**Issue by SuperFluffy** [Reference-LAPACK/lapack#115]
I was looking into efficiently calculating a sum of squares and found the [`xLASSQ`](http://www.netlib.org/lapack/explore-html/df/dd1/group___o_t_h_e_rauxiliary_ga9c824016058563e3b7189801d1de6d58.html#ga9c824016058563e3b7189801d1de6d58) [auxiliary routines]( http://www.netlib.org/lapack/explore-html/df/dd1/group___o_t_h_e_rauxiliary.html), which do not seem to be exposed in the C-interface. I was wondering what the reason for that was? Is there some C header where these functions might be defined?

This issue came up for the [`LAPACK`](https://github.com/stainless-steel/lapack/issues/14) rust library, which is closely following `lapacke.h` to implement its interface.

**Comment by langou** [comment]
Hello, having xLASSQ in LAPACKE is definitely a good idea. We will see what we can do. We just got a similar request last week actually from PLASMA. Thanks for the request. Great idea. Best wishes, Julien.
