### ISSUE TITLE
Test not done for ALPHA=ONE

### ISSUE THREAD

**Issue by ashwinyes** [Reference-LAPACK/lapack#116]
In multiple files in lapack tests (for eg: [https://github.com/Reference-LAPACK/lapack/blob/master/TESTING/LIN/cdrvrf3.f]), the following code is seen which makes it not test for ALPHA=ONE.

`IF ( IALPHA.EQ. 1) THEN`
`    ALPHA = ZERO`
`ELSE IF ( IALPHA.EQ. 1) THEN`
`    ALPHA = ONE`
`ELSE`
`    ALPHA = CLARND( 4, ISEED )`
`END IF`

**Comment by langou** [comment]
Hi @ashwinyes, thanks for the bug report. If you want to review the fix, that would be great. Please let us know. Cheers, Julien.

**Comment by ashwinyes** [comment]
Thanks @langou for the fix. Now review needed as it is straightforward.
