### ISSUE TITLE
Consistency in github repo (annotated tags for version numbers)

### ISSUE THREAD

**Issue by zerothi** [Reference-LAPACK/lapack#123]
It seems that lapack-3.7.0 was tagged with a non-annotated tag. 

I think this was a mistake and you really wanted an annotated tag.
FYI, `git describe` will currently show:

    git describe
     v3.6.1-307-g8ca6cfd

However, if the version number becomes annotated (`git tag -a`) it will become

    git describe
     v3.7.0-87-g8ca6cfd

The simple fix, to also maintain the tag-date and tag-message, is:

    msg="$(git log -1 --format=%B v3.7.0)"
    date="$(git show v3.7.0 --format=%aD | head -1)"
    GIT_COMMITTER_DATE="$date" git tag -a -f -m "$msg" v3.7.0 v3.7.0

**Comment by zerothi** [comment]
Oh, similar tricks for the `GIT_<>` may be used for the committer etc.

**Comment by langou** [comment]
Hi Nick, 

Thanks for pointing this and thanks for your email with detailed instruction on how to do this. 

For future reference, I ended up entering the following commands in the terminal: 
```
  msg="releasing and tagging version 3.7.0"
  date="$(git show v3.7.0 --format=%aD | head -1)"
  GIT_COMMITTER_DATE="$date" GIT_COMMITTER_NAME="Julie" GIT_COMMITTER_EMAIL="julie@cs.utk.edu" git tag -a -f -m "$msg" v3.7.0 v3.7.0
  git push --tags -f
```

It seems better now. Thanks a lot. 
Julien.

**Comment by zerothi** [comment]
Thanks! :)

Perhaps it may be good to "fix" the previous tags as well? I.e. 3.6.0... and older? Just to have everything aligned?

**Comment by langou** [comment]
Hi Nick. Good idea. This is done. I have updated 3.6.0 and 3.6.1 so that they now are annotated. Super. Thanks a lot. Best wishes, Julien.

**Comment by langou** [comment]
Note for all. If you have a copy of the lapack git repository and you want to update it with the new annotated tags, then you need to type `git pull --tags` and that will do the trick. Thanks Nick for the command. Julien.
