### ISSUE TITLE
lapack 3.7.0 does not compile on macOS Sierra with cmake >= 3.7

### ISSUE THREAD

**Issue by fxcoudert** [Reference-LAPACK/lapack#139]
I'm trying a clean build of lapack 3.7.0 with gfortran 6.3.0 and Xcode 8.3, with `cmake .. -DLAPACKE:BOOL=ON`. It fails with:

```
-- Verifying Fortran/C Compiler Compatibility
CMake Warning (dev) at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FortranCInterface.cmake:309 (message):
  No FortranCInterface mangling known for VerifyFortran
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FortranCInterface/Verify/CMakeLists.txt:16 (FortranCInterface_HEADER)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Verifying Fortran/C Compiler Compatibility - Failed
CMake Error at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FortranCInterface.cmake:382 (message):
```

The full output files are there: https://gist.github.com/fxcoudert/f86c5fcba0519692702c711d0afa3b74

----

A build without the `-DLAPACKE:BOOL=ON`, however, succeeds.

**Comment by ilovezfs** [comment]
Also, CC @dpo.

**Comment by dpo** [comment]
The first error is probably because `ETIME` must not be declared `EXTERNAL` on OSX. I imagine it's the same on MacOS. Not sure about the second issue yet.

**Comment by fxcoudert** [comment]
Not sure what you call “the first error”: there is detection of ETIME prior to that check, and it seems to work OK.

**Comment by dpo** [comment]
This is the first error: https://gist.github.com/fxcoudert/f86c5fcba0519692702c711d0afa3b74#file-cmakeerror-log-L10

**Comment by fxcoudert** [comment]
This "first error" is expected: it is trying several variations of ETIME, and finding the right one.

**Comment by fxcoudert** [comment]
I have checked and can confirm that LAPACK builds fine with the exact same options if one uses cmake-3.6.3

**Comment by dpo** [comment]
Ok, sorry. It's hard to tell from that log what's an actual error and what's not then.

**Comment by julielangou** [comment]
Hey, is the build working with a Unix Makefile build?

**Comment by fxcoudert** [comment]
What would be the command line invocation of `make` that corresponds to `cmake .. -DLAPACKE:BOOL=ON`?

**Comment by langou** [comment]
I would say: `make lapackelib`

( Reading the threads, it seems that this is a problem from going from cmake 3.6.3 to cmake 3.7.1 and higher. So I do not think this is related. )

**Comment by ilovezfs** [comment]
This is fixed now:
https://github.com/Homebrew/homebrew-core/pull/12199
https://github.com/Homebrew/homebrew-core/pull/12198

**Comment by langou** [comment]
OK. Super. Thanks for following up with us. Julien.
