### ISSUE TITLE
Make ?ger behave similar to ?gemv and ?gemm

### ISSUE THREAD

**Issue by SuperFluffy** [Reference-LAPACK/lapack#146]
What are the steps to take to get something in `BLAS` changed or have it extended? I would love to change `?dger` from its current definition, `α v ⊗ w + A`, to `α v ⊗ w + β A`. In `?gemv` and `?gemm` you have the choice of overwriting the output matrix without adding to it by specifying a scalar `β = 0.0`. You cannot do this in `?ger`, which I think must be an oversight.

I am using `dger` to calculate the outer product between two vectors `v`, `w`, `α v ⊗ w + A`, where `α` is a scalar and `A` a matrix. As `?dger` is defined, the result is stored in `A` - but you have no way to discard the previous contents of `A`. Compare this to `?gemv`, `α A · v + β B`, where `β` controls if the previous contents of `B` are considered.

This is a tad annoying, since I have to fill the matrix A with zeros prior to using dger. That's not a wildly expensive operation, but still redundant as it could be done during the `?dger` update.

**Comment by langou** [comment]
The interface of `xGER` was defined in 
> J. J. Dongarra, J. Du Croz, S. Hammarling, and R. J. Hanson, An extended set of FORTRAN Basic Linear Algebra Subprograms, ACM Trans. Math. Soft., 1988.

I do not know why there isn't a `β` parameter on the matrix `A`. 

Unfortunately, I do not think it will be possible to change the interface of `xGER`. 

Note 1: you could use `xGEMM` then. 

Note 2: the behavior with respect to `β=0` and `NaN` would have to be defined. If we set `β=0`, and there is a NaN in A, do we want the `NaN` to propagate? Or do we want the `NaN` to be reset to `0`? Since you use `β=0` to initialize, you want to set all the elements to `0`. Therefore it is a tad different from doing `a(i,j) * β`. In `xGEMM`, when `β=0`, we do not multiply but set elements to `0`. 

Julien.

**Comment by langou** [comment]
I was reading a new paper on BLAS-like functionality and I was noticing that there is no `β` parameters on the matrix `A` for `xGER` either. See:
> F. G. Van Zee, R. A. Van De Geijn, BLIS: A Framework for Rapidly Instantiating BLAS Functionality, ACM Trans. Math. Soft., 2015.

**Comment by langou** [comment]
I am closing the issue. Feel free to reopen if more questions. Julien.

**Comment by SuperFluffy** [comment]
I will have to investigate if it makes sense to use `?gemm`, in particular with respect to possible performance differences.

I suspected that the interface of `?ger` couldn't be changed. But is it possible to instead add a `?ger_expanded` (or any other name) which provides this ability?

**Comment by langou** [comment]
Actually . . . . 

You need to know that there was an effort in the year 1999-2001 to create a new BLAS. This effort was the BLAS technical forum. See [http://www.netlib.org/blas/blast-forum](http://www.netlib.org/blas/blast-forum)

If you look at Chapter 2, Table 2.5, (page 20, line 15), 
[http://www.netlib.org/blas/blast-forum/chapter2.pdf](http://www.netlib.org/blas/blast-forum/chapter2.pdf), you find that there is a `β` on the matrix `A` for GER.

There is no implementation for this particular interface (that I know of) though. 

Julien.

**Comment by SuperFluffy** [comment]
Thanks for the source!

So what does this mean for e.g. `Reference-LAPACK`? Which standard does this project implement? The header file [`blas_dense_proto.h`](http://www.netlib.org/blas/blast-forum/blas_dense_proto.h) also linked on this blast forum site actually contains the full definition: 

```c
void BLAS_dger( enum blas_order_type order, enum blas_conj_type conj,
                int m, int n, double alpha, const double *x, int incx,
                const double *y, int incy, double beta, double *a, int lda );
```

So if I am reading you correctly there is no way of getting this interface into `Reference-LAPACK`?

**Comment by langou** [comment]
Hi @SuperFluffy. You are correct. From the BLAS technical forum, some features made it and some never made it. The XBLAS (extended BLAS) is complete and is released. The Sparse BLAS is complete and released. The CBLAS (C interface to the BLAS) is complete and released. Now all the part about Chapter 2 never made it into software. Cheers, Julien.
