### ISSUE TITLE
DISNAN violates Fortran aliasing rules when calling DLAISNAN

### ISSUE THREAD

**Issue by jeffhammond** [Reference-LAPACK/lapack#152]
DISNAN passes the same variable ([disnan.f, line 78](https://github.com/Reference-LAPACK/lapack/blob/master/SRC/disnan.f#L78)) to DLAISNAN, which expects two distinct variables ([dlaisnan.f, line 75](https://github.com/Reference-LAPACK/lapack/blob/master/SRC/dlaisnan.f#L75)).

This is a textbook violation of Fortran aliasing rules, as described in e.g. [Doctor Fortran in "I've Come Here For An Argument, Side 2"](https://software.intel.com/en-us/blogs/2009/07/10/doctor-fortran-in-ive-come-here-for-an-argument-side-2).

The best solution is to follow [disnan.f, lines 34-35](https://github.com/Reference-LAPACK/lapack/blob/master/SRC/disnan.f#L34) and use `IEEE_IS_NAN` from Fortran 2003.  According to [Fortran 2003 status](http://fortranwiki.org/fortran/show/Fortran+2003+status), all of the major compilers support the `IEEE_ARITHMETIC` intrinsics in recent versions.

The other solution, which should perhaps augment the prior one for older compilers, is to implement this functionality in a standard-compliant way using `INTENT(IN)`, `POINTER`, or `TARGET`.  (It would be nice if all of the LAPACK routines used `INTENT`...)

This is a bit of a bike-shed because I'm not aware of any compilers that break this code, but it would be nice if LAPACK was standard-compliant.

**Comment by jeffhammond** [comment]
I will submit a pull request for this if you indicate that the proposed solution is acceptable.

**Comment by langou** [comment]
Hi Jeff. Yes, please feel welcome to provide a pull request. Thanks! Cheers, Julien.
