### ISSUE TITLE
DLASQ4: unused value of local variable B2

### ISSUE THREAD

**Issue by vladimir-ch** [Reference-LAPACK/lapack#158]
In `dlasq4.f`, on line 243, the value assigned to `B2` is not used, it is overwritten soon after on line 250. It might be harmless, or it may indicate a subtle bug.

**Comment by langou** [comment]
Indeed . . . Let me ask around. Thanks for reporting. Julien.

**Comment by oamarques** [comment]
Hi Julien,
I compared the files in LAPACK 3.7.0 and the ones I have. I also looked at the base files for the dqds algorithm. That assignment for B2 is not needed, line 243 can be deleted.
Osni
