### ISSUE TITLE
Archive of LAPACK 3.7.1 cluttered by MacOS files

### ISSUE THREAD

**Issue by sebastien-villemot** [Reference-LAPACK/lapack#172]
Dear LAPACK maintainers,

I was about to package LAPACK 3.7.1 for Debian, until I noticed that the `lapack-3.7.1.tgz` tarball was full of filenames starting with `._` (dot+underscore). It seems these files are created by MacOS. This complicates the packaging for Debian, for reasons that are not worth mentioning here.

Do you plan to clean the tarball, or should I repack it myself before uploading to Debian?

**Comment by julielangou** [comment]
Argg...Thank you for letting us know
Thank you Sebastien. 
I will repackage it very soon. At the same time, you can download it directly from Github.

**Comment by ilovezfs** [comment]
Apologies for the duplicate cross-post, but just to make sure it's seen:

@julielangou in the future, it would be greatly appreciated if you could bump the version (e.g. 3.7.1.1 or 3.7.2) if the tarball needs to be altered after it has been published. Thanks!

https://github.com/Reference-LAPACK/lapack/issues/176
https://github.com/Homebrew/homebrew-core/issues/15676
https://github.com/Homebrew/homebrew-core/pull/14932
