### ISSUE TITLE
lapack 3.7.1 checksum mismatch

### ISSUE THREAD

**Issue by ilovezfs** [Reference-LAPACK/lapack#176]
URL: http://www.netlib.org/lapack/lapack-3.7.1.tgz

Expected SHA-256: 1af2e1aa940eb72c4154f3a1072418b922d1d163c1bc322de5171d9aaa715b79

Actual SHA-256:
f6c53fd9f56932f3ddb3d5e24c1c07e4cd9b3b08e7f89de9c867125eecc9a1c8

The expected checksum is what what we had in Homebrew for the SHA-256 when the formula was upgraded to 3.7.1 on Sun Jun 25 09:56:11 2017 -0700. See https://github.com/Homebrew/homebrew-core/pull/14932.

But currently downloading the file gives a different checksum.

I wanted to make sure you weren't hacked, and ask what the reason(s) for the changes were.

**Comment by zerothi** [comment]
Perhaps this is because of #172, i.e. updating the tar, but forgetting the hash
?

**Comment by ilovezfs** [comment]
@zerothi yup that explains it!

@julielangou in the future, it would be greatly appreciated if you could bump the version (e.g. 3.7.1.1 or 3.7.2) if the tarball needs to be altered after it has been published. Thanks!

**Comment by julielangou** [comment]
ok ,will do! sorry for all the trouble
