### ISSUE TITLE
GEMM GEMV ZERO CHECK

### ISSUE THREAD

**Issue by TLCFEM** [Reference-LAPACK/lapack#179]
Hello, I saw Langou committed 2b911746d5d7173ccee0067a4ad09159cdfce1a2 in Jan, 2014 to remove the zero check for zero entries in gemm and gemv. The purpose of this commit is to resolve the incorrect NaN propagation. I understand the situation that there will be some troublesome issues if the code is guarded by the if block.

However, the performance of the subroutine is significantly affected by this commit when it comes to solving the inverse of the matrix, like dgesv, especially for FEM, FDM applications in which the matrix will be sparse. I guess the users will handle the operations of non-dense matrices at least as frequently as handling NaN/Inf problems.

My argument is,  the NaN propagation issue cannot be thoroughly resolved by only modifying gemm and gemv. To do so, I guess all subroutines should be reviewed and modified. If so, then why bother creating another issue while leaving the old one unresolved?

Although this does not worry me as I can always use the old version like 3.4.2., I still want to bring this issue to you as it is pointless to increase the number of issues, is not it?

**Comment by langou** [comment]
Hi. I looked again at the commit https://github.com/Reference-LAPACK/lapack/commit/2b911746d5d7173ccee0067a4ad09159cdfce1a2. I still like it. A few points to consider. (1) The previous code was checking for ZERO and skipping operations "arbitrarily". There are many variants for GEMM and GEMV. The subroutine implemented one variant and decided to check for ZERO within loops of this variant. If you want to have the same answer for the same input, you would essentially have to use this exact same code. This is not the goal of this subroutine. We want other BLAS GEMM implementation to have the flexibility to use any variant (and return the same answer if NaNs are involved). (2) Not checking for ZEROs allows all variants to return the same results (when ZEROs and NaNs are invovled). Most BLAS GEMM implementations do not follow the reference one. (And this is a good thing.) The goal was to give a reference implementation that is as general as possible to give flexibility to implementors. (3) If the matrix is sparse and if the focus is about performance, then one should probably not use BLAS. And if one use BLAS, skipping a few rows here and there, does it really change performance? I do not know. Maybe this commit indeed had a significant impact on sparse matrices. But I do not know. I did not time. I am unable to quantify. And even though, BLAS is mostly for dense matrices. You have a good point though. The routine might be slower for sparse matrices and this is a caveat. I do think arguments (1) and (2) above are much more important than (3). A good implementation of BLAS GEMM is much much faster than the reference once so even if the reference skips computation, it is not clear it will be faster than an optimized BLAS GEMM. (4) There is the claim that many routines do not care of NaN propagation so why GEMM should. Well. (4a) We need to start somewhere. (4b) most subroutines in LAPACK do care about NaN propagation in general. NaN propagation is pretty natural for most of them, and you do have to do something to prevent it. So most of time we have NaN propagation just by coding the algorithm. The IF statement in the reference BLAS GEMM were preventing NaN propagation and this was not a good thing. Cheers, Julien.

**Comment by TLCFEM** [comment]
Hi, Julien, I fully agree with your points. I will close the issue. But I wish to leave some more stuff here. The result is just for one's reference.

Following are some benchmark tests on a 400*400 matrix with 10 to 20% sparsity. I saw in another post you claimed that 20% is the threshold between dense and sparse.

The code I used is basically calculating the inverse. Armadillo is used for generating and storing the matrix but I directly called dgesv to solve the system.
```cpp
    mat A;
    A.load("A"); // load from disk, A is generated by sprandn(400,400,.15), which is a 400*400 matrix with sparsity of 15% and stored as dense matrix, here A is dense storage
    vec B;
    B.load("B");

    vec tmp; // tmp vector to hold result

    wall_clock T;
    T.tic(); // for timing

    for (auto I = 0; I < 1000; ++I)
        ge_solve(tmp, A, B); // the wrapper of dgesv

    cout << T.toc() << endl; // print time elapsed
```

The wrapper
```cpp
int ge_solve(vec &X, mat &A, const vec &B) {
    X = B;

    auto N = static_cast<int>(A.n_cols);
    auto NRHS = 1;
    auto LDA = N;
    auto LDB = N;
    auto IPIV = new int[N];
    auto INFO = 0;

    dgesv_(&N, &NRHS, A.memptr(), &LDA, IPIV, X.memptr(), &LDB, &INFO);

    delete[] IPIV;

    return INFO;
}
```
The CPU is i7-2600. I tested version 3.7.1 and 3.4.2, the output time is **~14** seconds for **3.4.2** and **~23** seconds for **3.7.1**.

The gprof shows
- For version 3.4.2
```text
Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  Ts/call  Ts/call  name    
 67.70      9.43     9.43                             dgemm_
 19.10     12.09     2.66                             dtrsm_
 11.20     13.65     1.56                             dger_
  1.29     13.83     0.18                             idamax_
  0.43     13.89     0.06                             dscal_
  0.14     13.91     0.02                             dgetf2_
  0.14     13.93     0.02                             dlaswp_
```
- For version 3.7.1
```text
Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  Ts/call  Ts/call  name    
 87.98     20.86    20.86                             dgemm_
 11.30     23.54     2.68                             dtrsm_
  0.38     23.63     0.09                             idamax_
  0.17     23.67     0.04                             dscal_
  0.04     23.68     0.01                             operator new[](unsigned long long)
  0.04     23.69     0.01                             dgetrf2_
  0.04     23.70     0.01                             dlaswp_
  0.04     23.71     0.01                             lsame_
```

The GFLOPS of dgemm is obtained from Intel Advisor, and is around
- **3.1** for version 3.4.2
- **1.8** for version 3.7.1

Here the sparsity is 15%, real applications may have a way lower value, even lower than 5%.

I also tested OpenBLAS and Intel MKL, neither works well (no significant improvement compared to the reference 3.4.2 version or even performs worse).

The final test I did is get the old version of OpenBLAS which uses LAPACK version 3.4.2 as reference. That is OpenBLAS version 0.2.8. The performance is around the same level of reference 3.4.2 version.

So the conclusion may be drawn as, for problem scale around such a size (400, relatively small), BLAS seems to be not that friendly to sparse matrix. As far as I tested, no optimized version can help to speed it up. The [DGEMM benchmark of OpenBLAS](http://www.openblas.net/dgemm_snb_1thread.png) shows a very attractive performance (8 times faster than reference version), but I guess that is only for dense large matrix.

Cheers, 

T.L.C.

**Comment by langou** [comment]
Hi @TLCFEM. Thanks for all the feedback. You wrote: "I saw in another post you claimed that 20% is the threshold between dense and sparse." Have I ever said this? I guess I was young and unwise at the time. What a bold claim to make! ;). Thanks for making the experiments. Quite a difference indeed between 3.4.2 and 3.7.1. But as written, I think we should not take the reference BLAS as a markstick. We should look at the behavior for optimized BLAS implementation. That said, this is a very nice set of experiments. Thanks for writing this. Best wishes, Julien.
