### ISSUE TITLE
LAPACKE_WITH_TMG is not tested on TRAVIS dashboard

### ISSUE THREAD

**Issue by hjmjohnson** [Reference-LAPACK/lapack#18]
The LAPACKE_WITH_TMG option is not tested on the TRAVIS dashboard.  

To minimize surprises after code changes, this should be added to patch tests.

This work can not be completed until pull request #16 is completed.

**Comment by hjmjohnson** [comment]
Chage line

cmake -DCMAKE_INSTALL_PREFIX=${INST_DIR} -DLAPACKE=ON \
                                     ${SRC_DIR}

-- to --

cmake -DCMAKE_INSTALL_PREFIX=${INST_DIR} -DLAPACKE:BOOL=ON \
                                                                   -DLAPACKE_WITH_TMG:BOOL=ON \
                                                                    ${SRC_DIR}

**Comment by julielangou** [comment]
Fixed with #21
