### ISSUE TITLE
Possible undefined output in delaruv

### ISSUE THREAD

**Issue by Jellby** [Reference-LAPACK/lapack#182]
Am I missing something or could `ISEED` be garbage on output if `dlaruv` is called with `N` < 1?

https://github.com/Reference-LAPACK/lapack/blob/afd02ae8d40eefe454e004f506b878a4e48b517b/SRC/dlaruv.f#L438-L441

**Comment by langou** [comment]
Good point. I suggest we put a quick return if N < 1. (?)

**Comment by zerothi** [comment]
:+1:
