### ISSUE TITLE
Different sha512sums value in version 3.7.1

### ISSUE THREAD

**Issue by rgdoliveira** [Reference-LAPACK/lapack#193]
Alpine Linux builds lapack and it downloads the 3.7.1 source from [netlib.org](http://www.netlib.org/lapack/lapack-3.7.1.tgz)

We are rebuilding all the Alpine packages for 3.7 release and lapack failed to build when comparing the sha512sums. It was before:
sha512sums="b97a08b35a094fdedec88ea81026baa501397f8ae27444cac83d0e9518df8ddb4359e34e61f993b7dc5f40bba54e35837682cde6bec6f7fcd5ffad4de71bd8fe  lapack-3.7.1.tgz"

And now:
sha512sums="b16063146626d2f67ae1456a660dbb93f42d8387cfebef1bc2681a35b5d21d53120fb74b52932373d2423cd7df39a7ae4bbfc992a71addd936bbdd051d4e2eb7  lapack-3.7.1.tgz"

Does this tar.gz got any changes or it was uploaded again (or something like that)?

**Comment by zerothi** [comment]
Did you see this #176, I am however not sure whether it is the same thing?

**Comment by rgdoliveira** [comment]
yeah, #176 answer my question.

I'm going to close this. Thanks!
