### ISSUE TITLE
Infinite loop for infinity arguments in the ?larfg family of functions

### ISSUE THREAD

**Issue by martin-frbg** [Reference-LAPACK/lapack#196]
Over at OpenBLAS, a recent issue https://github.com/xianyi/OpenBLAS/issues/1343 brought to our attention that DLARFG and related functions can enter an endless loop trying to rescale the input vector if its elements are "inf". 
While the fix would appear to be trivial - exiting the loop if the already present counter KNT exceeds some suitably large threshold here https://github.com/Reference-LAPACK/lapack/blob/6bcfa0d632158cb047a9b722da1a2f22c509ba12/SRC/dlarfg.f#L173-L174
I wonder if the circumstances would be seen as too contrived to warrant attention ?

**Comment by langou** [comment]
Hi Martin. 

We fixed something related in ZLARTG in 2013:

> bug110 :: possible infinite loop in ZLARTG when input vector has NaN
> CORRECTED, rev 1437
> Present in LAPACK 3.4.2
> Bug report by Mark Hoemmen and Jack Poulson
> See http://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=5&t=3267&p=9067
> 
> Mark Hoemmen writes: Jack Poulson found that ZLARTG has an infinite loop related to NaN .EQ. 0. It’s the line below "ELSE IF( SCALE.LE.SAFMN2 )" between 10 and 20. When G is NaN, then the loop goes forever.
>
> Corrected by Rodney on Oct 5 2013

You wrote: 

> I wonder if the circumstances would be seen as too contrived to warrant attention ?

if ( ( (nan in input) => (infinite loop) ) .or. ( (inf in input) => (infinite loop) ) ) then we would like to be safe against this. This is not too contrived and this warrants attention. Thanks to OpenBLAS for pointing this.

**Comment by martin-frbg** [comment]
Thanks for the quick reply. If you agree with the non-elegant solution of exiting the loop after something like 100 futile iterations I will prepare a PR soon. (I am not aware of a check for inf that is both portable and reliable ?)

**Comment by weslleyspereira** [comment]
I think this issue was solved with #197. Am I right?

**Comment by martin-frbg** [comment]
I think so too - and probably #308 as well

**Comment by langou** [comment]
Thanks @martin-frbg and @weslleyspereira. Let us close this issue.
