### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by spotrh** [Reference-LAPACK/lapack#207]
The 3.8.0 release notes reference these files:

SRC/clahef_aa_2stage.f
SRC/dlasyf_aa_2stage.f
SRC/slasyf_aa_2stage.f
SRC/zlahef_aa_2stage.f

However, these files are not present in the 3.8.0 tarball (nor in github). Was not sure if this was an accidental omission or not.

**Comment by langou** [comment]
Hi @spotrh, , we will correct tthe release notes asap, but the tarball and GitHub are good. Thanks for letting us know. Julien.

**Comment by julielangou** [comment]
Fixed sorry
