### ISSUE TITLE
MWE for LAPACK building system in multiplatform

### ISSUE THREAD

**Issue by massich** [Reference-LAPACK/lapack#215]
I'm trying to build a [helloWordl repo](https://github.com/massich/cpp-mkl-test) with the idea to use travis and appveyor to build against all the BLAS backends listed [here](http://icl.cs.utk.edu/lapack-for-windows/lapack/), so that it can be used as a starting project. Just fork the repo, strip out everything you don't need. 

I started with the MKL backend and as you can see for the [appveyor](https://ci.appveyor.com/project/massich/cpp-mkl-test) trace it gets properly installed.
```
Installdir was defined as C:\Program Files (x86)\IntelSWTools
Space check passed: required 5.2GB, available  37GB
Product will be installed into 
    C:\\Program Files (x86)\\IntelSWTools
Intel(R) Math Kernel Library 2018 for Windows* installation was completed successfully.
```
However when calling `cmake .. -DBLA_VENDOR=Intel -DBLAS_DIR="C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.0.124\windows\mkl\lib\intel64_win\"` it seems to not find it.
I'm using `cmake-3.8.0-win32-x86` and here's the CMakeLists.txt:
```cmake
cmake_minimum_required (VERSION 3.2)
project (CMakeHelloWorld)

#version number
set (CMakeHelloWorld_VERSION_MAJOR 1)
set (CMakeHelloWorld_VERSION_MINOR 0)

# Find the BLAS stuff
find_package(BLAS REQUIRED)
message(STATUS ${BLAS_LIBRARIES})

#include the subdirectory containing our libs
add_subdirectory (Hello)
include_directories(Hello)
#indicate the entry point for the executable
add_executable (CMakeHelloWorld Hello HelloWorld.cpp)

# Indicate which libraries to include during the link process.
target_link_libraries (CMakeHelloWorld Hello ${BLAS_LIBRARIES})
```
I can see that mkl is not found ` A required library with BLAS API not found.  Please specify library`  but I can't find anything useful in [CMakeChache.txt](https://ci.appveyor.com/api/buildjobs/tt356d5375mt53yx/artifacts/CMakeCache.txt), [CMakeOutput.log](https://ci.appveyor.com/api/buildjobs/tt356d5375mt53yx/artifacts/CMakeOutput.log) nor [CMakeError.log](https://ci.appveyor.com/api/buildjobs/tt356d5375mt53yx/artifacts/CMakeError.log)

I tried to trace `FindBLAS.cmake` but I got no luck either. Any hints?

**Comment by weslleyspereira** [comment]
I'm sorry this issue received no attention. I am closing it because I believe you may not have this problem anymore. I can reopen if this is not the case.

Nowadays, MKL is distributed inside intel openapi packages. One should be able to load openapi environment variables all at once. On m y Linux machine, I run `source /opt/intel/oneapi/setvars.sh` to load the environment variables. That is how I do it for CMake.
