### ISSUE TITLE
Request for Fortran95 module interfaces

### ISSUE THREAD

**Issue by martin-frbg** [Reference-LAPACK/lapack#216]
Over at OpenBLAS, a request for "modern" interface declarations to LAPACK similar to those found in the old netlib lapack95 project was received some time ago as issue https://github.com/xianyi/OpenBLAS/issues/1195 . It is my feeling that the topic really belongs here as the upstream source.

**Comment by physkets** [comment]
> old netlib lapack95

Is it not maintained anymore?

**Comment by martin-frbg** [comment]
My impression is that it has not received updates since its 3.0 release in november 2000, or do you know otherwise ?

**Comment by langou** [comment]
LAPACK 95 is not maintained any longer correct. 

As far as modern interface for LAPACK, I will point to:
https://bitbucket.org/icl/slate
This is C++. 

I do not know of efforts for modern version of Fortran for the interface. Internally, we use more and more modern version of Fortran, but we get complains that older compiler do not work on the new code. So we take it easy.

**Comment by physkets** [comment]
I'm using LAPACK95 in most of my code; I do hope it doesn't become incompatible with new releases of LAPACK. Fortran is my primary language, and I don't use C++.

@langou That should change slowly... as HPC admins upgrade to newer versions of CentOS, across the world. But should that be affecting your work on LAPACK? Can't people just use an older version of the package until they get new compilers?

**Comment by langou** [comment]
@physkets good point
