### ISSUE TITLE
slacgv_, dlacgv_ undefined when linking with shared intel libs

### ISSUE THREAD

**Issue by raovgarimella** [Reference-LAPACK/lapack#228]
If I create shared intel libraries of the LAPACKE/LAPACK/BLAS suite, I cannot link a program with these shared libs because the linker says says slacgv_ and dlacgv_ are undefined. This is because SLACGV is defined as external in ```SRC/ssytrf_aa_2stage.f``` but is never defined. SImilarly DLACGV is defined as external in ```SRC/dsytrf_aa_2stage.f```. Can these be safely removed?

**Comment by raovgarimella** [comment]
When I do ```find . -name '*.*' -exec grep -i slacgv {} \; -print``` the only place it occurs is ```SRC/ssytrf_aa_2stage.f``` and only in the line that defines it as being EXTERNAL.
```
find . -name '*.*' -exec grep -i slacgv {} \; -print
      EXTERNAL           XERBLA, SCOPY, SLACGV, SLACPY,
./SRC/ssytrf_aa_2stage.f
```
This leads me to think that this can be safely omitted

**Comment by langou** [comment]
``This leads me to think that this can be safely omitted`` => You are correct. Thanks. This is fixed.

**Comment by bartgol** [comment]
Seems like the patch never made it into the this repo?
