### ISSUE TITLE
[question] BLAS download

### ISSUE THREAD

**Issue by danimtb** [Reference-LAPACK/lapack#229]
Hi!

Maybe this is a dumb question but I would like to know if this could be considered as the official repository for BLAS (frotran) library also.

I would like to setup a cmake project with BLAS (maybe CBLAS too) and I haven't found information about this issue.

Thanks

**Comment by langou** [comment]
Good point. Yes this is the ``official`` repository for the BLAS (fortran) library. Julien.

**Comment by danimtb** [comment]
Hi @langou  and thank you for this quick response.

So, should this be considered as a monolith repository for BLAS (with CBLAS), LAPACK (with LAPACKE) all of them with a common versioning?

Is there a way to compile only BLAS without lapack?

Thanks again! 😄

**Comment by langou** [comment]
> Is there a way to compile only BLAS without lapack?
``make blaslib``

Yes for this is a monolith repository for BLAS (with CBLAS), LAPACK (with LAPACKE) all of them with a common versioning. This is correct.

**Comment by danimtb** [comment]
Hi @langou!

I was able to compile with cmake using:

```
$ cmake . -G "MinGW Makefiles" -D CBLAS=ON -D LAPACKE=ON
...
$ cmake --build . --target=cblas
$ cmake --build . --target=lapacke
```

to build all the libraries in this repo.

Thank you so much for your support!
