### ISSUE TITLE
Documentation problem with verbatim and title

### ISSUE THREAD

**Issue by albert-github** [Reference-LAPACK/lapack#239]
When running doxygen a number of ```verbatim``` versus ```title``` type of problems are reported like:
```
SRC/cgelq.f:137: warning: Illegal command verbatim  as part of a title section
SRC/cgelq.f:139: warning: unexpected command endverbatim
```
There looks like to be a solition by placing in the comment block a line in the form ```\brief \b <subroutine name>```. This is not the optimal solution, best would be that doxygen would handle this properly, I'm looking into the issue but it is not easy and nos solution yet.

**Comment by langou** [comment]
Thanks @albert-github. These issues should be closed by #503.
