### ISSUE TITLE
Wrong include directory for target lapacke

### ISSUE THREAD

**Issue by mrak1990** [Reference-LAPACK/lapack#246]
https://github.com/Reference-LAPACK/lapack/blob/4f7f2aab27814a920613f27f4b0d5055a421dcaf/LAPACKE/CMakeLists.txt#L63-L66

The correct path for headers:
`$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>`

**Comment by julielangou** [comment]
fix by #277
