### ISSUE TITLE
?TREXC: unavoidable error return when N=0

### ISSUE THREAD

**Issue by vladimir-ch** [Reference-LAPACK/lapack#25]
The documentation and the code indicate that N=0 is allowed. However, in that case the error checking for IFST (and ILST) leads to an unavoidable failure:
```
      ELSE IF( IFST.LT.1 .OR. IFST.GT.N ) THEN
         INFO = -7
      ELSE IF( ILST.LT.1 .OR. ILST.GT.N ) THEN
         INFO = -8
      END IF
```

**Comment by langou** [comment]
Hi Vladimir, 

Thanks for pointing out the problem. 

We need to do something about this. 

I think we want to keep allowing N=0 and have a quick return in the case N=0 and if N=0, then we do not worry about checking IFST and ILST. 

So a fix could be:
`      ELSE IF(( IFST.LT.1 .OR. IFST.GT.N ).AND.( N.GT.0 )) THEN
         INFO = -7
      ELSE IF(( ILST.LT.1 .OR. ILST.GT.N ).AND.( N.GT.0 )) THEN
         INFO = -8
 `
I do not plan on altering the comments. (We could discuss the case N=0 in more details, but I think this is an overkill and would rather leave the comments as is.)

How does this sound to you?

Cheers, 
Julien.

**Comment by langou** [comment]
Yes please!
