### ISSUE TITLE
LAPACKE_?trexc_work: ldq must be always >= n

### ISSUE THREAD

**Issue by vladimir-ch** [Reference-LAPACK/lapack#26]
In row-major case, `LAPACKE_?trexc_work` requires `ldq >= n` even when `compq` is not `'v'`, that is, when the matrix Q is not referenced. The `ldq` parameter is always used conditionally only if `compq` is `'v'`, so the `ldq >= n` check should be also done only in that case.

In ?TREXC the corresponding check is:
```
IF( LDQ.LT.1 .OR. ( WANTQ .AND. LDQ.LT.MAX( 1, N ) ) ) THEN
   INFO = -6
```

**Comment by langou** [comment]
Thanks for spotting this. What about on line 54 of `LAPACKE_dtrexc_work.c`:
```
        if(( ldq < n )&&(LAPACKE_lsame( compq, 'v' ))) {
```
Note: LAPACKE does not check for ( ldq < 1 ) if the array is not referenced. This is fine. This is not consistent with LAPACK. LAPACK (Fortran) does check for  ( ldq < 1 ). 

Do you want to submit a pull request? And if you have a better solution for changing the check, please go ahead. 

Cheers,
Julien.
