### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by ghost** [Reference-LAPACK/lapack#266]
hi，I encountered this problem when I compiled it.
stbt05.f: In function 'stbt05':
stbt05.f:189: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [stbt05.o] Error 1
make[2]: Leaving directory `/mnt/data/gulinlin/software/lapack-3.8.0/TESTING/LIN'
make[1]: *** [LIN/xlintsts] Error 2
make[1]: Leaving directory `/mnt/data/gulinlin/software/lapack-3.8.0/TESTING'
make: *** [lapack_testing] Error 2

**Comment by gulinlin** [comment]
I am getting a segmentation fault when running the Makefile. It seems to occur when it hits the subroutine stpt05.f
What should I do? Any help would be appreciated.

**Comment by christoph-conrads** [comment]
```
stbt05.f:189: internal compiler error: Segmentation fault
```
There is a problem with the Fortran compiler and not with LAPACK. To fix this problem you have to use a different Fortran compiler. Try to upgrade the Fortran compiler or build LAPACK on a different system.

Please report the the compiler bug at http://bugzilla.redhat.com/bugzilla.

**Comment by weslleyspereira** [comment]
Closed due to inactivity. Please let me know if I should reopen it.
