### ISSUE TITLE
Help text for DORCSD2BY1

### ISSUE THREAD

**Issue by chtobler** [Reference-LAPACK/lapack#27]
DORCSD2BY1:
The help text for DORCSD2BY1 (and similarly for SORCSD2BY1, CUNCSD2BY1, ZUNCSD2BY1) does not tell me exactly how to build the output matrices from LAPACK's output. It gives the following formula:

                                [  I  0  0 ]
                                [  0  C  0 ]
          [ X11 ]   [ U1 |    ] [  0  0  0 ]
      X = [-----] = [---------] [----------] V1**T .
          [ X21 ]   [    | U2 ] [  0  0  0 ]
                                [  0  S  0 ]
                                [  0  0  I ]

and defines that X is M-by-Q, X11 is P-by-Q, and thus X12 is (M-P)-by-Q, and U1, U2, and V1 are P-by-P, (M-P)-by-(M-P), and Q-by-Q, respectively. The help text also defines that the matrices C and S are R-by-R, with R = MIN(P,M-P,Q,M-Q). But the sizes of the other blocks in the formula are not defined.

After quite some experimentation, I think that the top left matrix I should have size T-by-T, with T = max(Q+P-M, 0), and the bottom right matrix I should have size K-by-K, with K = max(Q-P, 0). The sizes of the other blocks can be derived from these two blocks, but finding these two formulas took me quite a long time on my own, and should really be documented directly.

**Comment by julielangou** [comment]
Email to contributor sent
