### ISSUE TITLE
Add LAPACK option and support building only LAPACKE without requiring fortran

### ISSUE THREAD

**Issue by jcfr** [Reference-LAPACK/lapack#273]
@langou  : @phcerdan and I will start working on the following

* [ ] Do not require `Fortran`. See https://github.com/Reference-LAPACK/lapack/blob/9fb29d8ea47d643ad44a67d3da5de36e280143f5/CMakeLists.txt#L3

* [ ] Add option `LAPACK` enabled by default (similar to the other option named `LAPACKE` and `CBLAS`). Enable Fortran only with `LAPACK` is on. In a nutshell, `enable_language(Fortran)` will be called only if `LAPACK` is `ON`

* [x] Exclude [this](https://github.com/Reference-LAPACK/lapack/blob/9fb29d8ea47d643ad44a67d3da5de36e280143f5/CMakeLists.txt#L27-L31) code if `CMAKE_CONFIGURATION_TYPES` is defined

* [ ] Update `appveyor.yml` to test building with `LAPACK:BOOL=OFF` and `LAPACKE:BOOL=ON` using generators `-G "Visual Studio 14 2015 Win64` (will add VS 2017 later)

**Comment by julielangou** [comment]
Will this fix #267?

**Comment by jcfr** [comment]
> Will this fix #267?

yes

**Comment by jcfr** [comment]
@phcerdan Let's fix #267 in with a dedicated PR.
