### ISSUE TITLE
Segmentation fault when testing xeigtstz

### ISSUE THREAD

**Issue by bkmgit** [Reference-LAPACK/lapack#276]
When building on Fedora 28 using gcc 8.1.1, get segmentation fault when doing tests:

NEP: Testing Nonsymmetric Eigenvalue Problem routines
./EIG/xeigtstz < nep.in > znep.out 2>&1
/bin/sh: line 1:  9646 Segmentation fault      (core dumped) ./EIG/xeigtstz < nep.in > znep.out 2>&1
make[1]: *** [Makefile:464: znep.out] Error 139

**Comment by weslleyspereira** [comment]
Hello! There are some other issues related to the same problem, e.g., #85 and #335. I am closing this issue and move the discussion to #335.
