### ISSUE TITLE
SGELSS not zeroing all of S when the matrix is zero

### ISSUE THREAD

**Issue by martin-frbg** [Reference-LAPACK/lapack#296]
In https://github.com/xianyi/OpenBLAS/issues/1859 it has been brought to our attention that SGELSS, unlike the other xGELSS, does zero only the first row of the output matrix S when the input matrix A is zero [here](https://github.com/xianyi/OpenBLAS/blob/develop/lapack-netlib/SRC/sgelss.f#L410) - compare  [dgelss](https://github.com/xianyi/OpenBLAS/blob/develop/lapack-netlib/SRC/dgelss.f#L414) which has MINMN as the last parameter to DLASET rather than 1.

**Comment by langou** [comment]
Thanks Martin. This is fixed. This was a weird bug. The call to SLASET was not valid with such a small LDA. Thanks a lot. Julien.
