### ISSUE TITLE
Unnecessary GO TO in DLANV2

### ISSUE THREAD

**Issue by SimonDeRidder** [Reference-LAPACK/lapack#302]
The subroutine DLANV2 contains an if-else structure like:
`IF ...`
&emsp;`...`
&emsp;`GO TO 10`
`ELSE IF ...`
&emsp;`...`
&emsp;`GO TO 10`
`ELSE`
&emsp;`...`
`END IF`
`10 CONTINUE`
I believe the `GO TO` statements (and the label) are unnecessary and can be removed.

**Comment by zerothi** [comment]
I agree, same goes for `slanv2`

**Comment by langou** [comment]
Thanks Simon and Nick. This is fixed. Six less GOTOs in LAPACK. Way to go. Cheers, Julien.
