### ISSUE TITLE
Question : do you allow publishing binaries?

### ISSUE THREAD

**Issue by dotChris90** [Reference-LAPACK/lapack#313]
Hello LAPACK team, 

I am .NET open Source developer from NumSharp Project - we try to adapt Numpy for C#. 
A good NumSharp sure need a good LAPACK native lib.

I was just wondering if you ok if we publish them in their compiled binary form as a nuget package (the package format from .NET). 

We will surely write in Readme, that we did not implement it but you did. And when publishing keep your license for this specific package. 

we already adapted the appveyor file for artifacts on https://ci.appveyor.com/project/dotChris90/lapack. 
Now in next step want to publish the generated package for .NET developer on nuget.org. And thats why ask you if you ok with it. ;)

**Comment by langou** [comment]
Please go ahead. J.

**Comment by dotChris90** [comment]
cool will do.
