### ISSUE TITLE
lapacke and its interaction with complex when using C++

### ISSUE THREAD

**Issue by aprokop** [Reference-LAPACK/lapack#320]
Inclusion of `<complex.h>` in `lapacke.h` (through `lapack.h`) leads to problem with compilation in some situations when using C++. It was discovered in OpenBLAS, see xianyi/OpenBLAS#1992 for more discussion.

It seems that the issue can be fixed by including `<complex>` instead of `<complex.h>` when compiling with C++, guarded by `__cplusplus` (and possibly `__cplusplus >= 201103L`.

It seems that there have already been a step in that direction by including `<complex>` in `lapacke_config.h`.

**Comment by julielangou** [comment]
fixed with #434 - Thanks Martin!
