### ISSUE TITLE
lapack.h not being installed

### ISSUE THREAD

**Issue by raovgarimella** [Reference-LAPACK/lapack#331]
When I build and install LAPACK with LAPACKE enabled, lapack.h is not getting installed in the target include directory. When I look at LAPACKE/include/CMakeLists.txt, it is has the following lines

`set(LAPACKE_INCLUDE lapacke.h lapacke_config.h lapacke_utils.h)
  
file(COPY ${LAPACKE_INCLUDE} DESTINATION ${LAPACK_BINARY_DIR}/include)
`
So clearly, lapack.h is not being copied over. Is this a "feature" or a bug?

**Comment by martin-frbg** [comment]
I do not think a file lapack.h even exists - LAPACK as such is FORTRAN code which does not use C-style headers, and LAPACKE was created specifically to provide C bindings for it, which naturally includes an appropriate header file for this purpose.

**Comment by raovgarimella** [comment]
It does

https://github.com/Reference-LAPACK/lapack/blob/master/LAPACKE/include/lapack.h

and lapacke.h refers to it.

**Comment by raovgarimella** [comment]
Apparently, the change happened on Nov 18 in this commit b03dd2011da
I will try to issue a pull request to copy this additional file over to the install directory

**Comment by martin-frbg** [comment]
Ah, sorry, I had only compared against a checkout of 3.8.0 (which is what OpenBLAS uses). So this appears to be an oversight from #294

**Comment by julielangou** [comment]
Close by #332
