### ISSUE TITLE
Typo in idamax docstring

### ISSUE THREAD

**Issue by Jellby** [Reference-LAPACK/lapack#358]
https://github.com/Reference-LAPACK/lapack/blob/f04cb6ce84b77e42e5f6935cbe8488a96b9191dd/BLAS/SRC/idamax.f#L46

`SX` should be `DX`.

There could be similar mistakes elsewhere.

**Comment by julielangou** [comment]
This was fixed with commit 77b0d67 : 
https://github.com/Reference-LAPACK/lapack/commit/77b0d6761b2de0523dfb05e0a8547941da0fce6e
