### ISSUE TITLE
*LASQ4 S must be initialized to zero.

### ISSUE THREAD

**Issue by moe123** [Reference-LAPACK/lapack#359]
in *LASQ4 S must be initialized to zero else TAU is set to undefined if none of branches are entered.

**Comment by thijssteel** [comment]
do you have a case where this is a problem or was it just a compiler warning?

Unless `n0in` is less than `n0`, i think its impossible for none of the branches to be entered. `n0in` is initialized as `n0` and `n0` only ever decreases, so `n0in` will always be at least `n0`
