### ISSUE TITLE
Linking of LAPACK to GFORTRAN failed 

### ISSUE THREAD

**Issue by Sci-Phil** [Reference-LAPACK/lapack#360]
Hey guys,

I am currently trying to install Dakota from Sandia National Laboratories, where LAPACK is a required tool to perform the calculations. However, there is an error while compiling. It says:

/usr/bin/ld: /usr/lib/x86_64-linux-gnu/lapack/liblapack.a(xerbla.o): undefined reference to symbol '_gfortran_string_len_trim@@GFORTRAN_8'
/usr/bin/ld: /lib/x86_64-linux-gnu/libgfortran.so.5: error adding symbols: DSO missing from command line

Unfortunately, I have not come across a suitable solution yet.
Therefore, I would be very grateful if someone can help me with this problem.

With best regards
Sci-Phil

**Comment by moe123** [comment]
hello, I don't know the layout but do you have a libblas.a somewhere? `find /usr/lib/x86_64-linux-gnu/ -name blas` if so just add -lblas to your makefile.

**Comment by zerothi** [comment]
If you are linking with gcc, then you manually have to add,`-lgfortran` to the linker line, I am not at my comp, and I can't exactly remember if the error message looks like yours.
