### ISSUE TITLE
Some file were not compiled 

### ISSUE THREAD

**Issue by WangHongSen** [Reference-LAPACK/lapack#362]
I want to use function lapacke_dlatms . There is source file in directory  LAPACKE/src. I compile and get liblapacke.a. but nm told me there is no reference in liblapacke.a, which means I can not call it in C.  Aslo, thereis no lapacke_dlatms.o, so what's wrong?
I use ferdora with gcc-9.

**Comment by vladimir-ch** [comment]
Try compiling lapacke with
```
make LAPACKE_WITH_TMG=1
```
