### ISSUE TITLE
LASQ3 line 320 unused expression.

### ISSUE THREAD

**Issue by moe123** [Reference-LAPACK/lapack#364]
`QMAX = MAX( QMAX, Z( 4*I0+PP-3 ), Z( 4*I0+PP+1 ) )` QMAX is never used; if you expect it out
mark it as is.

**Comment by thijssteel** [comment]
qmax is used in xlasq2

**Comment by moe123** [comment]
@thijssteel as an output result: again  QMAX is never used within this context; if you expect it out
mark it as is. @see doc-string.

**Comment by thijssteel** [comment]
Oh, so if i understand correctly, it's about the documetation on line 94 where QMAX is declared as [IN]?

I'm not sure what you mean. Can you write out your argument a little more clearly?
