### ISSUE TITLE
Inccorect documentation for -b option of lapack_testing.py

### ISSUE THREAD

**Issue by svillemot** [Reference-LAPACK/lapack#366]
The help notice for `lapack_testing.py` says that the default value for the `-b` option is the current directory (`.`).

However, when this option is not passed, the script looks into the `bin/Release` subfolder of the present directory.

Note that this is functional change in release 3.9.0. In previous releases, the script would look in the current directory.

**Comment by christoph-conrads** [comment]
fixed by commit 89e8b8940090f6dc8ca951ae6b79cf00e25cd789

**Comment by langou** [comment]
Thanks @svillemot, thanks @christoph-conrads.
