### ISSUE TITLE
Changes pushed to master without a Pull Request

### ISSUE THREAD

**Issue by vladimir-ch** [Reference-LAPACK/lapack#371]
This is not an issue with the reference lapack per se, rather a suggestion or a mild request towards its maintainers.

It seems that the project allows to push changes directly to master without going first through a pull request. Consequently changes silently land in master without any notification even for people watching the repository which makes it harder to follow the work that is being done. This has happened recently for example with the dorhr addition. I perfectly understand that this style may fit the contributors workflow but could the maintainers at least consider protecting master so that "_... all commits must be made to a non-protected branch and submitted via a pull request with the required number of approving reviews ..._"? This can be easily done via Settings -> Branches -> Branch protection rules.

**Comment by julielangou** [comment]
Thank you for the advice.
We just added a branch rule on our repository to not allow direct commit into master.
