### ISSUE TITLE
Missing manpages for 3.9.0

### ISSUE THREAD

**Issue by matzeri** [Reference-LAPACK/lapack#377]
The current 
  http://netlib.org/lapack/manpages.tgz 
is still linked to
  http://netlib.org/lapack/manpages-3.8.0.tgz

and it seems that no
  http://netlib.org/lapack/manpages-3.9.0.tgz
is available.

Before packaging for Cygwin this Lapack version I will appreciate an updated manpages.

**Comment by julielangou** [comment]
Should be fixed now
