### ISSUE TITLE
IINFO isn't passed out for sormqr and cunmqr

### ISSUE THREAD

**Issue by Peter9606** [Reference-LAPACK/lapack#385]
In cunmqr LINE283, variable "IINFO" isn't passed out.
https://github.com/Reference-LAPACK/lapack/blob/eed5b4f17f2c9a7598f44c3eccb1c561a52ec1b3/SRC/cunmqr.f#L283

Same issue in sormqr.

**Comment by martin-frbg** [comment]
As I read it, none of the input parameters can have changed at this point (the call to cunm2r), so any invalid input would have been caught by the (identical) checks in cunmqr itself already and IINFO is certain to be zero always.
