### ISSUE TITLE
Transitive dependencies not PUBLIC in CMAKE build system

### ISSUE THREAD

**Issue by raovgarimella** [Reference-LAPACK/lapack#389]
The CMake build system sets up PRIVATE dependencies between the different library targets, e.g., 

```target_link_libraries(lapacke PRIVATE ${LAPACK_LIBRARIES})```

https://github.com/Reference-LAPACK/lapack/blob/e8ef54bd54123f1817220b9435a5fc352a45ecfc/LAPACKE/CMakeLists.txt#L94

but shouldn't these be PUBLIC dependencies so that the dependencies are transmitted through to downstream applications?

It used to be that way, until v3.7.0 but PR #119 to prevent "overlinking" changed that to it's current form but modern CMake seems to not care. Time to change it back? The change would be to replace the PRIVATE keyword with PUBLIC in relevant ```target_link_libraries``` command.

**Comment by raovgarimella** [comment]
@turboencabulator thoughts?

**Comment by turboencabulator** [comment]
What's the advantage of making it public?

Are you building static libs?  PRIVATE is for the benefit of shared libs, that internally keep track of their own dependencies.  Static libs generally don't keep track of their own deps, leaving it to you (or the build system if you're lucky, see the --static flag for pkg-config) to account for everything.

**Comment by raovgarimella** [comment]
I am not sure I agree with your interpretation of PRIVATE and PUBLIC flags for the dependencies. PRIVATE dependencies are necessary for the building of  a particular target but subsequent use of that target does not require those targets - say, I need a header only library ```foo``` to build my static library ```bar``` but projects linking to my ```foo``` don't need to know about ```bar```. On the other hand, PUBLIC dependencies are used to indicate to downstream project what targets in my project depends on and what they will need to link to. Using the same example as before, if ```foo``` depended on static or shared library ```bar``` without which any project linking to ```foo``` would fail to build, I should indicate the dependence of ```foo``` on ```bar``` using a PUBLIC property for the dependency. That would be the meaning of *transitive* dependencies. Once I have declared a public dependency I can write that out in the package config file so that others know that they have to link to ```bar``` when they link to ```foo```. In fact, I might go further and help them find ```bar```. I don't force them to automatically know of and furnish every dependency up the chain like in the old CMake days. Without this logic, there would be no reason for the PUBLIC keyword to exist in the ```target_link_libraries``` command. For more on this, see

https://youtu.be/bsXLMQ6WgIk?t=1295

So my question is, is there a special reason for these to have been made PRIVATE dependencies thereby changing the previous behavior (presumably put in by Kitware since they collaborated on the build system)? In particular, I am not sure what "overlinking" is or what problems it caused. Or can I issue a PR to change these to a PUBLIC dependency so that they get written out to the lapacke-config.cmake file.

**Comment by raovgarimella** [comment]
I just noticed that the current config file gets around this problem by explicitly setting LAPACKE_LIBRARIES to include LAPACK_LIBRARIES as well.

```set(LAPACKE_LIBRARIES lapacke ${LAPACK_LIBRARIES})```

I suppose it will do for now.
