### ISSUE TITLE
Confusion with pointing to blas, liblas and lapack 

### ISSUE THREAD

**Issue by UfrancoU** [Reference-LAPACK/lapack#392]
Hi all,

I have BLAS 3.8.0 library: I have the full set of .f subroutines, which I compiled, getting their corresponding .o files. All good with that.

I also have LAPACK 3.8.0. Inspecting this I find a BLAS subdirectory inside it. 
1) Why does Lapac3.8.0 directory contains also a BLAS subdirectory?
The BLAS subdirectory contains SRC and TESTING, and makefile. Upon doing make, make all, make blas, ..I get no results. The message reads: Nothing to be done.

Upon installing the software I need (Trilinos and other stuff), I need to provide a path for these libraries BLAS and LAPACK to be properly used.

2) Which BLAS library should I point to in the path? Should I point to my BLAS library, or to the BLAS libraries inside LAPACK?

3) The support team of the softwares that I am installing let me know that I need to have libblas.so
Upon searching on the web, I find a repository (Centos.pkgs.org) for libblas, but this is all part of BLAS, they recommend simply 'yum install blas' . But certainly, In my libraries I find NO libblas.

I would appreciate your help,

cheers,
Felipe

**Comment by moe123** [comment]
Hello, when using lapack build everything from there; hence point to those librairies; you don't need a standalone libblas living elsewhere.

Have a good day.

**Comment by UfrancoU** [comment]
Hi Juggling Frog,

 

   Thanks for your reply.

 

   Thank you. Your recommendation is worthy. I must admit that what you indicate was not obvious to me.

 

cheers,

 

Felipe

 
 

Sent: Friday, February 28, 2020 at 12:41 AM

**Comment by moe123** [comment]
@UfrancoU please feel free to close it.
