### ISSUE TITLE
cblas.h incompatible with similar libraries

### ISSUE THREAD

**Issue by mdarnold1** [Reference-LAPACK/lapack#393]
cblas.h is incompatible with ATLAS clapack.h.  The latter also includes cblas.h  but the definitions are not currently compatible which can cause confusion on systems with both libraries installed.  One way they are incompatible is ATLAS declares function arguments like enum CBLAS_... but lapack cblas.h has typedef enum {...} CBLAS_... (lines 19-25).

One way to improve compatibility would be a subtle modification to lapack's cblas.h:
typedef enum CBLAS... {...} CBLAS_...
...
#define CBLAS_ORDER CBLAS_LAYOUT

**Comment by martin-frbg** [comment]
Shouldn't Reference-LAPACK (a.k.a "netlib lapack" take priority here, with ATLAS "in the wrong" ?

**Comment by langou** [comment]
The C interface to the BLAS provided with the reference BLAS library (CBLAS) follows the specifications in: [http://www.netlib.org/blas/blast-forum/cinterface.pdf]

@mdarnold1  : can you be more specific on what changes you suggest? (Can you give an example of a current line and how you suggest this line would be changed?) Also, can you explain to me the implication of this change as far as compatibility?

**Comment by mdarnold1** [comment]
The spec document is a little sparse, but compare:

cinterface.pdf:
enum CBLAS_ORDER {CblasRowMajor=101, CblasColMajor=102};

atlas cblas.h
enum CBLAS_ORDER {CblasRowMajor=101, CblasColMajor=102 };

lapack cblas.h:
typedef enum CBLAS_LAYOUT {CblasRowMajor=101, CblasColMajor=102};
typedef CBLAS_LAYOUT CBLAS_ORDER;

lapacke.h
#define LAPACK_ROW_MAJOR               101
#define LAPACK_COL_MAJOR               102

openblas cblas.h
typedef enum CBLAS_ORDER     {CblasRowMajor=101, CblasColMajor=102} CBLAS_ORDER;

**Comment by mdarnold1** [comment]
The openblas version works with any of them (at least as far as the constants are concerned).

The lapack version will not work with atlas, because atlas lacks a typedef so all uses of the enum must be prefaced with enum, with doesn't work with the form of typedef used in the lapack header.

**Comment by mdarnold1** [comment]
The simplest resolution would seem to be to replace lines 19-25 with:
typedef enum CBLAS_LAYOUT {CblasRowMajor=101, CblasColMajor=102} CBLAS_LAYOUT;
typedef enum CBLAS_TRANSPOSE {CblasNoTrans=111, CblasTrans=112, CblasConjTrans=113} CBLAS_TRANSPOSE;
typedef enum CBLAS_UPLO {CblasUpper=121, CblasLower=122} CBLAS_UPLO;
typedef enum CBLAS_DIAG {CblasNonUnit=131, CblasUnit=132} CBLAS_DIAG;
typedef enum CBLAS_SIDE {CblasLeft=141, CblasRight=142} CBLAS_SIDE;
  
#define CBLAS_ORDER CBLAS_LAYOUT

**Comment by mgates3** [comment]
I agree with @mdarnold1.

For instance, the original cblas.h (http://www.netlib.org/blas/blast-forum/cblas.tgz) uses:
`enum CBLAS_UPLO {CblasUpper=121, CblasLower=122};`
This is still used in Apple's Accelerate cblas.h and ATLAS cblas.h.

The cblas.h in LAPACK, added in 3.6, uses:
`typedef enum {CblasUpper=121, CblasLower=122} CBLAS_UPLO;`
This was used in Intel MKL <= 2019, but it appears MKL 2020 changed.

Doing as @mdarnold1 suggests:
`typedef enum CBLAS_UPLO {CblasUpper=121, CblasLower=122} CBLAS_UPLO;`
would be compatible with both uses. This is used in OpenBLAS, and effectively in MKL 2020 (as 2 statements). Then an application do either:
`enum CBLAS_UPLO uplo = CblasUpper;` or
`CBLAS_UPLO uplo = CblasUpper;`
So doing a typedef that way increases compatibility, with no negative side effects that I am aware of.
