### ISSUE TITLE
LAPACKE_dtpmqrt_work wrong computation for row major layout

### ISSUE THREAD

**Issue by haldaas** [Reference-LAPACK/lapack#404]
The transposition of input matrices to have them in column major layout is not performed correctly. 
Consider we want to apply Q from the left.
The array 'a' for example is a  k x n matrix. In the line 105, it transposed into k x m matrix! (Checking the dimension, line 61, is wrong as well.)
The 't' array is nb x k matrix with leading dimension at least k in row major layout. Lines 54, 71, and 104 should be corrected. The same with the array 'v', lines 55 and 103 should be corrected. 
The dimensions of the transposed arrays are wrong and need to be corrected.

**Comment by weslleyspereira** [comment]
Hi @haldaas. I am trying to solve this issue. Can you please review #540? Thanks.
