### ISSUE TITLE
Why lapacke is not working in ubuntu 20.04 

### ISSUE THREAD

**Issue by amamun** [Reference-LAPACK/lapack#407]
Hi, I recently upgrade my laptop to ubuntu 20.04. 
I had no problem working with lapacke on ubuntu 18.04, but now it is not working any more. It compiles but while running the code it does nothing. I have no doubt about the program I wrote since it has been giving me correct results before the update. What can I do? Thanks in advance.

**Comment by martin-frbg** [comment]
Are you sure that your program is actually linked against the intended version of the lapack library, and manages to load it at runtime ? Doing "nothing" (in which LAPACKE or LAPACK function call ?) is not a very useful description, I assume it returns the input arguments unchanged without setting an error code (or crashing) ? Have you tried to trace execution with gdb ?

**Comment by m4v** [comment]
I ran into the same issue, the program hangs with the CPU at 100% and needs to be terminated, gdb shows this is when some functions of lapacke are called. 
Using locally compiled lapack libraries fixes it so probably there's something wrong with the packaged ones in Ubuntu 20.04

**Comment by martin-frbg** [comment]
OpenBLAS just got a heads up that Ubuntu 20.04 seems to have libraries compiled with an additional LDFLAG of `-Wl,-Bsymbolic-functions` that appears to cause the hangs.

**Comment by martin-frbg** [comment]
@m4v, @amamun are you actually using Reference-LAPACK libraries or the LAPACK included in  OpenBLAS ? (Something like `sudo update-alternatives --config liblapack.so.3` should tell)

**Comment by amamun** [comment]
Thank you all for your feedback. I freshly reinstalled ubuntu 20.04 and my problem is solved. Thanks a lot again.

**Comment by m4v** [comment]
> @m4v, @amamun are you actually using Reference-LAPACK libraries or the LAPACK included in OpenBLAS ? (Something like `sudo update-alternatives --config liblapack.so.3` should tell)

update-alternatives says there's no alternatives and ldd shows that my system uses `/lib/x86_64-linux-gnu/liblapack.so.3` and not `/usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3` which is the other liblapack.so that I have in my system.

**Comment by moe123** [comment]
portable INF/NAN check in 2020 is named standard for Floating-Point Arithmetic (IEEE 754); if you still try messing around today about that fact; nobody can help you; you are a sicko; this is the only rational statement to be made; if your code becomes a computer museum patchwork you should think about changing career.

**Comment by martin-frbg** [comment]
@moe123 I assume you intended to comment on issue 411 rather than here ? (And it would be appreciated if you could review your words - if you are a professional you will know that one cannot simply tell everybody to dump their old hardware and outdated compilers, even if it can be frustrating to be bound by some of their "historical" limitations)

**Comment by moe123** [comment]
@martin-frbg I don't the relationship with professional  mumbo-jumbo IEEE 754-1985 describes those behaviors. So you are talking about using computer that ~30 years old; yes! does car constructors maintains such backward compatibility? not a single industry does; and yes I was talking about part of those kind of irrecevable excuses: my computers are old; ok stick with it nobody cares; the rest of the world moves on and needs to.
