### ISSUE TITLE
getsls optimal workspace < min workspace size

### ISSUE THREAD

**Issue by mgates3** [Reference-LAPACK/lapack#415]
For m < n, the queried optimal workspace size can be smaller than the minimum workspace size, yielding an error. Attached is an example code to replicate the issue, using the current head (8e1e16c). Here's sample output:

```
dgetsls m   2, n   0, nrhs   1, info_min   0, info_opt   0, info   0, lwork_min   6, lwork_opt   6, lwork   0, ok
dgetsls m   2, n   1, nrhs   1, info_min   0, info_opt   0, info   0, lwork_min   7, lwork_opt   7, lwork   7, ok
dgetsls m   2, n   2, nrhs   1, info_min   0, info_opt   0, info   0, lwork_min   9, lwork_opt   9, lwork   9, ok
 ** On entry to DGETSLS parameter number 10 had an illegal value
dgetsls m   2, n   3, nrhs   1, info_min   0, info_opt   0, info -10, lwork_min  10, lwork_opt   9, lwork   9, ERROR: lwork_min > lwork_opt!
 ** On entry to DGETSLS parameter number 10 had an illegal value
dgetsls m   2, n   4, nrhs   1, info_min   0, info_opt   0, info -10, lwork_min  11, lwork_opt   9, lwork   9, ERROR: lwork_min > lwork_opt!
```

[lapack-issue-getsls.cc.txt](https://github.com/Reference-LAPACK/lapack/files/4606687/lapack-issue-getsls.cc.txt)

**Comment by thijssteel** [comment]
Seems to be caused by line 260 of DGETSLS. I think `tszo` should be `tszm`, same problem in SGETSLS

**Comment by martin-frbg** [comment]
That would certainly match the surrounding code at that location. Would you like to create a PR for this ?

**Comment by thijssteel** [comment]
that was my first guess (and i still think changing line 260 would be for the better), but there are other problems. I have now confirmed that the problem is caused by the workspace query in dgelq. I'll make a PR for it soon.
