### ISSUE TITLE
LAPACKE `strict-prototypes` compiler warning for `LAPACKE_get_nancheck` prototype

### ISSUE THREAD

**Issue by ChisholmKyle** [Reference-LAPACK/lapack#416]
https://github.com/Reference-LAPACK/lapack/blob/8e1e16c6300861f096744a5ab75c3572c4b9b756/LAPACKE/include/lapacke.h#L12578

If compiler warning `-Werror=strict-prototypes` is set, the following message appears:

    include/lapacke.h:12578:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]

A simple fix: 

`int LAPACKE_get_nancheck(void);`

This issue was originally raised in OpenBLAS: https://github.com/xianyi/OpenBLAS/issues/2619

**Comment by moe123** [comment]
yes strict prototypes should always be enforced; B.A.B.A as we say.
