### ISSUE TITLE
[Version 3.9] Corrupted eigenvectors from *heev *heevd *syev *syevd for LAPACK_ROW_MAJOR layout

### ISSUE THREAD

**Issue by nboelter** [Reference-LAPACK/lapack#423]
I was considering moving from calling LAPACK directly to the higher-level LAPACKE API and noticed that the eigenvectors I got from LAPACKE_dsyev were invalid with LAPACK_ROW_MAJOR.
This error has potentially been fixed in 6ca6671d75c76f990b00b7d2aeb191804367c3be but no updated version has been released. So maybe this issue can be a warning to other users not to use these functions until a new version is released.

**Comment by martin-frbg** [comment]
this is issue #379

**Comment by nboelter** [comment]
Oh that is right! Maybe this issue can stay open anyway since not only cheev() is affected by this problem as the title of issue #379 would suggest.

**Comment by weslleyspereira** [comment]
I think #330 solved this and #379. Am I right?
