### ISSUE TITLE
NetLib.LAPACK package in C# or VB.NET issue

### ISSUE THREAD

**Issue by Howell1618** [Reference-LAPACK/lapack#439]
Hi!
I installed NetLib.LAPACK package from Nuget successfully but I can't see any function. (you can look the pic)
Is this a issue or something else I need to do?
I wish you can reply me, thanks!

Regards, Canhao

![图片](https://user-images.githubusercontent.com/61608749/92281329-ea330380-ef2d-11ea-953f-1b57208840aa.png)

**Comment by martin-frbg** [comment]
Perhaps try contacting the maintainer of that (somewhat outdated) Nuget package ? I am not aware of "official" C# or VB interfaces to the Fortran codes in netlib LAPACK so this may be just a plain build of the library itself packaged in nuget format but without any ready-to-use wrappers for calling from c#

**Comment by Howell1618** [comment]
Em......
Maybe you are right. Perhaps it isn't an official package. You see, it version still at 3.8.0. But I hope LAPACK can support C# or VB.NET later. 
Thanks for your kindly answer!
![图片](https://user-images.githubusercontent.com/61608749/92312459-54fa4280-eff3-11ea-9ab7-9c1ea39070fa.png)

**Comment by martin-frbg** [comment]
There is a C interface included (LAPACKE), maybe you can interface to that ... but in the screenshot you posted, "NLapack" looks a lot more promising if you do not plan to write your own interfaces to everything.

**Comment by andreasnoack** [comment]
Might be a good idea to close issues like these (that are unrelated to that code in the repo) to keep the issue tracker more focused.

**Comment by langou** [comment]
Right. Good idea @andreasnoack. Doing so now. J.
