### ISSUE TITLE
why build the lapack spark segment error

### ISSUE THREAD

**Issue by honghh2018** [Reference-LAPACK/lapack#441]
Hi @all,
   When i copy the make.inc.example to make.inc and type 'make' occurred below error: 
   Make [2]: leave directory "/share/NAS1/data/users/Hong/temp/lapack-3.9.0/testing/eig"
NEP: Testing Nonsymmetric Eigenvalue Problem routines
./EIG/xeigtstz < nep.in > znep.out 2>&1
/Bin/sh: Line 1: 278306 segment error 
(emesis)./ eig / xeigtstz< nep.in > znep.out 2>&1
make[1]: *** [znep.out]Error 139
Make [1]: leave directory "/share/NAS1/data/users/Hong/temp/lapack-3.9.0/testing"
make: *** [lapack_ Testing] error 2
   what happen on it, and how to fix it.
   my system was CentOS Linux release 7.3.1611 (Core)
   Bests,
    hanhuihong

**Comment by martin-frbg** [comment]
The Eigenvalue tests for COMPLEX and COMPLEX16 have unusually large stacksize requirements as they allocate a big matrix on the stack. You will need to set `ulimit -s unlimited` (or at least a much bigger value than the usual default of 8192 bytes) before running `make lapack-test`

**Comment by honghh2018** [comment]
Excellent, it worked!
Thanks.
