### ISSUE TITLE
The lapack compile successfully for JAGS 'make' error 

### ISSUE THREAD

**Issue by honghh2018** [Reference-LAPACK/lapack#442]
Hi @all,
     I build the lapack as to compile the JAGS, because the JAGS compile dependent on lapack library.
     When i compile the lapack done, it generate the *.a file, so i configure the JAGS files like below,
      ./configure --with-lapack=/opt/Software/lapack-3.9.0/liblapack.a --with-blas=/opt/Software/lapack-3.9.0/librefblas.a
     and it done  well, and the i type 'make' to start compiling the JAGS showing error like below,
      
![image](https://user-images.githubusercontent.com/41668708/92476515-a7b14580-f211-11ea-8df1-a9d4cced3be2.png)
     what should i do for this issue.
     Best,
     hanhuihong

**Comment by martin-frbg** [comment]
Try to do what the message suggests, i.e. add `-fPIC` to the CFLAGS and FFLAGS lines in the LAPACK make.inc and recompile.

**Comment by honghh2018** [comment]
Hi @martin-frbg ,
     While I try your propose,  it still showing same error.
     The make.inc that i add -fPIC was showing below.
![image](https://user-images.githubusercontent.com/41668708/92545092-f8f91d80-f281-11ea-94a7-78e869c8f1ea.png)
     The error still occurred.
      
![image](https://user-images.githubusercontent.com/41668708/92545255-53927980-f282-11ea-963a-caf3a3c3be49.png)
     The lapack compiled result like red arrow showing below.
       
![image](https://user-images.githubusercontent.com/41668708/92545336-7fadfa80-f282-11ea-86bb-d04da59ff438.png)
     Best,
     hanhuihong

**Comment by langou** [comment]
From the error message, I think you need to create and link with a shared LAPACK library and BLAS library (so a ``.so`` and not ``.a``.)

**Comment by honghh2018** [comment]
Thanks, @langou 
 But the lapack compiled can not be generated *.so file. it just make *.a files when run over the 'make' command within the lapack folder.
  So, how can i compile the *.so file when run 'make' command ?
   Any advice would be appreciated
   Best,
   hanhui

**Comment by martin-frbg** [comment]
I think for compiling to .so you would currently use the `cmake` build system rather than `make`, but you could also try a quick
`gfortran -shared -o liblapack.so liblapack.a libtmglib.a` and `gfortran -shared -o librefblas.so librefblas.a`  with the .a files you already have compiled with -fPIC.
