### ISSUE TITLE
GGGLM leaves Y uninitialized for N=0

### ISSUE THREAD

**Issue by amigalemming** [Reference-LAPACK/lapack#446]
In case of N=0, the correct result would be Y full of zeros.
Instead, the function returns early and leaves Y uninitialized.
The function documentation does not mention that this case is excluded or that Y must be initialized by the user.

**Comment by thijssteel** [comment]
N=0, means we have an unconstrained problem. This seems like a reasonable use case.
I'll make a PR with a fix.

**Comment by jschueller** [comment]
@langou looks like this is fixed now

**Comment by langou** [comment]
Yes, indeed. Need to close the issue! Thanks for the reminder.
