### ISSUE TITLE
Reference-LAPACK/lapack vs Reference-LAPACK/lapack-release

### ISSUE THREAD

**Issue by JHenneberg** [Reference-LAPACK/lapack#450]
Hey,

why are there two *.gits existing representing more or less the same? Do I miss something?

`Reference-LAPACK/lapack-release` is missing v.3.9.0 and all recent commits of course and `Reference-LAPACK/lapack` is missing the tags down from 3.6.0.
In the release version different branches are representing the tags.

If all tags down to 3.1.0 could be implemented as tags in `Reference-LAPACK/lapack` `Reference-LAPACK/lapack` could be deleted.

**Comment by martin-frbg** [comment]
I suspect this is simply a result of converting from whatever CVS system was used prior to 3.7 and the move to github. What would be gained by deleting one of them and retroactively tagging releases in the other (which may be tedious or even technically impossible, depending on how source trees where handled in earlier days, and in any case would remove the "archival" quality of having the old releases exactly as they were created) ?

**Comment by JHenneberg** [comment]
The benefit would be less confusion because of consistency. Now there is overlapping data. 

For example someone is searching for the newest release version of lapack and he finds the repoistory `Reference-LAPACK/lapack-release` first. Then he is taking 3.8.0 falsfully for the newest one. 
Also providing feedback by creating Issues is right now done in both repositories and additionaly on netlib.

If it should be kept for archival quality it should be marked as such with reference to the current SCM and issues should be deactivated to avoid confusion.

**Comment by martin-frbg** [comment]
The README.me in the "lapack-release" repo already points here, and I do note that this setup appears to have worked for the past couple of years, however unusual it might look. (If anything a 3.9.0 branch might need to be added to the lapack-release repository, I suspect both maintainers had to move their attention to novel teaching conditions created by the covid pandemic soon after the 3.9.0 release).

**Comment by ilayn** [comment]
They just forgot to add 3.9.0 to `lapack-release` probably. Seems like an SVN habit to have this as trunk and the other as the release copy.

But hardly ever, people use GitHub for LAPACK distribution anyways since most either goes to NetLib for download or use some other specialized implementation anyways.

**Comment by JHenneberg** [comment]
>  I do note that this setup appears to have worked for the past couple of years, however unusual it might look. 

This does not mean it is the perfect setup or there can not be adjustments.

> (If anything a 3.9.0 branch might need to be added to the lapack-release repository, I suspect both maintainers had to move their attention to...

This could be avoided for example as simple it might look. 

> They just forgot to add 3.9.0 to lapack-release probably. Seems like an SVN habit to have this as trunk and the other as the release copy.

I agree, it looks like SVN branch, trunk, tag structure.

**Comment by langou** [comment]
Hi, I am not against reorganization of the overall structure and go back in time to make things following the new reorganized structure. We indeed moved from SVN to GIT a few years back, and then a few updates might have slipped through. If someone wants to take the lead on this, tag, restructure, and have the LAPACK GitHub looks and feel like an example of best Git repository practice, this would be great. Julien.

**Comment by martin-frbg** [comment]
I have no problem with that except that I have seen "let's rearrange the repository" become the end of more than one "legacy" project, and I am far more concerned about unhandled issues and new functionality not getting approved.

**Comment by jfowkes** [comment]
This is very confusing as the tagline for lapack-release is "LAPACK official release branches", any chance this could be changed to something like "Old LAPACK release branches"?

**Comment by langou** [comment]
Hi @jfowkes. "LAPACK official release branches" is not confusing to me. We could add the world "previous" release branches. I'll be OK adding "previous", but my preference is to leave things as is. Comments welcome. @langou

**Comment by jfowkes** [comment]
Hi @langou, adding "previous" would be great. When I read "official release branches" I assumed that all the release branches would be there and got very confused when the latest ones were missing.

**Comment by weslleyspereira** [comment]
The repository lapack-release was archived after https://github.com/Reference-LAPACK/lapack-pre-github-historical-releases/pull/8. We updated the README with the text:

```
This repository contains all LAPACK releases from [3.1.0](https://github.com/Reference-LAPACK/lapack-release/tree/lapack-3.1.0) to [3.10.0](https://github.com/Reference-LAPACK/lapack-release/tree/lapack-3.10.0). This list includes historical pre-GitHub releases. LAPACK releases are now published at https://github.com/Reference-LAPACK/lapack/releases. Check out the [latest release](https://github.com/Reference-LAPACK/lapack/releases/latest).
```

I think we can close this discussion. Please, let me know if there is something missing from this discussion so I can reopen it. Thanks!
