### ISSUE TITLE
Cannot succesfuly link all component for using LAPACKE

### ISSUE THREAD

**Issue by Daractive** [Reference-LAPACK/lapack#456]
I don't know if it's the right place, but I'm stumped and not a single commonly proposed answer seems to work.
I try to use LAPACKE with VS 2019. I downloaded this very repo and run it through CMake (setting as Win32, since trying to turn any project into x64 made VS choke on its own dependencies and refused to acknowledge headers). In the project itself, I've passed the headers localisation to VC++ and C++, .lib files localisation to VC++ and the very .lib files (blas.lib, lapack.lib, cblas.lib, lapacke.lib and ifconsol.lib) to Linker settings. In the code, I firstly engaged CBLAS with cblas_dgemv which seemingly worked (meaning that debug and library settings are consistently Win32), but once I tried using LAPACKE's LAPACKE_dgesv I got hit with "unrecognised external symbol _dgesv_ called in function _LAPACKE_dgesv_work" called from lapacke.lib. If I understand it right, it failed at the very end of linking when trying to access basic LAPACK elements. Has anyone encountered something similar or have any idea how to fix this?
In advence thanks for your time.

**Comment by langou** [comment]
I am no expert in all this, but it seems that you are only linking with LAPACKE. LAPACKE defines _LAPACKE_dgesv_work, but does not define dgesv. DGESV is in LAPACK. So you need to have LAPACKE and LAPACK in your linking sequence (and the BLAS). Also, this might be a name mangling problem. So it seems that your compiler is expecting to find ``dgesv`` but maybe VS2019 renamed it _dgesv, etc. Please note that the LAPACK library is in FORTRAN. So to install LAPACK, you would need a FORTRAN compiler. LAPACKE is a C wrapper library on top of the LAPACK FORTRAN library. I am not sure how much I wrote help. I tried to give some explanations on a few things. J.

**Comment by Daractive** [comment]
Sadly, I think most of these have already been adressed. I do have an Intel FORTRAN compiler (since it was a must to build those with CMake and if that was the source I don't think CBLAS would work). And , as you can see in my original post I've got all the libs included (with ifconsol.lib being the FORTRAN compiler one, since VS couldn't find it). The only one I don't really know how to possibly check is the mangling one. I can see that the files have mangling defining headers for CBLAS and LAPACKE but none for the basic ones. Either way, I'm still mostly in the dark.
None the less, thank you.

**Comment by langou** [comment]
So in Linux we would do something like ``nm liblapack.a | grep -I dgesv`` to see the mangling. I do not know if such a command exist for a .lib on Windows. Then you can configure your LAPACKE to have the correct mangling. I am sorry for not being more useful on that one.

**Comment by martin-frbg** [comment]
As far as I have been told recently, the ABI of the Intel Fortran compiler is incompatible with that of VS , so you would _probably_ need to compile the C/C++ with the Intel compiler as well (though your apparent success with (C)BLAS seems to suggest this is not strictly true)

**Comment by martin-frbg** [comment]
The `nm` equivalent on Windows is `dumpbin` (which comes with VS, so needs to be called from a VS-enabled shell to have it in the PATH) , the command would probably be `dumpbin /symbols /exports liblapack.lib`

**Comment by Daractive** [comment]
Changing compiler to Intel C++ changed nothing (as expected).
The only relevant (I think) line of dumbin output was:
002 00000000 SECT1  notype ()    External     | _DGESV
but I don't really know what to make of it. For the sake of anybody with any potential knowledge of such things I attach
dumpbin output po lapack.lib and, what I believe is, current mangling rules for LAPACKE.
[output.txt](https://github.com/Reference-LAPACK/lapack/files/5396811/output.txt)
[lapacke_mangling.txt](https://github.com/Reference-LAPACK/lapack/files/5396812/lapacke_mangling.txt)

**Comment by langou** [comment]
Maybe try -DUPPER as a compilation flag. There is an underscore at the start of all routines, I think we should not worry about this. The one thing that appears in ``output.txt`` is that all FORTRAN routines are with the underscore at the start (we do not worry about this) but they are also all upper caps. Your compiler is complaining of not finding _dgesv (lower cap), and indeed your .lib has _DGESV (upper cap), so we need to tell LAPACKE to call for upper cap routines. So all in all, I'll try to recompile LAPACKE with -DUPPER.

**Comment by Daractive** [comment]
Where should I use this flag? Would doing so in VS while building libraries suffice or should I alter the files before running CMake? If so, which ones? If it helps I'm using this repository so if you understand those "automakers" you can point here (I'm pretty green when it comes to those).

**Comment by langou** [comment]
Do not alter any file! :) Yes to "when in VS while building the library". ``My bet would be on make.inc.ifort`` Actually no. -DUPPER would be a C compiler flag that you give to the C compiler compiling LAPACKE. Then you would leave your LAPACK compiled as is.

**Comment by Daractive** [comment]
Well, it seems that, for the time being, it works. Gotta admit though it requires some serious wizardry. Either way, both of you have my sincere thanks and with that being said I'm closing the issue.
