### ISSUE TITLE
There is unused var  JDUM described in /TESTING/EIG/serrgg.f

### ISSUE THREAD

**Issue by elivanova** [Reference-LAPACK/lapack#46]
$less  /TESTING/EIG/serrgg.f
. . . . .
80        INTEGER DUMMYK, DUMMYL, I, IFST, ILO, IHI, ILST, INFO,
81     $ J, M, NCYCLE, NT, SDIM, LWORK, JDUM

Should be:
80        INTEGER DUMMYK, DUMMYL, I, IFST, ILO, IHI, ILST, INFO,
81     $ J, M, NCYCLE, NT, SDIM, LWORK

**Comment by langou** [comment]
Well spotted! Thanks Elena. I am contacting you by regular email to see how you want to proceed to apply this patch to the master branch. Best wishes, Julien.

**Comment by langou** [comment]
Hello. This is fixed. See `7d5e4cecc38924d6c6361237d9a097152a1fdcab`. Julien.
