### ISSUE TITLE
Optimal packing in XLAQR5

### ISSUE THREAD

**Issue by thijssteel** [Reference-LAPACK/lapack#476]
The paper "Optimally Packed Chains of Bulges in Multishift QR Algorithms" by L. Karlsson et al. describes a way to reduce the size of the computational window in XLAQR5 (and thus the computational cost) without reducing the number of shifts.

Reported speedups are around 20%. Seems worthwhile to me, especially since dlaqr0 is one of the most important routines in this library.

I'll take a stab at implementing it when I can find some time.

**Comment by thijssteel** [comment]
So far, the implementation is going well, but supporting `KACC = 2` is more difficult than i'd thought.

Does anyone know whether `KACC = 2` is still important on modern machines?
The paper mentioned that at best, it resulted in negligable speedup for them and it's the same on my machine.
@martin-frbg perhaps you know more about this from OpenBLAS, is `DTRMM` more difficult to optimize or something?

If it's no longer that relevant, i'll remove that optimization.

**Comment by martin-frbg** [comment]
I don't feel qualified to answer this, as my involvement with OpenBLAS is more by accident than by vocation and I cannot claim any algorithmic breakthroughs. That said, I am not aware of DTRMM being more difficult to optimize.

**Comment by langou** [comment]
Hi @thijssteel, Can you explain more what the trade-off is? So we can use TRMM or GEMM to update the far-from-diagonal matrix entries, TRMM uses 2x less FLOPS than GEMM, GEMM performs at higher FLOPS rate than TRMM. So sometimes GEMM is faster than TRMM. By default the code uses TRMM. If KACC=2, then the code uses GEMM instead of TRMM. And you wonder whether it is worth to do the GEMM-based code. Do I have this correct? Do I have this reverse? Not at all correct? Typically how big are the matrices used for the update? Cheers, @langou

**Comment by thijssteel** [comment]
It's a bit more complicated.

So here's the nonzero pattern for a typical U, the accumulated reflections.
![image](https://user-images.githubusercontent.com/18015192/106378759-77786800-63a7-11eb-82de-ec37f21df143.png)

We can split the matrix into 4 parts, 2 being triangular and 2 being (almost) dense. We can the use a combination of DGEMM and DTRMM to calculate the matrix-matrix product (this is KACC=2). This means that we save not 50%, but 25% of the flops (or a little more because the bottom right triangular matrix is even smaller). On top of that, the matrices are half as big (probably means less multithreading, but not sure)
If we don't do that trick, we just use DGEMM once.

Because of a denser accumulation matrix, the speedup of using DTRMM is going to be less that it is now. So if it's already negligable, it doesn't seem worth it.

**Comment by langou** [comment]
Thanks for explaining @thijssteel. Yes, saying: ``we are going to break 1 20x20 GEMM in 4 10x10 GEMMs`` might be a very bad idea and we might see quite less performance from the 4 10x10 GEMMs than on the 1 20x20 GEMM, and then yes, the 2 TRMM will do less FLOPS. So you recoup this loss of performance there. My opinion: It does not seem that implementing KACC=2 is a high priority.
