### ISSUE TITLE
Bug in the comments to CTREVC3 / ZTREVC3

### ISSUE THREAD

**Issue by elivanova** [Reference-LAPACK/lapack#48]
In /SRC/ctrevc3.f
instead of
    21  *       SUBROUTINE CTREVC3( SIDE, HOWMNY, SELECT, N, T, LDT, VL, LDVL,
    22  *                           VR, LDVR, MM, M, WORK, LWORK, RWORK, INFO )
should be
    21  *       SUBROUTINE CTREVC3( SIDE, HOWMNY, SELECT, N, T, LDT, VL, LDVL,
    22  *                           VR, LDVR, MM, M, WORK, LWORK, RWORK, LRWORK, INFO )
The same in the case of /SRC/ztrevc3.f

**Comment by langou** [comment]
Thanks Elena. See: `20ebed48e472f1ac2919601d8bb44d8e84fc2e9b`
