### ISSUE TITLE
make[2]: *** [SRC\CMakeFiles\lapack.dir\build.make:28035: bin/liblapack.dll] Error 1

### ISSUE THREAD

**Issue by ChrisNabold** [Reference-LAPACK/lapack#482]
I try to compile Lapack 3.9.0 using only Mingw-64 compilers and Cmake .
I set the CMake parameters to Build Lapacke and Build shares libs to on. After make without errors until ...

[ 44%] Building Fortran object SRC/CMakeFiles/lapack.dir/zgesvdq.f.obj
[ 44%] Linking Fortran shared library ..\bin\liblapack.dll
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(string_intrinsics.o):(.text$_gfortran_concat_string+0x0): multiple definition of `_gfortran_concat_string'
../lib/libblas.dll.a(d000008.o):(.text+0x0): first defined here
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(string_intrinsics.o):(.text$_gfortran_string_len_trim+0x0): multiple definition of `_gfortran_string_len_trim'
../lib/libblas.dll.a(d000038.o):(.text+0x0): first defined here
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_transfer_integer_write+0x0): multiple definition of `_gfortran_transfer_integer_write'
../lib/libblas.dll.a(d000058.o):(.text+0x0): first defined here
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_transfer_character_write+0x0): multiple definition of `_gfortran_transfer_character_write'
../lib/libblas.dll.a(d000053.o):(.text+0x0): first defined here
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_st_write+0x0): multiple definition of `_gfortran_st_write'
../lib/libblas.dll.a(d000032.o):(.text+0x0): first defined here
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_st_write_done+0x0): multiple definition of `_gfortran_st_write_done'
../lib/libblas.dll.a(d000033.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make[2]: *** [SRC\CMakeFiles\lapack.dir\build.make:28035: bin/liblapack.dll] Error 1
make[1]: *** [CMakeFiles\Makefile2:261: SRC/CMakeFiles/lapack.dir/all] Error 2
make: *** [Makefile:170: all] Error 2

**Comment by weslleyspereira** [comment]
Hi @ChrisNabold. Have you tried @kimumasamune's solution https://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=4&t=5315#p12704

The original solution was found in
https://qiita.com/kimurap/items/756e7d38622cad34773b

**Comment by syby119** [comment]
> Hi @ChrisNabold. Have you tried @kimumasamune's solution https://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=4&t=5315#p12704
> 
> The original solution was found in
> https://qiita.com/kimurap/items/756e7d38622cad34773b

Thank you. The solution add '-Wl,--allow-multiple-definition' definitely solved the problem on my win10 computer.
