### ISSUE TITLE
Implicit typing

### ISSUE THREAD

**Issue by thijssteel** [Reference-LAPACK/lapack#484]
@weslleyspereira recently found a typo in a PR of mine, a typo that would have been impossible without implicit typing.

It would surprize me if any of the routines actually used implicit typing, so it probably always points to a bug.

I propose that we add `IMPLICIT NONE` to all the subroutines. Or perhaps add `-fimplicit-none` to the CI.

**Comment by thijssteel** [comment]
apparently, i made another mistake with implicit typing in one of my first PR's, i'll make a fix soon.

**Comment by weslleyspereira** [comment]
Thanks @thijssteel ! I think using the flag `-fimplicit-none` is the best first option since it is less intrusive.
