### ISSUE TITLE
Tipos in comments in /SRC/cbbcsd.f

### ISSUE THREAD

**Issue by elivanova** [Reference-LAPACK/lapack#49]
In /SRC/cbbcsd.f
Instead of
276 *> RWORK is REAL array, dimension (MAX(1,LWORK))
277 *> On exit, if INFO = 0, WORK(1) returns the optimal LWORK.
Should be:
276 *> RWORK is REAL array, dimension (MAX(1,LRWORK))
277 *> On exit, if INFO = 0, RWORK(1) returns the optimal LRWORK.
The same for /SRC/zbbcsd.f

**Comment by langou** [comment]
Thanks Elena. See: `3a4585b67e8cba600cca746a9ba1562518b97ba4`. Julien.
