### ISSUE TITLE
How to get my libtmglib.so?

### ISSUE THREAD

**Issue by benz725** [Reference-LAPACK/lapack#490]
Things is like that:
I want to use cmake to compile my mxnet project. I have installed LAPACK followed the README.md tutorial:

>    mkdir build
>    cd build
>    cmake -DCMAKE_INSTALL_LIBDIR=$HOME/.local/lapack ..
>    cmake --build . -j --target install
I only get some .a files in my .local/lapack dir (libblas.a, liblapack.a).

When I use cmake to compile my mxnet project,  I added this line in my CMakeLists.txt: 

> find_package(LAPACK CONFIG REQUIRED)

then I get this error reported:

> CMake Error at /home/benz/miniconda3/lib/cmake/lapack-3.9.0/lapack-targets.cmake:84 (message):
>   The imported target "tmglib" references the file
> 
>      "/home/benz/miniconda3/lib/libtmglib.so"
> 
>   but this file does not exist.  Possible reasons include:
> 
>   * The file was deleted, renamed, or moved to another location.
> 
>   * An install or uninstall procedure did not complete successfully.
> 
>   * The installation package was faulty and contained
> 
>      "/home/benz/miniconda3/lib/cmake/lapack-3.9.0/lapack-targets.cmake"
> 
>   but not all the files it references.
> 
> Call Stack (most recent call first):
>   /home/benz/miniconda3/lib/cmake/lapack-3.9.0/lapack-config.cmake:7 (include)
>   CMakeLists.txt:1014 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/benz/mxnet/build/CMakeFiles/CMakeOutput.log".
> See also "/home/benz/mxnet/build/CMakeFiles/CMakeError.log".

The compiler could not found the libtmglib.so file, But when I installed the lapack, I only get some .a files, how to get my libtmg.so file?
By the way, my system is Ubuntu 18.04, the arch is x86-64.
Thanks for your help.

**Comment by martin-frbg** [comment]
Try `-DBUILD_SHARED_LIBS=ON` to get shared libraries, and I think you may need either `-DBUILD_TESTING=ON` or `-DLAPACKE_WITH_TMG=ON` to get libtmg built at all.

**Comment by weslleyspereira** [comment]
Hi @benz725, are you still in trouble with getting the `libtmglib.so` ?

**Comment by benz725** [comment]
> Hi @benz725, are you still in trouble with getting the `libtmglib.so` ?

No，follow the instructions of the @martin-frbg can solve this problem.

**Comment by langou** [comment]
Excellent. Let us close this issue then.
