### ISSUE TITLE
There should be a new release

### ISSUE THREAD

**Issue by marvinbernhardt** [Reference-LAPACK/lapack#509]
I was wondering why there is no new release, e.g. 3.9.1

For example #379 was solved by #330 over a year ago. I still have to tell people to not update lapack to 3.9 if they want to use my software.

**Comment by langou** [comment]
Hi @marvinbernhardt, Thanks for the feedback. Good that you shake us up a little. Thanks. So based on your feedback, @julielangou has been working today on releasing 3.9.1. See: https://github.com/Reference-LAPACK/lapack/releases/tag/v3.9.1 . Yes this is a good idea. We are working on 3.10.0 with a lots of top notch features, but we are a few months out, and 3.9.0 deserves to be patched. We'll be working on doing a 3.9.1 release soon then. And then the goal is to get 3.10.0 out in June 2021. @langou

**Comment by julielangou** [comment]
Release of LAPACK 3.9.1 on April 1st 2021

**Comment by marvinbernhardt** [comment]
thank you!
