### ISSUE TITLE
Documentation for the 3.9.1 release

### ISSUE THREAD

**Issue by albert-github** [Reference-LAPACK/lapack#516]
I see that the 3.9.1 version has been released (https://github.com/Reference-LAPACK/lapack/archive/v3.9.1.tar.gz), though there is no mention of this versions on:
- https://github.com/Reference-LAPACK/lapack/
- http://www.netlib.org/lapack/explore-html/
- http://www.netlib.org/lapack/
  also the links on these pages point to some older versions e.g. http://www.netlib.org/lapack/release_notes.html has as last entry 3.7.0 (though I think at least 3.9.0 release notes are present: http://www.netlib.org/lapack/lapack-3.9.0.html)

**Comment by weslleyspereira** [comment]
Hi. The prerelease 3.9.1 will become a release soon. We are working on that right now.

You are right! I haven't seen this wrong link. We shall fix it for release 3.9.1. Thank you!

**Comment by albert-github** [comment]
The package name didn't reveal to me it was a pre-release so I thought it was a release already.

**Comment by weslleyspereira** [comment]
Sorry for this misunderstanding, you were right. I just changed the git tag from v3.9.1 to v3.9.1-pre. Now we have:
https://github.com/Reference-LAPACK/lapack/archive/v3.9.1-pre.tar.gz
Thanks again!
