### ISSUE TITLE
Should we erase the version number from the files?

### ISSUE THREAD

**Issue by weslleyspereira** [Reference-LAPACK/lapack#517]
Version numbers are useful when you look directly at a file, but:

1. maintaining them involves extra work;
2. they generate inconsistencies with time;
3. (from @langou) they generate a huge diff files at each release that clutters the real diff between one version and the next;
4. (from @langou) files with version number written in them cannot be trusted, you want to do a diff anyway to check, version numbers might help to locate the correct version faster. GitHub can be trusted.

Since everyone that collaborates in Lapack uses Git, we can use `git tag` and remove the explicit mention of versions on each file. We could remove it in the next release 3.9.1 coming soon.

So, the question is: should we erase the version number from the files? Thumbs up for __YES__ / Thumbs down for __NO__
Please, let us discuss it.

**Comment by julielangou** [comment]
Most people are not aware of LAPACK Github, and LAPACK get included in packages so users lost track sometimes of the version they are using.
As a consequence, a lot of people do not know which version they downloaded.. this is actually why we have a version routine which returns the LAPACK version number. I found that more helpful that a GitHub tag for our end users.
I am ok with any decision.

**Comment by julielangou** [comment]
Close with #522 - version and date are gone from source files except some rare case, i.e BLAS code as the written date is part of the legend!
