### ISSUE TITLE
Codespell report for "LAPACK" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [Reference-LAPACK/lapack#518]
I see that there is a lot of work on a new LAPACK release. If this demanding work should become too exhausting, a simple task might be just right for relaxation: For this purpose I have configured on the FOSS server [fossies.org](https://fossies.org) (that supports also [LAPACK](https://fossies.org/lapack)) a kind of continous [codespell report](https://fossies.org/features.html#codespell) for the GitHub master version of LAPACK:

 &nbsp;https://fossies.org/linux/test/lapack-master.tar.gz/codespell.html

That version independent URL hopefully always redirects to the report for the latest "master" version identified by the short commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The data are residing within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines. The report should be available at least for some weeks and the refresh rate is currently half-hourly.

Congratulation, surprisingly few spelling errors were found. Although after a first review some obviously wrong matches ("False Positives") are already filtered out (ignored) please inform me if you find more of them so that I can exclude them if applicable.

Spelling corrections certainly have a low priority, but they may also contribute to the overall quality of a software project.

**Comment by weslleyspereira** [comment]
Thanks @jschleus! I've just applied all suggestions from the FOSS server, and there were no false positives.

**Comment by weslleyspereira** [comment]
I've just found one spelling error not reported "invesrse"

**Comment by jschleus** [comment]
Oops, this variant is really not present in any of the used dictionaries. Thanks for the information, I have added "invesrse"  and the also missing "invesre" to Fossies small own extra-dictionary.

**Comment by langou** [comment]
Yes. Count on the LAPACK team for doing crazy unheard-of typos. 😂

**Comment by jschleus** [comment]
Wow, congratulation, not a single error was found anymore. By the way, if a suitable mail address is available, principally also a short automated notification mail can be sent if Fossies finds a new spelling error in "master". But this may be overkill and in case of frequent errors (which is probably not to be expected) also a bit annoying.

**Comment by langou** [comment]
@weslleyspereira and I were speaking about exactly this: ``how to not forget doing the Fossies spell check for future releases``. (1) Ideally it would be great to have an Fossies integration similar as what we have with Appveyor, Travis or Codecov: each PR runs through the CI automatically. (2) For now, I do not think there is a good email address to receive the email of Fosses. So we'll have to remind ourselves and check. (3) We could add this as a step in our release workflow. Doing so should do the trick.

**Comment by zerothi** [comment]
Alternatively LAPACK development could have a discussion page (discord/gitter/matrix/slack) and then I guess Fossies spell checker could hook into those posting results for every commit, possibly only if there is a negative result.

That is done for many projects.

**Comment by weslleyspereira** [comment]
Hi, @jschleus. The word "comlpex" is another example of a False Negative.

**Comment by jschleus** [comment]
Good catch. The word "comlpex" was added to the [Fossies own extra dictionary](https://fossies.org/warix/codespell.dictionary.fossies_extra.txt) and a new codespell run forced.
