### ISSUE TITLE
There are no tests for Windows on Travis CI

### ISSUE THREAD

**Issue by weslleyspereira** [Reference-LAPACK/lapack#523]
We are still missing a continuous integration test for Windows. I plan to add it in the near future, but I would be happy to review a PR if one wants to start to solve it.

**Comment by ilayn** [comment]
Travis stopped OSS support very recently. So it's probably better if the effort is spent through either GH actions or Azure Pipelines.

**Comment by weslleyspereira** [comment]
I see... too bad. Do you have experience with one of those? I never used any of them? I would try GitHub actions first, just to not add a new tool to the repository.

**Comment by ilayn** [comment]
It's actually quite doable. We haven't encountered any specific difficulties https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by weslleyspereira** [comment]
I just started to look at it. Thanks!

**Comment by weslleyspereira** [comment]
Please, see https://github.com/Reference-LAPACK/lapack/pull/524#issuecomment-808529789. I encountered some problems on the tests for CBLAS.
