### ISSUE TITLE
Feature: Avoid using dynamic allocation in CBLAS

### ISSUE THREAD

**Issue by weslleyspereira** [Reference-LAPACK/lapack#529]
CBLAS use dynamic allocation on the following operations with row-major matrices:

- alpha A^H x + beta y (`GEMV, GBMV, HEMV, HBMV, HPMV`)
- alpha x y^H + A (`GERC, HER, HPR`)
- alpha x y^H + conj(alpha) y x^H + A (`HER2, HPR2`)

One may use the identities:

- alpha A^H x + beta y = conj( conj(alpha) A^T conj(x) + conj(beta) conj(y) )
- x y^H = ( conj(y) x^T )^T

to avoid the additional dynamic allocation. E.g.:

```C
cblas_cgemv(CblasRowMajor, CblasConjTrans,
                 M, N,
                 alpha, A, lda,
                 X, incX, beta,
                 Y, incY);
```

equals to

```C
cblas_cgemv(CblasColMajor, CblasNoTrans,
                 N, M,
                 conj(alpha), A, lda,
                 conj(X), incX, conj(beta),
                 conj(Y), incY);
Y = conj(Y);
```

**Comment by langou** [comment]
The goal would be to remove these malloc:
https://github.com/Reference-LAPACK/lapack/blob/5b07c5e702d0d6740d9a5e03e116de633b8ce4cc/CBLAS/src/cblas_cgemv.c#L80

**Comment by ACSimon33** [comment]
Correct me if I'm wrong but isn't `cgemv` already using the identity 

`alpha A^H x + beta y = conj( conj(alpha) A^T conj(x) + conj(beta) conj(y) )` ?

And we need the allocation because we can't conjugate `x` in place since it's const. `y` is conjugated in place before and after the f77 call.

**Comment by langou** [comment]
Thanks @ACSimon33. I had forgotten why we need this malloc. On a side note, COBLAS is a full C implementation of reference BLAS, and while it does not link to any optimized BLAS, there is no malloc: https://github.com/langou/coblas/blob/master/src/cblas_cgemv.c

**Comment by ACSimon33** [comment]
Yes, that is true but I think if we want to call an optimized BLAS we are forced to use the malloc. The row-major will transform `alpha A^H x + beta y` into `alpha conj(A) x + beta y` and to map that onto the standard F77 BLAS interface we always have to conjugate either `A` or `x`. 
One could think about not declaring `x` as const, conjugating it in place, and restoring it to the original values at the end. But changing that in the routine could be dangerous for software that uses those routines in a threaded context. We could provide a second interface but I'm not sure if it's worth the hassle.

**Comment by weslleyspereira** [comment]
I agree we should keep the `const` and, therefore, the `malloc`. Thanks for noting that @ACSimon33! I am closing this issue.
