### ISSUE TITLE
Turn on BLAS++, blaspp build error.

### ISSUE THREAD

**Issue by dbyoung720** [Reference-LAPACK/lapack#530]
Turn on BLAS++, blaspp build error:
FAILED: blaspp-prefix/src/blaspp-stamp/blaspp-configure

Trun off BLAS++, lapackpp also build error:
FAILED: lapackpp-prefix/src/lapackpp-stamp/lapackpp-configure

WIN10X64+ifort.exe

**Comment by zerothi** [comment]
Blaspp and lapackpp are not part of this project... So I think you are posting the wrong place.

**Comment by langou** [comment]
Hi Nick, in #465, @martin-frbg kindly helped us having some integration with BLASPP, I think @dbyoung720 is reporting an issue with #465. Julien.

**Comment by zerothi** [comment]
Ok, great. Hadn't seen that one. 👍

**Comment by martin-frbg** [comment]
@dbyoung720 can you provide the full error message please, or is that all you are seeing ? (I guess there should at least be a config.log somewhere).
I had tested #465 on Linux only, perhaps there is a problem with Windows-specific paths or tools.

**Comment by dbyoung720** [comment]
CMakelists.txt: (379 line)

> if (BLAS++)
  _display_cpp_implementation_msg("BLAS")
  include(ExternalProject)
  ExternalProject_Add(blaspp
	  URL https://bitbucket.org/icl/blaspp/downloads/blaspp-2020.10.02.tar.gz
	  #	  CMAKE_ARGS "-DUSE_CMAKE_FIND_BLAS=ON -DLIBRARY_PATH=${CMAKE_BINARY_DIR}"
	  CONFIGURE_COMMAND env LIBRARY_PATH=${CMAKE_BINARY_DIR}/lib LD_LIBRARY_PATH=${PROJECT_BINARY_DIR}/lib ${CMAKE_COMMAND} -DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR} -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} ${PROJECT_BINARY_DIR}/blaspp-prefix/src/blaspp
	  BUILD_COMMAND env LIBRARY_PATH=${PROJECT_BINARY_DIR}/lib LIB_SUFFIX="" make
	  INSTALL_COMMAND make PREFIX=${PROJECT_BINARY_DIR} LIB_SUFFIX="" install
	  )
  ExternalProject_Add_StepDependencies(blaspp build ${BLAS_LIBRARIES})
endif()

there
CONFIGURE_COMMAND env  and  BUILD_COMMAND env，It should not be recognized in windows

**Comment by martin-frbg** [comment]
Thanks. Does it work when you replace the word `env` with `${CMAKE_COMMAND} -E env` on both lines ?
[CMakeLists.txt](https://github.com/Reference-LAPACK/lapack/files/6283759/CMakeLists.txt)

**Comment by dbyoung720** [comment]
FAILED: BLAS/SRC/CMakeFiles/blas.dir/dznrm2.f90.obj
lapack\BLAS\SRC\dznrm2.f90(89): error #5149: Illegal character in statement label field  [f] function DZNRM2( n, x, incx )
lapack\BLAS\SRC\dznrm2.f90(89): error #5149: Illegal character in statement label field  [u] function DZNRM2( n, x, incx )
lapack\BLAS\SRC\dznrm2.f90(89): error #5149: Illegal character in statement label field  [n] function DZNRM2( n, x, incx )
lapack\BLAS\SRC\dznrm2.f90(89): error #5149: Illegal character in statement label field  [c] function DZNRM2( n, x, incx )
lapack\BLAS\SRC\dznrm2.f90(89): error #5149: Illegal character in statement label field  [t] function DZNRM2( n, x, incx )

**Comment by martin-frbg** [comment]
Ok that isn't me now, must be some fallout from #514 (guessing a stray TAB character or similar on the affected line)

**Comment by dbyoung720** [comment]
Comment out the line set(CMAKE_Fortran_FORMAT FIXED),  CMakeLists.txt line 20

FAILED: blaspp-prefix/src/blaspp-stamp/blaspp-configure
cmd.exe /C "cd /D blaspp-prefix\src\blaspp-build && cmake\3.19.4\bin\cmake.exe -E env LIBRARY_PATH=lapack/x86/lib LD_LIBRARY_PATH=lapack/x86/lib cmake/3.19.4/bin/cmake.exe -DCMAKE_INSTALL_PREFIX=lapack/x86 -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=OFF lapack/x86/blaspp-prefix/src/blaspp && cmake\3.19.4\bin\cmake.exe -E touch lapack/x86/blaspp-prefix/src/blaspp-stamp/blaspp-configure"
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:13 (project):
  No CMAKE_CXX_COMPILER could be found.

**Comment by martin-frbg** [comment]
Ah, sorry. Seems the local tree from which I copied CMakeLists.txt was outdated. I'll prepare a proper PR later today.
New message suggests that you do not have a C++ compiler installed, or at least CMAKE was unable to autodetect it.

**Comment by weslleyspereira** [comment]
Hi @dbyoung720 ! Was the problem solved by PR #531 ?

**Comment by dbyoung720** [comment]
NO

**Comment by martin-frbg** [comment]
So what part does not work - the fix in #531 should be the same as the CMakeLists.txt I had put here (updated to 3.9.1 and with the equivalent fix for lapack++). Are you still having issues with the CMAKE_CXX_COMPILER requirement for blas++  ?

**Comment by dbyoung720** [comment]
It's not solved. Why is it closed?

**Comment by langou** [comment]
Hi, I closed the issue because @martin-frbg asked a question seven days ago that I think is relevant, and his question was left unanswered. Julien.

**Comment by weslleyspereira** [comment]
Just to mention. Issue #530 was closed right after we accepted PR #531. PR was supposed to solve the issue. I forgot they were linked, sorry.

  Weslley
