### ISSUE TITLE
missing _gfortran elements when linking lapack programs

### ISSUE THREAD

**Issue by ChrisNabold** [Reference-LAPACK/lapack#532]
**Description**

**Checklist**

- [ ] I've included a minimal example to reproduce the issue
- [ ] I'd be willing to make a PR to solve this issue

**Comment by martin-frbg** [comment]
Add `-lgfortran` to the end of your gcc command line - the C compiler cannot know that one of your libraries depends on the fortran runtime.

**Comment by ChrisNabold** [comment]
I also tried to do it and receive the following error messages:

[C:\temp]gcc -o main.exe main.o -Lc:/lapack/build/lib -llapack -llapacke -lcblas -lblas -ltmglib -lgfortran

C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(write.o):(.text$get_precision+0x160): undefined reference to `quadmath_snprintf'

C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(write.o):(.text$get_float_string+0x16b): undefined reference to `quadmath_snprintf'

C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(write.o):(.text$get_float_string+0xa2f): undefined reference to `quadmath_snprintf'

C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(write.o):(.text$get_float_string+0x162c): undefined reference to `quadmath_snprintf'

C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(write.o):(.text$get_float_string+0x170a): undefined reference to `quadmath_snprintf'

collect2.exe: error: ld returned 1 exit status

 

Thank you for trying to help me

Best regards

Chris Nabold

**Comment by martin-frbg** [comment]
Add `-lquadmath` after the `-lgfortran` (and if it then starts asking about math functions like sine, add `-lm`)

**Comment by ChrisNabold** [comment]
Super!! 

It worked when adding -lquadmath

 

Thank you so much

Chris

**Comment by ChrisNabold** [comment]
Thanks to your proposal

[C:\temp]gcc -o main.exe main.o -Lc:/lapack/build/lib -llapack -llapacke -lcblas -lblas -ltmglib -lgfortran -lquadmath

[C:\temp]main

11.000000 -9.000000 5.000000 -9.000000 21.000000 -1.000000 5.000000 -1.000000 3.00000

Works fine.

Now I tried to convert it for CMAKE 

INCLUDE_DIRECTORIES(C:/LAPACK/BUILD/INCLUDE)

ADD EXECUTABLE(LAPACK_test  main.c)

TARGET_LINK_LIBRARIES(Lapack_test

C:/Lapack/build/lib/liblapack.a

C:/Lapack/build/lib/lapacke.a

C:/Lapack/build/lib/libblas.a

C:/Lapack/build/lib/libcblas.a

C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a

C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/libquadmath.a)

 

But that does not work 

The target name “C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/” is reserved 

or is not valid for certain CBASE features, such as generator expressions, and

may result in undefined behavious

 

I would be grateful if you could help me once more ..

Thank you

 

Chris Nabold
