### ISSUE TITLE
wrong protototype for LAPACK_lsame?

### ISSUE THREAD

**Issue by stefanozampini** [Reference-LAPACK/lapack#545]
**Description**
both MKL and BLIS define lsame as
`lsame( const char* ca,  const char* cb...)`
while this code uses 
`same( char* ca,  char* cb..`

```
diff --git a/LAPACKE/include/lapack.h b/LAPACKE/include/lapack.h
index a70352acd..efc7068e7 100644
--- a/LAPACKE/include/lapack.h
+++ b/LAPACKE/include/lapack.h
@@ -115,7 +115,7 @@ typedef lapack_logical (*LAPACK_Z_SELECT2)
     ( const lapack_complex_double*, const lapack_complex_double* );
 
 #define LAPACK_lsame LAPACK_GLOBAL(lsame,LSAME)
-lapack_logical LAPACK_lsame( char* ca,  char* cb,
+lapack_logical LAPACK_lsame( const char* ca,  const char* cb,
                               lapack_int lca, lapack_int lcb );
 ```
**Checklist**
 

- [ ] I've included a minimal example to reproduce the issue
- [ ] I'd be willing to make a PR to solve this issue

**Comment by weslleyspereira** [comment]
Hi @stefanozampini. I believe `lsame( const char* ca, const char* cb...)` is the most appropriate interface. Would you like to propose a PR with the changes?

I looked at OpenBLAS for curiosity. They use `lsame( char* ca, char* cb...)` - https://github.com/xianyi/OpenBLAS/blob/develop/kernel/generic/lsame.c

**Comment by ivan-pi** [comment]
For the record, problems encountered by BLIS due to differing const attributes and duplicate inclusion of the prototype are documented here: https://github.com/flame/blis/issues/145 (see posts closte to https://github.com/flame/blis/issues/145#issuecomment-822651021).

**Comment by martin-frbg** [comment]
Makes sense to me - the non-const lsame in OpenBLAS mentioned by weslleyspereira above is unchanged from the 2009 GotoBLAS2 and was certainly chosen to match the netlib LAPACK at that time.
