### ISSUE TITLE
Bad LAPACK_DIR in lapacke-config.cmake

### ISSUE THREAD

**Issue by 5tefan** [Reference-LAPACK/lapack#550]
**Description**

I've installed lapack v3.9.1 through homebrew w/ `brew install lapack`, and I'm trying to use it in a CMake project, but I have manually modify `lapacke-config.cmake` because the `LAPACK_DIR` appears to be malformed.

On fresh install with version 3.9.1, the line is:
```
set(LAPACK_DIR "${_LAPACKE_PREFIX}/lib/cmake/-3.9.1")
```

And it should be:

```
set(LAPACK_DIR "${_LAPACKE_PREFIX}/lib/cmake/lapack-3.9.1")
```

I've done a bit of digging and I believe the issue was introduced here: https://github.com/Reference-LAPACK/lapack/blob/2dafa3d2756a7825c23a8c8456781561e36668ae/LAPACKE/cmake/lapacke-config-install.cmake.in#L8 in the most recent commit.

Where perhaps `@LAPACK@` is undefined (sorry I'm at the edge of my CMake knowledge)... should it be `@LAPACKLIB@` instead?

**Checklist**

- [ x ] I've included a minimal example to reproduce the issue
- [ x ] I'd be willing to make a PR to solve this issue

**Comment by weslleyspereira** [comment]
Hi @5tefan. This is indeed a problem, and I think you got the answer.
- The same problem occurs in my Linux machine.
- The tag `@LAPACK@` was introduced in 5dd47be6720f97182a240efb8363ed58518ed12f. Based on the changes there, I think this is a typo. Could you please review this, @epsilon-0 ? Thanks in advance.

**Comment by epsilon-0** [comment]
@weslleyspereira Oops, sorry about this. Yes, this is a typo, it should've been @LAPACKLIB@.

**Comment by weslleyspereira** [comment]
Thanks!
