### ISSUE TITLE
Blue's scaling parameters ssml and sbig implemented incorrectly?

### ISSUE THREAD

**Issue by vladimir-ch** [Reference-LAPACK/lapack#554]
Blue defines `s` and `S` as:
```
s = b^floor((emin-1)/2)
S = b^ceil((emax+t-1)/2)
```
(then `ssml=1/s` and `sbig=1/S`)

Anderson modifies `ssml` a bit but seems to have a mistake/typo in `sbig` in the text and in Table I. However, the value of `sbig` in his code matches Blue's:
```
ssml = b^{-floor((emin-t)/2)}
sbig = b^{-ceil((emax-t+1)/2)}
```

Lapack has
```
!  ssml = 1/s, where s was defined in https://doi.org/10.1145/355769.355771
   real(dp), parameter :: dssml = real(radix(0._dp), dp)**( - floor( &
       (minexponent(0._dp) - 1) * 0.5_dp))
!  ssml = 1/S, where S was defined in https://doi.org/10.1145/355769.355771
   real(dp), parameter :: dsbig = real(radix(0._dp), dp)**( - ceiling( &
       (maxexponent(0._dp) - digits(0._dp) + 1) * 0.5_dp))
```
that is, `ssml` from Blue and `sbig` from Anderson.

The binary64 parameters are:
```
emin = -1021
emax = 1024
t = digits = 53
```
With these values Anderson's `ssml` and Blue's `sbig` are:
```
ssml = 2^537 = 4.4989137945431964e+161
sbig = 2^{-538} = 1.1113793747425387e-162
```
Lapack's values seem to be:
```
ssml = 2^511 = 6.703903964971299e+153 
sbig = 2^{-486} = 5.0052077379577523e-147
```

I've ported Lapack's DLASSQ and Anderson's test code to Go (https://github.com/gonum/gonum/pull/1632). With Blue's values the test passes. With Lapack's `sbig` value the test fails with what seems to be an overflow result from DLASSQ, suggesting that large values haven't been scaled down sufficiently.

Am I missing anything? Could someone check this?

**Comment by weslleyspereira** [comment]
Thanks for the details, @vladimir-ch!  I submitted a PR (#559) to fix this issue with the help of @ecanesc.
