### ISSUE TITLE
Changed return values from ROTG for zero input after recent change

### ISSUE THREAD

**Issue by vladimir-ch** [Reference-LAPACK/lapack#557]
Before #527 , ROTG was returning the following values for zero input:
```
      SCALE = DABS(DA) + DABS(DB)
      IF (SCALE.EQ.0.0d0) THEN
         C = 1.0d0
         S = 0.0d0
         R = 0.0d0
         Z = 0.0d0
```
After #527, the code has been replaced with:
```
   anorm = abs(a)
   bnorm = abs(b)
   if( anorm == zero ) then
      c = zero
      s = one
      a = b
      b = one
   else if( bnorm == zero ) then
      c = one
      s = zero
      b = zero
   else
```
Both results are ok but wouldn't it be worth preserving what values are returned for `a=b=0` across changes? For instance, by moving the test for zero bnorm to the beginning.

**Comment by ecanesc** [comment]
Agreed, if b is already 0, S/D ROTG should return c=1, s=0. Moving the test of bnorm = zero before the test of anorm = zero is the correct fix and passes all tests for me.

**Comment by weslleyspereira** [comment]
Thanks!
