### ISSUE TITLE
Correct xlaenv for lapack-3.9.1/TESTING/LIN/dchktsqr.f 

### ISSUE THREAD

**Issue by nakatamaho** [Reference-LAPACK/lapack#563]
**Description**
dchktsqr.f should clear xlaenv prior to call DERRTSQR

when we test "DTS" by the following, DTS routines failed the tests of the error exits.

$ cd lapack-3.9.1/TESTING/LIN
$ ./xlintstd < dts.in
...
 DGE drivers passed the tests of the error exits

 All tests for DGE drivers  passed the threshold (   5748 tests run)

 *** XERBLA was called from DGEQR with INFO =      6 instead of  8 ***
 *** DTS routines failed the tests of the error exits ***

 All tests for DTS routines passed the threshold (  10800 tests run)
.

This is due to derrtsqr.f expects certain xerbla values, but these values are not initialized for DERRTSQR.
I'm not sure which value to be set, but at least, following patch clears xlaenv, and set correctly later.

% diff -u  dchktsqr.f_org dchktsqr.f_new
--- dchktsqr.f_org      2021-03-26 03:25:15.000000000 +0900
+++ dchktsqr.f_new      2021-05-21 13:39:00.000000000 +0900
@@ -156,6 +156,8 @@
 *
 *     Test the error exits
 *
+      CALL XLAENV( 1, 0 )
+      CALL XLAENV( 2, 0 )
       IF( TSTERR ) CALL DERRTSQR( PATH, NOUT )
       INFOT = 0
 *

[dts.zip](https://github.com/Reference-LAPACK/lapack/files/6520131/dts.zip)

**Comment by nakatamaho** [comment]
Proposed patch

[patch-dchktsqr.f.txt](https://github.com/Reference-LAPACK/lapack/files/6520172/patch-dchktsqr.f.txt)

**Comment by weslleyspereira** [comment]
Nice catch @nakatamaho! I agree with your solution. Please see #564.
