### ISSUE TITLE
Size of WORK - LDWORK

### ISSUE THREAD

**Issue by elivanova** [Reference-LAPACK/lapack#58]
In clarfb.f the name of the parameter for the size of WORK is LDWORK.
LDWORK has been changed to LWORK everywhere else. It seems, to follow  the internal convention,
the size of WORK should be named LWORK too.

**Comment by elivanova** [comment]
The same for clarzb.f

**Comment by elivanova** [comment]
The same ctprfb.f

**Comment by elivanova** [comment]
The same ctrsna.f

**Comment by langou** [comment]
In these four subroutines ( ctrsna, ctprfb, ctprfb, and clarfb), `WORK` is a two-dimensional array and `LDWORK` refers to the leading dimension of the  two-dimensional array `WORK. This is akin to `LDA`, the leading dimension of the array `A`. 

I think the name `LDWORK` is good.

`LDWORK` is not referring to the size of `WORK` and it is not a good idea to name it `LWORK`.
