### ISSUE TITLE
Windows build with cmake intel fortran broken

### ISSUE THREAD

**Issue by billhoffman** [Reference-LAPACK/lapack#583]
**Description**
When building on Windows with cmake or perhaps any OS, the file LAPACKE/include/lapacke_mangling.h is picked up by the compiler. Insead of the cmake generated version of that found in the build tree in ./include/lapacke_mangling.h.  This gets the incorrect name mangling and you get linker errors when building LAPACKE as a shared library.

To reproduce do this:

cmake -GNinja  -DLAPACKE=ON -DBUILD_SHARED_LIBS=ON   ..
ninja

I am not sure how you want to fix it. I guess you could move LAPACKE/include/lapacke_mangling.h  to a directory that is only referenced in the Makefile. 

**Checklist**

- [x ] I've included a minimal example to reproduce the issue
- [ ] I'd be willing to make a PR to solve this issue

**Comment by weslleyspereira** [comment]
Hi @billhoffman,

I didn't get link errors in my Ubuntu using GNU compilers, GCC version 7.5.0. Can you post the error message here?
I will try to reproduce it on Windows.

Thanks,
  Weslley

**Comment by billhoffman** [comment]
Likely because that file works with the gnu linking conventions.  The error you get is when it links lapacke all of the fortran symbols are missing.

   Creating library lib\lapacke.lib and object lib\lapacke.exp
lapacke_ilaver.c.obj : error LNK2019: unresolved external symbol ilaver_ referenced in function LAPACKE_ilaver
lapacke_sbbcsd_work.c.obj : error LNK2019: unresolved external symbol sbbcsd_ referenced in function LAPACKE_sbbcsd_work
....

That should be ILAVER and SBBCSD and not lower case with an _.

**Comment by weslleyspereira** [comment]
> If I remove LAPACKE/include/lapacke_mangling.h it builds and links without error.

I think this is the correct solution, thanks @billhoffman!

The header `LAPACKE/include/lapacke_mangling.h` should be generated at compile time. The Makefile build has a rule to automatically generate `LAPACKE/include/lapacke_mangling.h` from `lapacke_mangling_with_flags.h.in`:

https://github.com/Reference-LAPACK/lapack/blob/34c829109513d32d700ad33ad5d255355979e685/LAPACKE/Makefile#L53-L55

I will propose a PR very soon.

**Comment by weslleyspereira** [comment]
Please, see #584.

**Comment by billhoffman** [comment]
Thanks, LGTM.
