### ISSUE TITLE
Building error during generating liblapack.dll

### ISSUE THREAD

**Issue by liang0724s** [Reference-LAPACK/lapack#585]
Cmake:3.18.4
Compiler: mingw-64
Visual Studio 2017 Developer Command Prompt v15.9.28
[vcvarsall.bat] Environment initialized for: 'x64'

【Cmake log】
Checking if build type is 'Coverage'
Checking if build type is 'Coverage': 0
Build tests: OFF
Looking for Fortran NONE - found
Looking for Fortran INT_CPU_TIME - found
Looking for Fortran EXT_ETIME - not found
Looking for Fortran EXT_ETIME_ - not found
Looking for Fortran INT_ETIME - found
--> Will use second_INT_ETIME.f and dsecnd_INT_ETIME.f as timing function.
Build deprecated routines: OFF
Build single precision real: ON
Build double precision real: ON
Build single precision complex: ON
Build double precision complex: ON
Using supplied NETLIB BLAS implementation
Using supplied NETLIB LAPACK implementation
LAPACKE enable
Build LAPACKE single precision real: ON
Build LAPACKE double precision real: ON
Build LAPACKE single precision complex: ON
Build LAPACKE double precision complex: ON
Windows BUILD
Build html documentation: OFF
Build man documentation: OFF
Configuring done
Generating done

【Building Log】
D:\3rdparty\lapack-3.9.1\build64>D:\mingw64\mingw64\bin\mingw32-make.exe
mingw32-make: *** No targets specified and no makefile found.  Stop.

D:\3rdparty\lapack-3.9.1\build64>D:\mingw64\mingw64\bin\mingw32-make.exe
Scanning dependencies of target blas
[  0%] Building Fortran object BLAS/SRC/CMakeFiles/blas.dir/isamax.f.obj
[  0%] Building Fortran object BLAS/SRC/CMakeFiles/blas.dir/sasum.f.obj
[  0%] Building Fortran object BLAS/SRC/CMakeFiles/blas.dir/saxpy.f.obj
[  0%] Building Fortran object BLAS/SRC/CMakeFiles/blas.dir/scopy.f.obj
...........................
[  3%] Building Fortran object BLAS/SRC/CMakeFiles/blas.dir/zher2k.f.obj
[  3%] Linking Fortran shared library ..\..\bin\libblas.dll
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.28
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
Microsoft (R) Library Manager Version 14.16.27043.0
Copyright (C) Microsoft Corporation.  All rights reserved.

  Creating library ..\..\lib\libblas.lib and object ..\..\lib\libblas.exp
[  3%] Built target blas
Scanning dependencies of target lapack
[  3%] Building Fortran object SRC/CMakeFiles/lapack.dir/sbdsvdx.f.obj
[  3%] Building Fortran object SRC/CMakeFiles/lapack.dir/sgbbrd.f.obj
[  3%] Building Fortran object SRC/CMakeFiles/lapack.dir/sgbcon.f.obj
..................................
[ 44%] Building Fortran object SRC/CMakeFiles/lapack.dir/zgesvdq.f.obj
[ 44%] Linking Fortran shared library ..\bin\liblapack.dll
D:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(string_intrinsics.o):(.text$_gfortran_concat_string+0x0): multiple definition of `_gfortran_concat_string'
../lib/libblas.dll.a(d000008.o):(.text+0x0): first defined here
D:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(string_intrinsics.o):(.text$_gfortran_string_len_trim+0x0): multiple definition of `_gfortran_string_len_trim'
../lib/libblas.dll.a(d000038.o):(.text+0x0): first defined here
D:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_transfer_integer_write+0x0): multiple definition of `_gfortran_transfer_integer_write'
../lib/libblas.dll.a(d000058.o):(.text+0x0): first defined here
D:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_transfer_character_write+0x0): multiple definition of `_gfortran_transfer_character_write'
../lib/libblas.dll.a(d000053.o):(.text+0x0): first defined here
D:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_st_write+0x0): multiple definition of `_gfortran_st_write'
../lib/libblas.dll.a(d000032.o):(.text+0x0): first defined here
D:/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_st_write_done+0x0): multiple definition of `_gfortran_st_write_done'
../lib/libblas.dll.a(d000033.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [SRC\CMakeFiles\lapack.dir\build.make:28215: bin/liblapack.dll] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:261: SRC/CMakeFiles/lapack.dir/all] Error 2
mingw32-make: *** [Makefile:170: all] Error 2

**Comment by martin-frbg** [comment]
please see #305

**Comment by liang0724s** [comment]
The solusion is here: https://github.com/Reference-LAPACK/lapack/issues/305#issuecomment-642780550
