### ISSUE TITLE
Cmake build ovewrites LD_LIBRARY

### ISSUE THREAD

**Issue by prime6809** [Reference-LAPACK/lapack#595]
**Description**

Trying to build lapack 3.10.0 on Centos 7.8.

On the target system we are using the 'modules' package so that we can have different versions of packages installed that can
be selected at run / compile time. One of the packages is gcc 11.x we have set LD_LIBRARY so that gcc can find it's versions of the libraries. 

Attempting to build using the cmake system fails at 41% not being able to find the libraries.

procedure used :
tar xvf v3.10.0.tar.gz
mkdir build-3.10.0
cd build-3.10.0
ccmake ../lapack-3.10.0
   Set the required options and generated make files 
make

Which then fails with :

[ 41%] Performing configure step for 'blaspp'
/usr/local/packages/cmake-3.20.5/bin/cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/packages/cmake-3.20.5/bin/cmake)
/usr/local/packages/cmake-3.20.5/bin/cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/local/packages/cmake-3.20.5/bin/cmake)
/usr/local/packages/cmake-3.20.5/bin/cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/packages/cmake-3.20.5/bin/cmake)
/usr/local/packages/cmake-3.20.5/bin/cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/packages/cmake-3.20.5/bin/cmake)
/usr/local/packages/cmake-3.20.5/bin/cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/packages/cmake-3.20.5/bin/cmake)
/usr/local/packages/cmake-3.20.5/bin/cmake: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/packages/cmake-3.20.5/bin/cmake)
make[2]: *** [blaspp-prefix/src/blaspp-stamp/blaspp-configure] Error 1
make[1]: *** [CMakeFiles/blaspp.dir/all] Error 2
make: *** [all] Error 2

running make VERBOSE=1

[ 41%] Performing configure step for 'blaspp'
cd /root/CentosBuild-2021/lapack/build-3.10.0/blaspp-prefix/src/blaspp-build && /usr/local/packages/cmake-3.20.5/bin/cmake -E env LIBRARY_PATH=/root/CentosBuild-2021/lapack/build-3.10.0/lib LD_LIBRARY_PATH=/root/CentosBuild-2021/lapack/build-3.10.0/lib /usr/local/packages/cmake-3.20.5/bin/cmake -DCMAKE_INSTALL_PREFIX=/root/CentosBuild-2021/lapack/build-3.10.0 -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=ON /root/CentosBuild-2021/lapack/build-3.10.0/blaspp-prefix/src/blaspp
/usr/local/packages/cmake-3.20.5/bin/cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/packages/cmake-3.20.5/bin/cmake)
/usr/local/packages/cmake-3.20.5/bin/cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/local/packages/cmake-3.20.5/bin/cmake)
/usr/local/packages/cmake-3.20.5/bin/cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/packages/cmake-3.20.5/bin/cmake)
/usr/local/packages/cmake-3.20.5/bin/cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/packages/cmake-3.20.5/bin/cmake)
/usr/local/packages/cmake-3.20.5/bin/cmake: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/packages/cmake-3.20.5/bin/cmake)
/usr/local/packages/cmake-3.20.5/bin/cmake: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/packages/cmake-3.20.5/bin/cmake)
make[2]: *** [blaspp-prefix/src/blaspp-stamp/blaspp-configure] Error 1
make[2]: Leaving directory `/storage/stsxab/CentosBuild-2021/lapack/build-3.10.0'

As you can see from the above cmake is overriding LIBRARY_PATH which is set to 

 echo $LIBRARY_PATH
/usr/local/packages/ATLAS-3.10.3/lib:/usr/lib/x86_64-linux-gnu:/usr/local/packages/ppl-0.11.2/lib:/usr/local/packages/cloog-ppl-0.15.11/lib:/usr/local/packages/gcc-11.1.0/lib64:/usr/local/packages/gcc-11.1.0/lib

I *CAN* build in the lapack folder by editing make.inc as needed and running make, however this doesn't seem to have an option for building shared libraries, nor does it have an install target.

**Comment by prime6809** [comment]
I've just checked out the version from the github repository and this also has the same problem.

**Comment by prime6809** [comment]
I've managed to solve this in my local tree, in CMakeList.txt the lines that set LIBRARY_PATH and LD_LIBRARY_PATH need
$ENV{LIBRARY_PATH}: and $ENV{LD_LIBRARY_PATH}: prepending to them respectively this allows lappack to finish building.

I'll submit a pull request for this later.

**Comment by weslleyspereira** [comment]
Fixed by #601. Please, reopen this issue in case #601 does not fix it.
