### ISSUE TITLE
Building blas and lapack as shared libraries

### ISSUE THREAD

**Issue by smijolovic** [Reference-LAPACK/lapack#611]
Digging everywhere, there doesn't seem to be any working or consistent method for building librefblas.so and liblapack.so using make. The cmake option is not an option, as inconsistencies in the results would not classify as a production ready build process, and the currently supported process is make.

Is it possible to get some guidance on how to do this?  I've seen some old examples online but none of them are working on the 3.10.0 branch.

**Comment by weslleyspereira** [comment]
Could you try the follwing quick tweak?

1. Add `-fPIC` to FFLAGS in `make.inc`. Then

2. Replace
```makefile
$(BLASLIB): $(ALLOBJ)
	$(AR) $(ARFLAGS) $@ $^
	$(RANLIB) $@
```
by
```makefile
$(BLASLIB): $(ALLOBJ)
	$(AR) $(ARFLAGS) $@ $^
	$(RANLIB) $@
	ld -shared -o ../../librefblas.so $^
```
in `BLAS/src/Makefile`.

3. If it works, do a similar tweak for the LAPACKLIB

This is not a solution, just something you can do to get a shared library quickly. It works on my Linux machine. Please, feel welcomed to submit a PR to add this functionality on LAPACK. Thanks!

**Comment by smijolovic** [comment]
That worked to produce the librefblas.so. Thank you!

For the liblapack.so...is it required to link the librefblas library?

In SRC/Makefile, I added:
ld -shared -o ../liblapack.so $^

And it produced liblapack.so. Is that all that is necessary?

**Comment by boboshaq** [comment]
Hi,

Compilatin librefblas.so was sucessfully.
Compilation liblapack(3.10.1) fails in this moment:
`gfortran -shared -o ../liblapack.so sbdsvdx.o spotrf2.o sgetrf2.o ...`

It is reproduces many of this information:
```
bin/ld: sbdsvdx.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/bin/ld: spotrf2.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/bin/ld: sgetrf2.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
...
```

and finally it is end with:
```
/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:558: ../liblapack.a] Error 1
rm la_xisnan.mod
make[1]: Leaving directory '/soft/lapack/lapack-3.10.1/SRC'
make: *** [Makefile:25: lapacklib] Error 2
```


In SRC/Makefile I was change:

> $(LAPACKLIB): $(LAPACKLIB_DEPS)
>         $(AR) $(ARFLAGS) $@ $^
>         $(RANLIB) $@

to:

> $(LAPACKLIB): $(LAPACKLIB_DEPS)
>         $(AR) $(ARFLAGS) $@ $^
>         $(RANLIB) $@
>         $(FC) -shared -o ../liblapack.so $^

What I was doing wrong? How to fix this?
Should I first compile static library?
It is possible that permissions to folders are wrong?

Regards!

**Comment by boboshaq** [comment]
OK, in my case, properly solution is:
1. Edit file lapack/make.inc:
 - add to options FFLAGS and FFLAGS_NOOPT: -fPIC
 
2. Edit file BLAS/SRC/Makefile:
- change this for BLAS:
```
$(BLASLIB): $(ALLOBJ)
        $(AR) $(ARFLAGS) $@ $^
        $(RANLIB) $@

```
to:
```
$(BLASLIB): $(ALLOBJ)
        $(AR) $(ARFLAGS) $@ $^
        $(RANLIB) $@
        $(FC) -shared -o ../../librefblas.so $^
```

- and change this for LAPACK:
```
$(LAPACKLIB): $(LAPACKLIB_DEPS)
        $(AR) $(ARFLAGS) $@ $^
        $(RANLIB) $@
```
to:
```
$(LAPACKLIB): $(LAPACKLIB_DEPS)
        $(AR) $(ARFLAGS) $@ $^
        $(RANLIB) $@
        $(FC) -shared -o ../liblapack.so $^
```
3. Run commands:
 - for BLAS:  make blaslib
 - for LAPACK: make lapacklib

This should produce 4 files in lapack dir:
1. libfrefblas.a
2. librefblas.so
3. liblapack.a
4. liblapack.so

So we have both: static (*.a) and shared(*.so) libraries for BLAS and LAPACK.

Regards!

**Comment by langou** [comment]
Great. Thanks for the "how-to" @boboshaq. Sounds good to me. Closing the issue now.
