### ISSUE TITLE
`lapacke_mangling.h` file not found for CMake build

### ISSUE THREAD

**Issue by bjack205** [Reference-LAPACK/lapack#614]
I'm trying to build LAPACK / BLAS inside of a CMake project and using the exported targets. My CMakeLists.txt file looks like this:
```
include(FetchContent)
FetchContent_Declare(lapacklib
  GIT_REPOSITORY https://github.com/Reference-LAPACK/lapack.git
  GIT_TAG aa631b4b4bd13f6ae2dbab9ae9da209e1e05b0fc
)
set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)
set(CBLAS "ON")
set(LAPACKE "ON")
FetchContent_MakeAvailable(lapacklib)

add_executable(main
  main.c
)
target_link_libraries(main
  PRIVATE
  lapacke
  cblas
)
```
With a very simple main file:
```
#include <stdlib.h>
#include <stdio.h>
#include "lapacke.h"

int main() {
  printf("Hello, world!\n");
}
```
My project configures just fine, and I've verified that it exports the `cblas` and `clapacke` targets, but when I go to build my executable it fails with 
```
[build] In file included from /home/brian/.julia/dev/SparseTOSolvers/build/_deps/lapacklib-src/LAPACKE/include/lapacke.h:36:
[build] /home/brian/.julia/dev/SparseTOSolvers/build/_deps/lapacklib-src/LAPACKE/include/lapack.h:11:10: fatal error: 'lapacke_mangling.h' file not found
[build] #include "lapacke_mangling.h"
[build]          ^~~~~~~~~~~~~~~~~~~~
[build] 1 error generated.
```
This file is supposed to be generated during the build, right? So why is this not working as expected?

Thanks!

**Comment by weslleyspereira** [comment]
Hi.
The problem is that the CMake configures the `lapacke_mangling.h` at `${LAPACK_BINARY_DIR}/include`. You are using the `lapack.h` from `lapacklib-src/LAPACKE/include/lapack.h`, i.e., from the source directory.

Can you please try to `FetchContent_MakeAvailable(lapackelib)` ? I only used FetchContent a few times, but I think this command would build lapackelib.

**Comment by bjack205** [comment]
Ah, I see the problem now. The library is including the wrong header location. I got the build to work by changing the target to use the include directory in the build path:
```
add_library(${LAPACKELIB} ${SOURCES})
set_target_properties(
  ${LAPACKELIB} PROPERTIES
  LINKER_LANGUAGE C
  VERSION ${LAPACK_VERSION}
  SOVERSION ${LAPACK_MAJOR_VERSION}
  )
target_include_directories(${LAPACKELIB} PUBLIC
  $<BUILD_INTERFACE:${LAPACK_BINARY_DIR}/include>
  $<INSTALL_INTERFACE:include>
)
```
changing [this line](https://github.com/Reference-LAPACK/lapack/blob/master/LAPACKE/CMakeLists.txt#L83) to use `LAPACK_BINARY_DIR`. This allows consumers of the target to get the correct include directory. This can also be done for CBLAS by making a similar change [here](https://github.com/Reference-LAPACK/lapack/blob/master/CBLAS/src/CMakeLists.txt#L127).

I'm not sure if this breaks anything else, but this seems like a bug to me. If you agree I'll go ahead and open a PR with the fix.

**Comment by weslleyspereira** [comment]
This seems a bug indeed. I agree with your solution. Thanks!

**Comment by langou** [comment]
Hi @bjack205, a PR would be great. J.
