### ISSUE TITLE
Is it possible to transform source-files to free-form?

### ISSUE THREAD

**Issue by MehdiChinoune** [Reference-LAPACK/lapack#639]
Fortran supported free-form since Fortran90 (~1992), which is easier to read. All the compilers out there support it.

Could I open a PR to transform the source file into free-form (with *.f90 extension)?

**Comment by langou** [comment]
Hi Mehdi, Thanks for offering to contribute. I am personally worried and not excited about this suggested massive file conversion. My preference is to not do it. I understand the merit of improved readability. converting to free form is a regular topic of conversation that we have, so thanks for opening this up again. I am happy to hear cons and pros. My current opinion is that we should abstain from doing this massive reformatting. Julien.

**Comment by MehdiChinoune** [comment]
I hope someday, LAPACK will start using Modern Fortran, instead of presenting Fortran as a language made for Punch Cards.
LAPACK is a highly-used project and being written in FORTRAN77 give a bad image about Fortran. The worse thing is that LAPACK itself doesn't support Modern Fortran by not updating LAPACK95 against the latest LAPACK.
I know people here don't care about Fortran Language (some hate it and wish it to die).

**Comment by ilayn** [comment]
Well, that's a lot of assumptions but new Fortran doesn't bring necessarily new stuff if you are just compiling the same codebase. I think what you implicitly wish to have is the codebase to switch to new Fortran standards like Python2 -> Python3 is that correct? 

Note that most of this codebase is "reference" implementation. Many backends modify parts of this code for further optimizations and probably distribute it by compiling with a new compiler. So it seems to me that you are placing your dissatisfaction in the wrong place.

**Comment by MehdiChinoune** [comment]
As I have expected, hopeless discussion.

**Comment by jeffhammond** [comment]
@MehdiChinoune You can just fork LAPACK, make all the changes you want, and then hope people use it.  If it's better, they will.  This is not a platitude, as I have personally been involved in a project that did this (technically, it was a clean-sheet reimplementation, but that's not important here).

If you are going to make LAPACK use modern Fortran, why not start with a module interface?  That is a much stronger incentive for users than fixed->free source form, which is invisible except to developers.  Intel MKL ships LAPACK95, which does something like this, but it has the wrong license for broad adoption.
