### ISSUE TITLE
what is the libgcc_s requirement in LAPACK?

### ISSUE THREAD

**Issue by jhgorse** [Reference-LAPACK/lapack#643]
Greetings,

I was trying to compile a 3rd party app for the new Apple M1 cpu and found some difficulty linking due to LAPACK's libgcc requirement. Specifically, `ld: file not found: @rpath/libgcc_s.1.1.dylib for architecture arm64`

The 3rd party build was done with clang.

The libgcc dep appeared to come from OpenBLAS/LAPACK's use of gfortran.

Is there any chance that libgcc might be mistakenly getting included in the LAPACK build?

Cheers,
Joe

**Comment by weslleyspereira** [comment]
Hi!
I have some questions to try to help you:
- Are you trying to build LAPACK with Makefile or CMake? The C Compiler is set to gcc in some make.inc files.
- Have you tried compiling LAPACK with the reference BLAS instead of OpenBLAS?

**Comment by martin-frbg** [comment]
I'm fairly certain that you will get the depencency on libgcc_s (gcc's runtime library) even just from compiling the LAPACK Fortran source with gfortran, with no C code in the mix. The alternative would be to compile everything with flang (not entirely sure if this is considered stable on the M1 yet), nvfortran or the commercial NAG fortran compiler.

**Comment by jhgorse** [comment]
@weslleyspereira, I have built it both ways. The make.inc.default from gcc to cc just worked. I had to run the */ Makefiles to generate the _mangling.h headers, but it otherwise worked without a hitch.

I do not see any references to the libgcc_s library, though I did not xref through all of it's symbols. If it grabbed any of the `long int` type numeric symbols, it does so without further issue because it is a statically linked set of .a libraries.

@martin-frbg, I did try to build flang and failed. Did not look too deep into it. I didn't know about nvfortran! Looks neat! =)

Cheers,
Joe

**Comment by weslleyspereira** [comment]
> @weslleyspereira, I have built it both ways. The make.inc.default from gcc to cc just worked. I had to run the */ Makefiles to generate the _mangling.h headers, but it otherwise worked without a hitch.

Good! We have been trying to improve the installation of the mangling files, see #584 and #616. Currently, one must run CBLAS/ and LAPACKE/ Makefiles to get the _mangling files installed.

**Comment by weslleyspereira** [comment]
We just merged a PR which improves the installation of mangling files for `lapack.h`. Please, see: https://github.com/Reference-LAPACK/lapack/pull/637

@jhgorse, May I mark this issue as solved? Thanks
