### ISSUE TITLE
Problem with zgeqrf() function

### ISSUE THREAD

**Issue by inzhevatkin** [Reference-LAPACK/lapack#644]
Good time of the day. I'm having problem implementing QR-decomposition. The problem is described [here](https://stackoverflow.com/questions/70251461/why-doesnt-qr-decomposition-work-correctly-lapacke-complex-cas). Maybe it will be easy for someone to repeat this problem and point out to me what I'm doing wrong.

**Comment by weslleyspereira** [comment]
Hi @inzhevatkin. Thanks for the message. Do you know if this problem also happens for col-major matrices? Would you be able to test it?

**Comment by langou** [comment]
I answered on Stackoverflow.

**Comment by inzhevatkin** [comment]
Thanks for such a complete answer on Stackoverflow.
