### ISSUE TITLE
Travis CI on MacOS: binary `jq` missing

### ISSUE THREAD

**Issue by cconrads-scicomp** [Reference-LAPACK/lapack#65]
Checking the why the [Travis build #99.2](https://travis-ci.org/Reference-LAPACK/lapack/jobs/164395192) of a patch failed only on MacOS, I noticed that the binary `jq` is missing and consequently, the environment variable BRANCH is always empty:

```
$ export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)

/Users/travis/build.sh: line 45: jq: command not found

(23) Failed writing body
```

**Comment by julielangou** [comment]
@cconrads-scicomp - I can see that one too...do you have any fix to suggest? 
I am a little lost on this one...

**Comment by cconrads-scicomp** [comment]
1. `jq` was added to the default Travis image in December 2014 ([source](https://docs.travis-ci.com/user/build-environment-updates/2014-12-09/)).
2. `jq` has been missing on MacOS since we started using it in the Travis builds (see [Job #45.2](https://travis-ci.org/Reference-LAPACK/lapack/jobs/148189019) / PR #19).

The Travis build started using `jq` in commit hjmjohnson@2b7d7dbd2da9ade58d58a5047149c079ae74be2b and in the commit message, the following code is referenced ([source](https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/)):
```
script:  
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
```
Note the absence of `jq`. For comparison, the LAPACK Travis build uses a combination of `curl` and `jq` to determine the pull request branch and I do not know why. @hjmjohnson

**Comment by BanzaiMan** [comment]
This is no longer an issue. See https://travis-ci.org/Reference-LAPACK/lapack/jobs/181720426, for example. The job fails for a different reason, but `jq` is found.

**Comment by turboencabulator** [comment]
I still see it there on line 54:
`/Users/travis/build.sh: line 57: jq: command not found`

**Comment by langou** [comment]
Thanks to @jschueller for fixing this. See #106 .
