### ISSUE TITLE
CMake: missing [s,d]combssq.f in [S,D]LASRC in SRC/CMakeLists.txt

### ISSUE THREAD

**Issue by scivision** [Reference-LAPACK/lapack#650]
**Description**
CMake shared build fails because missing source files in SRC/CMakeLists.txt

* SLASRC should also have: scombssq.f in SLASRC 
* DLASRC should also have dcombssq.f in DLASRC

Implemented in https://github.com/scivision/lapack/commit/b6f57d08cc164f8926a68add953372c4a0456e8f

**Comment by weslleyspereira** [comment]
Hi @scivision. scombssq.f and dcombssq.f were removed from LAPACK on #570. Please consider using the master branch or one of the releases.

**Comment by martin-frbg** [comment]
> or one of the releases.
That change was made in August, while the latest release happened in June...

**Comment by scivision** [comment]
OK thanks for the info
