### ISSUE TITLE
Please consider annotating LAPACKE_lsame with __attribute__((const)) for GCC

### ISSUE THREAD

**Issue by martin-frbg** [Reference-LAPACK/lapack#652]
Copied from https://github.com/xianyi/OpenBLAS/issues/3543 , suggested by @davidmalcolm

> LAPACKE_lsame is a case-insensitive char comparison, but is implemented in its own object file, so a compiler has no way of  knowing (without LTO) that multiple calls to it with the same inputs have the same results.
>
> GCC has __attribute__((const)) for marking functions that always return the same result on the same inputs:
> https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-const-function-attribute
> I'm the maintainer of the [GCC static analyzer](https://gcc.gnu.org/wiki/DavidMalcolm/StaticAnalyzer). When building openblas-0.3.15 with my analyzer, I noticed slightly over 2000 false positives from -Wanalyzer-malloc-leak on code like this:
> (...elided...)
> where my analyzer naively assumes that LAPACKE_lsame( vect, 'b' ) || LAPACKE_lsame( vect, 'p' ) can be true at the malloc guard, and false at the free guard; other compilers/analyzers may have similar behavior.
>
> I'm testing a fix for the GCC analyzer to take account of __attribute__((const)), and in my tests so far it fixes the OpenBLAS false positives when the attribute is added to LAPACKE_lsame. (I'm tracking this for GCC as https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104434). Presumably some kind of configuration define would be needed to support compilers that don't have the attribute.
> 
> Hope this is constructive

**Comment by weslleyspereira** [comment]
Thanks @martin-frbg !
