### ISSUE TITLE
Need test suite to verify LAPACKE interface (C based) APIs.

### ISSUE THREAD

**Issue by mopathan** [Reference-LAPACK/lapack#667]
Hi LAPACK reference team,
Currently, the test suite is present for LAPACK interface APIs (FORTRAN based test suite). But no test suite to verify LAPACKE interface. Need your support to implement test cases to verify LAPACKE (C-based) interface package (present in LAPACK reference code).
Do share your comments/queries if any.

Thanks,
Younas.

**Comment by mopathan** [comment]
Do you have any update on this?

**Comment by langou** [comment]
It is correct that there is no test suite for LAPACKE in LAPACK. LAPACKE is somewhat tested indirectly by other packages. (Such as LAPACK++.) Indeed, it would be great to have a test suite for LAPACKE.

**Comment by mopathan** [comment]
Any update on this?

**Comment by langou** [comment]
If you "need support to implement test cases to verify LAPACKE (C-based) interface package (present in LAPACK reference code)," please propose a PR. Thanks!
