### ISSUE TITLE
Travis CI MacOS environment broken

### ISSUE THREAD

**Issue by turboencabulator** [Reference-LAPACK/lapack#68]
All of my recent pull requests are failing to build on Mac with this error

> No CMAKE_Fortran_COMPILER could be found.

Did the environment change?  I see this in build 99:

```
$ export CXX=g++
$ export CC=gcc
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

and this in build 100:

```
$ export CXX=g++
$ export CC=gcc
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by turboencabulator** [comment]
Apparently [it did change](https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/).

**Comment by julielangou** [comment]
Sierra update?

**Comment by turboencabulator** [comment]
Might be able to revert it by adding `osx_image: beta-xcode6.1` to .travis.yml, but that image will go away soon.  Maybe `osx_image: xcode6.4` still works?

More info at https://docs.travis-ci.com/user/osx-ci-environment

**Comment by julielangou** [comment]
Just tried osx_image: xcode6.4...not working :-(

**Comment by BanzaiMan** [comment]
Sorry to hear about this problem. Could you tell us what command is supposed to be discovered by `cmake` with this string `CMAKE_Fortran_COMPILER`?

It was either provided on the old image by accident and we didn't take care to reinstate it in recent images, or Apple stopped providing it in recent Xcode or OS X/macOS images.

For example, on my OS X machine, I have `gfortran-4.9` available via Homebrew. If this is sufficient for your use case, you can add:

```yaml
before_install:
  - brew install gcc49
  ⋮
```

**Comment by turboencabulator** [comment]
List of compilers it looks for can be found at https://github.com/Kitware/CMake/blob/master/Modules/CMakeDetermineFortranCompiler.cmake

**Comment by julielangou** [comment]
Just adding those line make it failed ... seems home-brew is not installed on the host machine..

$ brew install gcc49
/home/travis/build.sh: line 57: brew: command not found
The command "brew install gcc49" failed and exited with 127 during .
Your build has been stopped.

**Comment by BanzaiMan** [comment]
@julielangou Homebrew is available on the Mac only, so it won't work on Linux.

@turboencabulator That is an instructive list. Thanks. `gcc49` doesn't appear to provide any of those, though, so another Homebrew package is probably needed.

Is it possible to find from the old passing build log which compiler cmake found?

**Comment by turboencabulator** [comment]
Here's the last passing build:
https://travis-ci.org/Reference-LAPACK/lapack/builds/164259737

Looks like it's finding /usr/local/bin/gfortran.  Several oddities here:

- It's in /usr/local/bin, not /usr/bin like a few lines later where it finds /usr/bin/gcc.  Maybe it was locally installed somehow?
- Says the C compiler ID is AppleClang, but why would that be installed to /usr/bin/gcc?

```
-- Setting build type to 'Release' as none was specified.
-- The Fortran compiler identification is GNU
-- Check for working Fortran compiler: /usr/local/bin/gfortran
-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes
-- Looking for Python greater than 2.6 - 
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.5", minimum required is "2.7") 
-- Using Python version 2.7.5
-- Reducing RELEASE optimization level to O2
-- Looking for Fortran NONE - found
-- Looking for Fortran INT_CPU_TIME - found
-- Looking for Fortran EXT_ETIME - not found
-- Looking for Fortran EXT_ETIME_ - not found
-- Looking for Fortran INT_ETIME - found
-- --> Will use second_INT_ETIME.f and dsecnd_INT_ETIME.f as timing function.
-- Using supplied NETLIB BLAS implementation
-- CBLAS enable
-- The C compiler identification is AppleClang 6.0.0.6000054
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
-- Verifying Fortran/C Compiler Compatibility
-- Verifying Fortran/C Compiler Compatibility - Success
-- Using supplied NETLIB LAPACK implementation
-- Building Single Precision
-- Building Double Precision
-- Building Complex Precision
-- Building Double Complex Precision
-- BUILD TESTING : ON
-- Running Summary
-- LAPACKE enable
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/travis/build/Reference-LAPACK/lapack-travis-bld
```

**Comment by langou** [comment]
Hi, can you look at the commit 58879a48fcb0a059ee96753fc6cc6341448a0015 and try to `revert` it or `improve and then commit`? The fact that Travis is broken is really an issue for us. We have had Travis broken since Oct 1s and commit 58879a48fcb0a059ee96753fc6cc6341448a0015. It would be nice to get this fixed. Reverting the commit does not fix the Travis? I was thinking that the commit was to blame, but now that I am reading this issue thread, all this seems more complicated. Anyone has a hint on what to do and how to fix. As I wrote, it would be very nice and useful to have Travis working again. Cheers, Julien

**Comment by turboencabulator** [comment]
We could disable it for Mac. Not a great solution but it would make Travis useful again.

**Comment by langou** [comment]
Thanks to @jschueller for fixing this. See #106 .
