### ISSUE TITLE
How to set compiler for LAPACK on linux with CMake

### ISSUE THREAD

**Issue by DavidSagan** [Reference-LAPACK/lapack#688]
I want to compile LAPACK with the ifort compiler on linux using CMake. Or if that is not possible, at least how to do it with the Make system. Any guidance is greatly appreciated.

**Comment by martin-frbg** [comment]
`cmake -DCMAKE_Fortran_COMPILER=ifort` (note the mixed case in the CMake variable) should work. (For GNU Make system, you would copy make.inc.ifort from the INSTALL directory to make.inc in the toplevel as mentioned in the README)

**Comment by weslleyspereira** [comment]
You can set the ifort compiler using one of the following:

1.
```sh
export FC="custom-compiler --arg1 --arg2"
```

2.
```sh
cmake ... -DCMAKE_Fortran_COMPILER='custom-compiler;--arg1;--arg2'
```

3. You can probably load the Intel environment setup. This will do step (1) automatically.
