### ISSUE TITLE
ZTREVC3

### ISSUE THREAD

**Issue by jkd2016** [Reference-LAPACK/lapack#69]
The double real constant ONE is passed into the routine ZGEMM at line 596 of ZTREVC3.

ZGEMM expects a double complex argument. This should be changed to CONE.

**Comment by langou** [comment]
Hi jkd2016, commit #633d65dc6afe9b12342f3d6add4bfc1a561a0b7f on August 29th 2016 fixed this problem. Cheers, Julien.
