### ISSUE TITLE
Compiler warnings in tests:  Rank mismatch

### ISSUE THREAD

**Issue by hjmjohnson** [Reference-LAPACK/lapack#7]
Compiler warnings are generated for:
~/lsrc/lapack-bld> gfortran --version
GNU Fortran (SUSE Linux) 4.8.3 20140627 [gcc-4_8-branch revision 212064]
Copyright (C) 2013 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

====================================

[  8%] /user/iibi/johnsonhj/lsrc/lapack/CBLAS/testing/c_dblat1.f:214.48:

               CALL STEST1(DNRM2TEST(N,SX,INCX),STEMP,STEMP,SFAC)       
                                                1
Warning: Rank mismatch in argument 'strue1' at (1) (scalar and rank-1)
/user/iibi/johnsonhj/lsrc/lapack/CBLAS/testing/c_dblat1.f:218.48:

               CALL STEST1(DASUMTEST(N,SX,INCX),STEMP,STEMP,SFAC)       
                                                1
Warning: Rank mismatch in argument 'strue1' at (1) (scalar and rank-1)

[  8%] Building C object CBLAS/testing/CMakeFiles/xscblat2.dir/c_sblas2.c.o
/user/iibi/johnsonhj/lsrc/lapack/CBLAS/testing/c_sblat1.f:214.48:

               CALL STEST1(SNRM2TEST(N,SX,INCX),STEMP,STEMP,SFAC)       
                                                1
Warning: Rank mismatch in argument 'strue1' at (1) (scalar and rank-1)
/user/iibi/johnsonhj/lsrc/lapack/CBLAS/testing/c_sblat1.f:218.48:

               CALL STEST1(SASUMTEST(N,SX,INCX),STEMP,STEMP,SFAC)       
                                                1
Warning: Rank mismatch in argument 'strue1' at (1) (scalar and rank-1)

**Comment by langou** [comment]
Hi Hans, Thanks for reporting the issue. I just fixed it. Please feel free to check the fix out. Cheers, Julien.

**Comment by hjmjohnson** [comment]
@langou Thank you for addressing this compiler warning!

Fixed in:
https://github.com/Reference-LAPACK/lapack/commit/7fb63b1cd386b099d7da6eeaafc3e7dce055a7d0
