### ISSUE TITLE
C程序调用lapack函数

### ISSUE THREAD

**Issue by shadowtwinkle** [Reference-LAPACK/lapack#708]
When calling the dgbtrs' function of LAPACK, there is a DGER function. How should the parameter 1 be passed? When I passed it, I tried many methods, saying that the parameter was illegal.
 dger_(&lm,&(*NRHS),-ONE,AB_2[(kd+1)*j],1,B[j],&(*LDB),B[j+1],&(*LDB));
 On entry to DGER parameter number  5 had an illegal value

**Comment by langou** [comment]
You need to create an integer variable say ``ione`` and then ``ione=1`` and then pass ``&ione``. Instead of calling the Fortran interface directly from C, you can try to use the LAPACKE, the C interface to LAPACK.

**Comment by langou** [comment]
And DGER is in the BLAS so you would use ``CBLAS``. Sorry. Not LAPACKE.
