### ISSUE TITLE
Why is there no LAPACKE_?langb interface?

### ISSUE THREAD

**Issue by ACSimon33** [Reference-LAPACK/lapack#722]
Hi all,

I wondered why there isn't a LAPACKE interface for `?langb`. If there is no reason against it I'm happy to implement it and submit a pull request.

**Comment by ACSimon33** [comment]
What kind of copyright header should I put into those new files? I just copy the Intel header, right?

**Comment by langou** [comment]
yes, please copy-paste Intel header file. That works. And then add your name as author, and here you go. My understanding is that Intel is holding the copyright which is just fine. The license is permissive enough, so who holds the copyright does not really matter. We just need someone to hold the copyright and for LAPACKE, this is Intel. Thanks for asking.
