### ISSUE TITLE
OpenXLF and OpenXLC 17.1.1 Build Failure

### ISSUE THREAD

**Issue by ocelotStride** [Reference-LAPACK/lapack#745]
Building with XLF fails on la_constants.f90

The following images show and example of the failure:

<img width="1019" alt="Screenshot 2022-11-04 at 16 45 43" src="https://user-images.githubusercontent.com/110676242/200071894-3b938b49-4005-47a3-aa94-b8a8f7fb8660.png">

<img width="1016" alt="Screenshot 2022-11-04 at 16 46 00" src="https://user-images.githubusercontent.com/110676242/200071902-c9409f0f-2850-42ef-b06c-1a049bf1dea2.png">

The new xlc compiler is based on clang and -qnosave is no longer relevant. I have tried digging back to find this option or an equivalent option from clang, but it appears that -qnosave hasn't been relevant to xlc since pre-16.1.1 at least (as far back as I could find documentation for).

As for how I am building, I simply copied the make.inc.XLF file from the 3.10.1 INSTALL folder and removed -qnosave from the xlc (now called ibm-clang) opts and I also dumped essl from the BLASLIB as I would prefer not to link against essl in this case.

**Comment by martin-frbg** [comment]
That error message is suspicious as there is no continuation line there, just comment lines surrounding the statement. Also this would probably have come up earlier with LLVM proper. Can you please make sure that the file is not corrupted ?

**Comment by ocelotStride** [comment]
> That error message is suspicious as there is no continuation line there, just comment lines surrounding the statement. Also this would probably have come up earlier with LLVM proper. Can you please make sure that the file is not corrupted ?

I should clarify; I'm not sure if the xlf is based on the clang family---only xlc seems to be. 

I do not think it is corrupt. I compiled with gcc/gfortran 12.2 just before this without issue. I wanted to compile with xlf for benchmarking purposes and ran into this error. I am building both from a fresh tar that I downloaded from netlib

**Comment by martin-frbg** [comment]
hmm, does it compile when you delete  all the comment lines ? (thinking this should probably be reported to ibm as a probable openxlf parser bug)

**Comment by ocelotStride** [comment]
> hmm, does it compile when you delete  all the comment lines ? (thinking this should probably be reported to ibm as a probable openxlf parser bug)

I will try this next week and respond back with the result. If it fixes the problem, I'll make a bug report to IBM

**Comment by martin-frbg** [comment]
could be something like a return of https://www.ibm.com/support/pages/apar/LI74813 (in that case, adding `-qfree=f90` would fix it)

**Comment by martin-frbg** [comment]
Actually this just seems to be a case of the make.inc template being outdated compared to what is in CMakeLists.txt for the cmake build - it still reflects the option set suitable for LAPACK 3.9.0, notably including `-qfixed` (and also lacking `-qrecur`).
Due to this, even xlf 15 (as installed in the gcc compile farm host gcc119) fails to compile la_constants.f90

**Comment by ocelotStride** [comment]
I do think it is more likely an issue of the template being outdated. As I mentioned, the opt flag on the original xlc of `-qnosave` seems to be outdated by a few xlc revisions, so it is likely the xlc is as well. I will try some tweaks on Monday and let you know what works. Thank you for the guidance on this

**Comment by ocelotStride** [comment]
Rather than build with the older make files, I'm attempting to build with cmake. The run fails on the linking step for `libVerifyFortran.a`

My command:

`cmake -DCMAKE_C_COMPILER=/opt/ibm/openxlC/17.1.1/bin/ibm-clang -DCMAKE_Fortran_COMPILER=/opt/ibm/openxlf/17.1.1/bin/xlf ..`

The command that errors out:

`/opt/ibm/openxlC/17.1.1/bin/ibm-clang -DWeirdNEC -DLAPACK_ILP64 -DHAVE_LAPACK_CONFIG_H -O3 -DNDEBUG CMakeFiles/VerifyFortranC.dir/main.c.o CMakeFiles/VerifyFortranC.dir/VerifyC.c.o -o VerifyFortranC   -L/opt/ibm/xlsmp/5.1.1/lib  -L/opt/ibm/openxlf/17.1.1/lib  libVerifyFortran.a -lxlf90 -lxlopt -lxlomp_ser -lxl -lxlfmath -ldl -lrt -lpthread -lm`

The error:

`ld.lld: error: undefined symbol: VerifyFortran`

I'm not sure how I would correct this as I don't have a tonne of experience with cmake. What are the flags that I would need to include in the older make files to match the up-to-date cmake builds?

**Comment by martin-frbg** [comment]
As I wrote above, remove the `-qfixed` and add `-qrecur`. The cmake error seems to be an internal cmake thing related to testing that the compiler can do mixed C+Fortran builds. No idea if it is indicative of a broken cmake or compiler on your system
