### ISSUE TITLE
Check if there are uninitialized M when quick return in ?LARR?

### ISSUE THREAD

**Issue by langou** [Reference-LAPACK/lapack#770]
In #769 , @akobotov fixes an issue for DLARRD and SLARRD introduced with 16db9c24ea .

@akobotov mentions that the issue might be present in other ?LARR? subroutines. 

I agree that this is possible. It would be good to check.

Request for help: can someone check? if no issue, can you report "no issue"? if issue, can you provide a PR?

**Comment by echeresh** [comment]
It was my commit originally. Sorry for leaving the bug that went undetected for 5 years :)
I carefully reviewed the other sources but haven't found any similar spots with double quick return so I think the issue can be closed.

**Comment by langou** [comment]
Thanks @echeresh for checking!
