### ISSUE TITLE
Scalapack compilation issue

### ISSUE THREAD

**Issue by dherminder-coder** [Reference-LAPACK/lapack#784]
Hi 
I have tried to compile  scalapack-2.2.0 using cmake. I get the following compilation errors:

home/dsk11/C++Libraries/scalapack-2.2.0/SRC/pstrord.f:525:51:

  490 |      $           CALL IGAMX2D( ICTXT, 'All', TOP, 1, 1, MMAX, 1, -1,
      |                                                        2
......
  525 |             CALL IGAMX2D( ICTXT, 'All', TOP, 1, 1, INFO, 1, -1, -1,
      |                                                   1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
/home/dsk11/C++Libraries/scalapack-2.2.0/SRC/pstrord.f:1582:51:

  490 |      $           CALL IGAMX2D( ICTXT, 'All', TOP, 1, 1, MMAX, 1, -1,
      |                                                        2
......
 1582 |             CALL IGAMX2D( ICTXT, 'All', TOP, 1, 1, IERR, 1, -1,
      |                                                   1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
/home/dsk11/C++Libraries/scalapack-2.2.0/SRC/pstrord.f:1593:54:

  490 |      $           CALL IGAMX2D( ICTXT, 'All', TOP, 1, 1, MMAX, 1, -1,
      |                                                        2
......
 1593 |                CALL IGAMX2D( ICTXT, 'All', TOP, 1, 1, INFO, 1, -1,
      |                                                      1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
/home/dsk11/C++Libraries/scalapack-2.2.0/SRC/pstrord.f:3253:51:

  490 |      $           CALL IGAMX2D( ICTXT, 'All', TOP, 1, 1, MMAX, 1, -1,
      |                                                        2
......
 3253 |             CALL IGAMX2D( ICTXT, 'All', TOP, 1, 1, IERR, 1, -1,
      |                                                   1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
/home/dsk11/C++Libraries/scalapack-2.2.0/SRC/pstrord.f:3264:54:

  490 |      $           CALL IGAMX2D( ICTXT, 'All', TOP, 1, 1, MMAX, 1, -1,
      |                                                        2
......
 3264 |                CALL IGAMX2D( ICTXT, 'All', TOP, 1, 1, INFO, 1, -1,
      |                                                      1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
make[2]: *** [CMakeFiles/scalapack.dir/build.make:12812: CMakeFiles/scalapack.dir/SRC/pstrord.f.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1234: CMakeFiles/scalapack.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by martin-frbg** [comment]
This probably belongs in Reference-ScaLAPACK and looks like resolved issue 55 there: https://github.com/Reference-ScaLAPACK/scalapack/issues/55 (I notice there has not been a new release of ScaLAPACK since the fix got merged, so you'd need to build directly from the github master branch)

**Comment by dherminder-coder** [comment]
thanks - that works.
