### ISSUE TITLE
Inconsistent calls to [cz]gemm from [cz]trevc3.f?

### ISSUE THREAD

**Issue by reeuwijk-altium** [Reference-LAPACK/lapack#79]
Hi,

I'm trying to apply f2c[*] to the latest LAPACK release, and I get:
---
ctrevc3.f:
   ctrevc3:
Warning on line 596 of ctrevc3.f: inconsistent calling sequences for cgemm,
        arg 6: here real variable, previously complex variable.
---

arg 6 is ALPHA, which is COMPLEX, so I think this is a valid warning, and the actual parameter ONE should be CONE. 

Is my analysis correct?

Similar for ztrevc3.f.

[*] Yeah, I know that f2c cannot translate all of the latest LAPACK, but for the platform I'm targeting that's the best I have.

-- 
Kees van Reeuwijk

**Comment by langou** [comment]
Hi Kees, commit 633d65dc6afe9b12342f3d6add4bfc1a561a0b7f on August 29th 2016 fixed this problem. Cheers, Julien.
