### ISSUE TITLE
achtung... where is dtoa.c?

### ISSUE THREAD

**Issue by hergljkds** [Reference-LAPACK/lapack#799]
fp is part of netlib.  A component of netlib is dtoa.c (by david gay )...

This problem is sort like a corrupted anatomy... of a codebase rather than that of a person... although never underestimate the extent to which an exogenous support infrastructure (ie dependencies) assimilate into an identity (selective pressure held Constance... constant).

So, where is fp/dtoa.c ???

**Comment by martin-frbg** [comment]
you're wildly off topic here, and it would help if you could phrase your question in a less dramatic way. On netlib.org, follow the big "Browse" link to locate "fp" in their list of hosted software, and click there to access dtoa.c and related files.
