### ISSUE TITLE
Excessive size of man pages on 3.6.1

### ISSUE THREAD

**Issue by matzeri** [Reference-LAPACK/lapack#8]
Dear Development Team ,
is it possible to have a manpage file that includes
only the manual and not also all the Doxygen
extra stuff as on previous release ?

$ ls -sh manpages-3.6.0.tgz
1.4M manpages-3.6.0.tgz

$ ls -sh manpages-3.6.1.tgz
9.6M manpages-3.6.1.tgz

All the additional Doxygen stuff does not belong to a normal man page:

--------------------------------------------
...
Definition at line 152 of file zupmtr\&.f\&.
.PP
.nf
152 *
153 * -- LAPACK computational routine (version 3\&.4\&.0) --
154 * -- LAPACK is a software package provided by Univ\&. of Tennessee, --
155 * -- Univ\&. of California Berkeley, Univ\&. of Colorado Denver and NAG Ltd\&.\&.--
156 * November 2011
[cut]
--------------------------------------------

**Comment by julielangou** [comment]
Just a quick update - I looked quickly at it - I could not locate the issue in Doxygen configuration
I will look at it again

**Comment by julielangou** [comment]
Finally found the issue! Issue was due to missing Doxygen groups, and other Doxygen Group related issues.
Fixed with commit 843115b on Sep 15th 2016

**Comment by langou** [comment]
Great. Thanks Julie!
