### ISSUE TITLE
Add Security Policy

### ISSUE THREAD

**Issue by gabibguti** [Reference-LAPACK/lapack#818]
Adding a Security Policy is important to provide guidance on how users can report potential vulnerabilities and communicate when vulnerabilities will be confirmed, fixed and disclosed to the public.

I recently recommended https://github.com/Reference-LAPACK/lapack/issues/803 and, like that change, this one also considered a good-practice and recommended by [Github](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy) and [Scorecard](https://github.com/ossf/scorecard).

If you agree, I can open a PR to suggest a Security Policy! We can then work together to communicate how the repo can best handle vulnerability reports.

##### Additional Context
Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by langou** [comment]
Hi Gabriela, yes, OK, by all means, please submit a PR to suggest a Security Policy. Cheers, Julien.
