### ISSUE TITLE
dsyev() only returns upper/lower triangle of eigenvector matrix

### ISSUE THREAD

**Issue by david-houseman** [Reference-LAPACK/lapack#850]
**Description**

Sorry if this is a novice misunderstanding, but my understanding is that given a symmetric matrix, dsyev() should return in place the matrix of eigenvectors (when JOBZ = 'V'). The eigenvector matrix is not symmetric (it is orthogonal). However, it appears that dsyev() only returns the upper/lower triangle of the eigenvector matrix, which is not enough to easily construct the full eigenvector matrix.

Example:

    #include "stdio.h"
    #include "lapacke.h"

    int main()
    {
        const int N = 2;
        double a[2*2] = { 1.0, 0.5, 0.5, 1.0 };
        double s[2];

        printf( "input:\n" );
        printf( "%f %f\n", a[0], a[1] );
        printf( "%f %f\n", a[2], a[3] );
    
        LAPACKE_dsyev( LAPACK_ROW_MAJOR, 'V', 'U', N, a, N, s );

        printf( "output:\n" );
        printf( "%f %f\n", a[0], a[1] );
        printf( "%f %f\n", a[2], a[3] );
    
        return 0;
    }

Output:

    input:
    1.000000 0.500000
    0.500000 1.000000
    output:
    -0.707107 0.707107
    0.500000 0.707107

Problem:
The 0.5 in the output lower triangle should be 0.707107.
There is the opposite problem if UPLO = 'L'.
This problem applies to symmetric matrices of all sizes.

**Checklist**

- [X] I've included a minimal example to reproduce the issue
- [ ] I'd be willing to make a PR to solve this issue

**Comment by david-houseman** [comment]
It is version 3.9.0-3 (amd64) packaged with debian stable (11.7). I will raise a bug report with them. Also I will check whether the upcoming new debian release is affected.

Apologies I did not check against the upstream version before posting the bug report. Very glad this is already fixed upstream!

**Comment by angsch** [comment]
The problem was fixed with 7d5bb9e5e641772227022689162dd9cc47e64de0, ie version 3.9.1 should include the fix.

**Comment by angsch** [comment]
@david-houseman Can we close this?

**Comment by david-houseman** [comment]
@angsch Yes, this problem is fixed at head and in the new debian stable. Can close. Sorry if you were waiting for my response!
