### ISSUE TITLE
Why is the shared library option not enabled in compilation

### ISSUE THREAD

**Issue by karthik18495** [Reference-LAPACK/lapack#874]
I was trying to install lapack libraries to install the elmerfem software. 
In general I noted that only static library compilation is turned on in the cmake routine. May I know why is there no option to add a shared library compilation. I manually put in the flag while compiling and it compiled like a charm. Is it possible to add this functionality like in `-DSHARED_LIBRARY=ON` ?

Thank you

**Comment by weslleyspereira** [comment]
Hi. There is a CMake option for that: `BUILD_SHARED_LIBS`. Please, try using `-D BUILD_SHARED_LIBS=ON` in the configuration step of CMake.
