### ISSUE TITLE
segfault in ?gelss with nrhs=0 

### ISSUE THREAD

**Issue by eaberendeev** [Reference-LAPACK/lapack#875]
For example single precision, but there is in all precision.

For nrhs = 0 there is copy (line 530) N elements to B array, but size of B can be less then N

![gelss](https://github.com/Reference-LAPACK/lapack/assets/44430293/271b90dd-b0d5-444f-bdaf-7db13df69215)

I suggest add condition 

`IF NRHS > 0`

for this condition branch
and for branch on line 638 and 713
![sgelss](https://github.com/Reference-LAPACK/lapack/assets/44430293/041c23eb-397e-44c3-9ef4-560ee1b8ee16)

![gelss3](https://github.com/Reference-LAPACK/lapack/assets/44430293/5c24e33b-845b-42d1-b36c-ca339638730a)

**Comment by langou** [comment]
I agree. I will repeat to make sure that we are on the same page.

You are speaking about these lines of code
https://github.com/Reference-LAPACK/lapack/blob/4b54a336a422b294d4f54b9b666941ecf54eb0a2/SRC/dgelss.f#L698-L718

But there is the same pattern three times throughout the code. As you noted.

Your solution of " add a condition `IF NRHS > 0` around the branch" would work.

Other solution: What about changing the `ELSE` statement in a `ELSE IF( NRHS.EQ.1 ) THEN` in the line below?
https://github.com/Reference-LAPACK/lapack/blob/4b54a336a422b294d4f54b9b666941ecf54eb0a2/SRC/dgelss.f#L714-L717
I think that'll do the job too. What do you think? Do you agree?

Would you be willing to submit a PR (pull request)?

Julien

**Comment by langou** [comment]
I am not sure you are used to LAPACK, so, adding just in case, if you do a PR, (1) thanks a lot, (2) please consider doing all four arithmetics, so that means (1) cgelss.f, (2) dgelss.f, (3) sgelss.f, and (4) zgelss.f. (Not just dgelss.f.) I should have mentioned this in my previous post.
