### ISSUE TITLE
Wrong uplo value in LAPACKE_?larfb

### ISSUE THREAD

**Issue by vladimir-ch** [Reference-LAPACK/lapack#877]
**Description**

`LAPACKE_?larfb` and `LAPACKE_?larfb_work` routines compute an uplo value based on the input parameters in order to transpose the trapezoidal matrix V. This computation wrongly uses the parameter `left` (side) instead of the correct `forward` (direct).

In other words, instead of 
```
uplo = ( ( left && col ) || !( left || col ) ) ? 'l' : 'u';
```
the code should do
```
uplo = ( ( forward && col ) || !( forward || col ) ) ? 'l' : 'u';
```

With this fix our Gonum tests (for Dlarfb) pass again.

**Checklist**

- [ ] I've included a minimal example to reproduce the issue
- [x] I'd be willing to make a PR to solve this issue

**Comment by langou** [comment]
Hi @vladimir-ch, Thanks! A PR from you to fix this issue sounds good to me! @langou.
