### ISSUE TITLE
`lauum` producing incorrect factorization

### ISSUE THREAD

**Issue by david-cortes** [Reference-LAPACK/lapack#884]
**Description**
The docs for `lauum` say that it should produce a factorization
$\mathbf{A} = \mathbf{U} \mathbf{U}^T$

or
$\mathbf{A} = \mathbf{L}^T \mathbf{L}$

In this example, I am passing a positive-definite matrix to `dlauum`, and it exits with `info=0`, but the result doesn't actually factorize the matrix:
```cpp
#include <iostream>

extern "C" void dlauum_(const char *uplo, const int *n, double *A, const int *lda, int *info);

int main()
{
     double S[] = {
        5.69380401, -0.81422404, -1.17556336,  1.46995046,
        0,  1.45817153, -1.3378084 ,  0.41896384,
        0,  0,  3.17103388, -0.21233572,
        0,  0, 0,  2.79247332
    };

    int n = 4;
    int info;
    dlauum_("L", &n, S, &n, &info);
    std::cout << "info:" << info << std::endl;

    std::cout << "X:" << std::endl;
    for (int row = 0; row < n; row++)
    {
        std::cout << "[ ";
        for (int col = 0; col < n; col++) std::cout << S[col + row*n] << ", ";
        std::cout << "]" << std::endl;
    }
    return 0;
}
```
```
info:0
X:
[ 36.6251, 1.00126, -4.03987, 4.1048, ]
[ 0, 4.09153, -4.3312, 1.16995, ]
[ 0, 0, 10.1005, -0.592942, ]
[ 0, 0, 0, 7.79791, ]
```

This is with LAPACK 3.11, compiled with gcc/gfortran, running on linux (intel 12700H).

**Checklist**

- [x] I've included a minimal example to reproduce the issue
- [ ] I'd be willing to make a PR to solve this issue

**Comment by langou** [comment]
LAUUM does the product, not the factorization. You give U in input, and it computes A = U^T * U in output. 
If you want the factorization, you want to use POTRF.

**Comment by david-cortes** [comment]
@langou Thank you very much for your answer, I had completely missed that distinction.

However, `potrf` computes the Cholesky, which would be
$\mathbf{A} = \mathbf{L} \mathbf{L}^T$

whereas the docs for `lauum` mention
$\mathbf{L}^T \mathbf{L}$

Is there any routine in LAPACK doing that factorization instead of regular Cholesky? I haven't been able to find any from the docs.

**Comment by langou** [comment]
Right, that's a good question. The answer is "no". We do not have this factorization.
LAPACK factors with "lower times upper". LAPACK does not factor "upper times lower". 
That's the way it is.
