### ISSUE TITLE
AppVeyor can't find Fortran compiler

### ISSUE THREAD

**Issue by weslleyspereira** [Reference-LAPACK/lapack#919]
There is a failure in one of the test scripts: AppVeyor fails to find the flang compiler. See:
https://ci.appveyor.com/project/langou/lapack/builds/48409716
and
https://ci.appveyor.com/project/langou/lapack/builds/48410695

**Comment by martin-frbg** [comment]
with LLVM17, the flang compiler is most likely named flang-new now.

**Comment by weslleyspereira** [comment]
Thanks! I tried a simple fix, but it seems `flang-new is not able to compile a simple test program`. See https://ci.appveyor.com/project/langou/lapack/builds/48411974

**Comment by martin-frbg** [comment]
Looks like it's getting fed Microsoft-style arguments that it does not understand - where do the /machine etc. come from ?
Is this something you were setting for the previous compiler, environment variables from the vcvars script (unlikely for fortran I guess) or defaults assumed by an old CMAKE that does not yet know flang-new ?

**Comment by weslleyspereira** [comment]
This is the script: https://github.com/Reference-LAPACK/lapack/blob/952039c44b19969dc2133e66b9d6654cda68cefb/.appveyor.yml. I have no idea about where `/machine` comes from.

**Comment by martin-frbg** [comment]
actually it is using the new flang as the linker and supplying options as if it were microsoft's ld. guess that is a problem with the cmake version (but we do not yet have a Windows/LLVM17 CI job for OpenBLAS from which I could copy)

**Comment by martin-frbg** [comment]
installing a newer cmake from conda solves the compiler detection, but now it tries  to invoke lib.exe with the "qc" argument of GNU ar.

**Comment by weslleyspereira** [comment]
I think AppVeyor is working again. They have probably fixed the issue upstream. See https://ci.appveyor.com/project/langou/lapack/builds/48420171

**Comment by martin-frbg** [comment]
Looks like conda (or something) reverted to providing LLVM11 instead of LLVM17 when asked to install flang. Not sure if this is a decision (given that LLVM11 is fairly ancient) or just a case of different mirror sites hosting different versions

**Comment by weslleyspereira** [comment]
Thanks for explaining!

**Comment by h-vetinari** [comment]
> Looks like conda (or something) reverted to providing LLVM11 instead of LLVM17 when asked to install flang. Not sure if this is a decision (given that LLVM11 is fairly ancient) or just a case of different mirror sites hosting different versions

The issue is that since the hand-patched "classic" flang (based on LLVM 11), there has been no usable flang on windows in conda-forge, until the upstream llvm "flang-new" recently matured enough that we have builds for LLVM 17 available now. However, since things are still pretty experimental, those aren't our default setup yet (which has a couple consequences, including potential downgrades in case of conflicts).

I'm hoping things stabilize enough by LLVM 18 early next year to make this the default. By then, the compiler binary should also be called `flang` instead of `flang-new` again (if all goes well 🤞).

**Comment by h-vetinari** [comment]
PS. Feel free to ping me about conda-forge packages and LLVM resp. flang in particular.

**Comment by weslleyspereira** [comment]
Thanks!

**Comment by martin-frbg** [comment]
aaand it is bouncing between LLVM11/flang and LLVM17/flang-new again...

**Comment by h-vetinari** [comment]
Can you provide the environment (as resolved) with flang 11 resp. 17?

**Comment by martin-frbg** [comment]
`conda info --envs` and `env list` both return
```
base        *
C:\Miniconda37-x64
```
for the "broken" case - we are just loading some fairly old vs2017 image on appveyor and running `activate.bat` without any parameters, then not even updating conda before the `conda install flang`

**Comment by h-vetinari** [comment]
That's an extraordinarily old setup. It would be good to update conda itself first before doing something else.

That said, I was asking for the `conda list` of the environments, to perhaps understand where the flipping might be coming from. But it would be better to upgrade conda first, to rule out historical bugs.

**Comment by martin-frbg** [comment]
IIRC, the update command was commented out at some point as it ran into some circular dependency. As this is "only" a CI job, all that is wanted is a reproducible (if now outdated) Windows environment with a certain version of flang...

**Comment by h-vetinari** [comment]
> all that is wanted is a reproducible (if now outdated) Windows environment with a certain version of flang...

If that's what you want, you can create a lock-file from a working environment, à la:
```
conda env export -f lock.yml
```
commit that file, and then create the unchanged environment you want to keep using with:
```
conda env create -f lock.yml
```

This will ensure you get the exact environment again and again.

**Comment by martin-frbg** [comment]
@h-vetinari thank you very much - as it turns out, we were not even requesting a specific version of flang and adding `=11.0.1` appears to be enough (for now at least) to restore the "old" behaviour
