### ISSUE TITLE
xLASWP: bug for negative INCX

### ISSUE THREAD

**Issue by vladimir-ch** [Reference-LAPACK/lapack#92]
In DLASWP, `INCX` is the increment for `IPIV` and can be positive or negative. If negative, the swaps are applied from `K2` down to `K1`, otherwise from `K1` to `K2`. From the documentation it is understood that the same elements of `IPIV` are accessed in both cases.

However, the implementation behaves differently. When `INCX>0`, the first accessed element is `K1`, then `K1+INCX`, ... until `K1+(K2-K1)*INCX`. When `INCX<0`, the first accessed element is
```
1+(1-K2)*INCX
```
when in fact it should be
```
K1+(K1-K2)*INCX
```
It seems that the `1` is missing a `K` in front. All the calls to DLASWP with `INCX=-1` luckily use `K1=1` in LAPACK.

**Comment by langou** [comment]
I have been starring at this line ( `1+(1-K2)*INCX` ) for quite some time (like 10 years) and could not figure out the meaning of this line and put in context with the subroutine description.

Yes, it really seems that you are correct and that the intent was to write: `K1+(K1-K2)*INCX` and what was written was `1+(1-K2)*INCX`. 

As you said I think we only use `xLAWSP` with `INCX = 1` or `INCX = -1`. So the other cases are not really tested.

In the `INCX = -1` case (only negative `INCX` case used in `LAPACK`), the line (`1+(1-K2)*INCX`) is good enough and returns the correct value (`K2`). But in other cases, (not used in `LAPACK`,) this line (`1+(1-K2)*INCX`) is clearly not correct and does not match the subroutine description.

This might be one of the oldest in LAPACK I know of. Oh my. I cannot check LAPACK 1.0 and others to see if the bug was present initially, or it was introduced at some point. The bug is in LAPACK 3.0. So since 2000 for sure.

**Comment by langou** [comment]
Three proposed changes in xLASWP:

(1) In description, change 
`
          K2 is INTEGER
          The last element of IPIV for which a row interchange will
          be done.
`
to
`
          K2 is INTEGER
          (K2-K1+1) is the number of elements of IPIV for which a row
          interchange will be done.
`

(2) In description, change 
`
          IPIV is INTEGER array, dimension (K2*abs(INCX))
          The vector of pivot indices.  Only the elements in positions
          K1 through K2 of IPIV are accessed.
          IPIV(K) = L implies rows K and L are to be interchanged.
`
to
`
          IPIV is INTEGER array, dimension (K1+(K2-K1)*abs(INCX))
          The vector of pivot indices.  Only the elements in positions
          K1 through K1+(K2-K1)*INCX of IPIV are accessed.
          IPIV(K) = L implies rows K and L are to be interchanged.
`

(3) In code, change line 146 (as Vladimir suggests)
`
          IX0 = 1 + ( 1-K2 )*INCX
`
to
` 
         IX0 = K1 + ( K1-K2 )*INCX
`

**Comment by langou** [comment]
Also I want to say that I am not a big fan of the INCX in this context. INCX=1, yes. INCX=-1, yes. I am not sure of the usefulness of other values of INCX. (As noted by Vladimir, LAPACK does not use any other values. LAPACK only uses 1 and -1.) Moreover the meaning of K1 and K2 starts to be a little confusing when ABS( INCX ) is not 1. So maybe another option is to "forbid" all values of INCX but 1 and -1. And simplifies codes and comments accordingly.

Any comment welcome. 

Not relevant to this thread: Note that the code permutes rows by block of 32 columns at a times. So the codes takes columns 1 to 32, applies all the row permutations on these columns, then move to columns 33 to 64, applies all the row permutations on these columns, etc.

**Comment by vladimir-ch** [comment]
> In the INCX = -1 case (only negative INCX case used in LAPACK), the line (1+(1-K2)*INCX) is good enough and returns the correct value (K2)

In fact, the correct value in that case should be `K1+K2`. In LAPACK the -1 case is always with `K1=1` which is why it works.

I agree with the doubtful usefulness of other values of `INCX` than 1 and -1. The necessity for complicated explanations such as in point (2) above looks suspicions and unmerited for an elementary function such as xLASWP. Also, one confusion that arises is that if `IPIV` is to be strided, then why `K1` can be arbitrary and not respect the stride. Perhaps the original intention was to allow only 1 and -1 for `INCX` and it seems that your hands are still free to restrict it.

So, I think it would be beneficial to forbid all values of `INCX` but 1 and -1 and simplify code and comments accordingly.

**Comment by vladimir-ch** [comment]
> In fact, the correct value in that case should be K1+K2. In LAPACK the -1 case is always with K1=1 which is why it works.

Oh, please disregard what I wrote, you were of course right, `K2` is the correct value.

**Comment by langou** [comment]
Hi Vladimír, I just committed a fix. I have you as the author of the fix since I ended up doing verbatim what you suggested. Thanks! Cheers, Julien.
