### ISSUE TITLE
incorrect comment in dtrsv.f

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [Reference-LAPACK/lapack#931]
In the reference BLAS, dtrsv.f, the function is incorrectly listed as a BLAS level1 method:

https://github.com/Reference-LAPACK/lapack/blob/8ecaaf9869b6bb95ed280f6f54ae5ae061eeeded/BLAS/SRC/dtrsv.f#L144

See also line 139.

The other [dcz]strv.f functions have "level2" in their comments.

I haven't checked for incorrect references in the rest of the BLAS, but it would be a good idea to check that.

**Comment by langou** [comment]
Thanks @DrTimothyAldenDavis. This should be fixed.

**Comment by DrTimothyAldenDavis** [comment]
Woohoo ... I found my first BLAS "bug" ;-)

OK, not really a bug; just a minor documentation glitch.   But I'm sure fixes even as trivial as this in the Fortran reference BLAS are rare.
