### ISSUE TITLE
Inkscape and OpenShot throw error "undefined symbol: ssyrk_64_" from libcblas

### ISSUE THREAD

**Issue by Khris777** [Reference-LAPACK/lapack#947]
**Description**

I did a fresh install of OpenShot and Inkscape this weekend.
I'm using EndeavorOS and the arch repositories with the pacman package manager.

Both applications fail to start and throw the same error:

Inkscape:
`symbol lookup error: /usr/lib/libcblas.so.3: undefined symbol: ssyrk_64_`

OpenShot:
`ImportError: /usr/lib/libcblas.so.3: undefined symbol: ssyrk_64_`

The [cblas library](https://archlinux.org/packages/extra/x86_64/cblas/) just got updated to 3.12.0, so I presume that might be the cause.

cblas Version: 3.12.0
Operating System / Distro: EndeavorOS, Kernel 6.1.62-1-lts

**Checklist**

- [ ] I've included a minimal example to reproduce the issue
- [ ] I'd be willing to make a PR to solve this issue

**Comment by martin-frbg** [comment]
The _64_ in the symbol name suggests that your applications require an "INTERFACE64=ON" build of BLAS/CBLAS. it is possible that the symbol suffix naming has changed from previous releases (new name may be ssyrk64_ as a side effect of providing both normal and extended-address-range symbols in the same library).In that case the 3.12 library would no longer be a drop-in replacement for earlier versions but require a recompile/relink of dependent applications. Can you check with "nm" what the symbol names are in the new Arch build ?

**Comment by Khris777** [comment]
> The _64_ in the symbol name suggests that your applications require an "INTERFACE64=ON" build of BLAS/CBLAS. it is possible that the symbol suffix naming has changed from previous releases (new name may be ssyrk64_ as a side effect of providing both normal and extended-address-range symbols in the same library).In that case the 3.12 library would no longer be a drop-in replacement for earlier versions but require a recompile/relink of dependent applications. Can you check with "nm" what the symbol names are in the new Arch build ?

I am not knowledgable about nm, but when I use it on libcblas.so(.3(.11.0)) I get "no symbols". 
Can you direct me to the correct file I need to look at?

There's also [something about the 64-bit API](https://www.netlib.org/lapack/lapack-3.12.0.html#_improvements_in_the_64_bit_api) in the release notes.

**Comment by martin-frbg** [comment]
The "no symbols" is a bit strange for a shared library, perhaps you looked at a symbolic link that is not pointing anywhere
after the update of libcblas to 3.12.0 ?
Make sure that your "blas" package also got updated to 3.12, and if the problem persists perhaps check with whoever manages the lapack/cblas package on the Arch Linux side - I just did a test build of 3.12 on Linux and my nm output looks correct -
```
nm lib/libcblas.so|grep ssyrk
000000000000d8a0 T cblas_ssyrk
000000000001d8c0 T cblas_ssyrk_64
                 U ssyrk_
                 U ssyrk_64_
```
(and libblas.so has the matching symbols for ssyrk that libcblas **U**ses:
```
nm lib/libblas.so|grep ssyrk
000000000000dff0 T ssyrk_
000000000007ec80 T ssyrk_64_


```

**Comment by guillaumechauvat** [comment]
In case this is useful to anyone finding this, I had the same exact error because I had an old /usr/local/lib64/libblas.so* ... I was confused because `nm /usr/lib/libcblas.so.3.12.0` also returned "no symbols", but it works anyway after deleting the old library files.
