### ISSUE TITLE
'exit_level_0' unreferenced label in *syconv

### ISSUE THREAD

**Issue by cmoha** [Reference-LAPACK/lapack#95]
This label `exit_level_0: ` in `*syconv` is not used, is there anything missing?

**Comment by langou** [comment]
Hi, I am not sure what you mean. Can you explain some more? What do you mean by "this label exit_level_0: in *syconv" ? Cheers, Julien.

**Comment by cmoha** [comment]
I mean this label is declared but not used in these files  [lapacke_ssyconv.c](https://github.com/Reference-LAPACK/lapack/blob/master/LAPACKE/src/lapacke_dsyconv.c#L54),  [lapacke_ssyconv.c](https://github.com/Reference-LAPACK/lapack/blob/master/LAPACKE/src/lapacke_ssyconv.c#L54),  [lapacke_zsyconv.c](https://github.com/Reference-LAPACK/lapack/blob/master/LAPACKE/src/lapacke_zsyconv.c#L56) and [lapacke_csyconv.c](https://github.com/Reference-LAPACK/lapack/blob/master/LAPACKE/src/lapacke_csyconv.c#L55), 
 and they give a compiler warning.

**Comment by langou** [comment]
Thanks. This is fixed. There was indeed a problem. (A few extra useless lines of codes.)
