### ISSUE TITLE
Make all release tags annotated tags

### ISSUE THREAD

**Issue by christoph-conrads** [Reference-LAPACK/lapack#957]
On the current master branch, the output of `git describe` is `v3.11.0-406-ga4298d5ff` when `v3.12.0-13-ga4298d5ff` is most likely preferred (the second description was generated by `$ git describe --tags`). The reason is that the v3.12.0 tag is not an annotated tag (see the console output below and note the message by the tagger). I suggest to make all release tags annotated tags.

```console
$ git show v3.11.0
tag v3.11.0
Tagger: Weslley da Silva Pereira <weslley.spereira@gmail.com>
Date:   Wed Nov 16 09:35:22 2022 -0700

LAPACK v3.11.0

commit 7866626840f5d5e7e27f027a55182da8b3303872 (tag: v3.11.0, tag: v3.11)
Merge: e7253049c 57f15d84c
Author: langou <julien.langou@ucdenver.edu>
Date:   Fri Nov 11 10:49:54 2022 -0700

    Merge pull request #751 from weslleyspereira/lapack-3.11-preparation
    
      Preparing LAPACK 3.11

$ git show v3.12.0
commit 04b044e020a3560ccfa9988c8a80a1fb7083fc2e (tag: v3.12.0)
Merge: b231dd57c d7be81320
Author: langou <julien.langou@ucdenver.edu>
Date:   Fri Nov 24 13:41:15 2023 -0700

    Merge pull request #944 from julielangou/master
    
    LAPACK 3.12.0 release

```

References:
* ["git describe" ignores a tag](https://stackoverflow.com/questions/4154485/git-describe-ignores-a-tag)

**Comment by martin-frbg** [comment]
I suspect the lightweight form is what one gets when using the "convenient" tagging option on the "draft a release" page of the github web interface ? (At least I think that is how I became guilty of the same mistake).

And I see we have been there before in #123 (which also mentions a nice quick script for repairing such tags)

**Comment by langou** [comment]
Thanks @christoph-conrads for pointing the issue. Thanks @martin-frbg for reminding me of the fix. The v3.12.0 tag is now an annotated tag. We will try to annotate our tag from now on, this is good practice, agreed.
