### ISSUE TITLE
xLABAD

### ISSUE THREAD

**Issue by langou** [Reference-LAPACK/lapack#96]
This is related to the  subroutines xLABAD.

> SLABAD takes as input the values computed by SLAMCH for underflow and
> overflow, and returns the square root of each of these values if the
> log of LARGE is sufficiently large.  This subroutine is intended to
> identify machines with a large exponent range, such as the Crays, and
> redefine the underflow and overflow limits to be the square roots of
> the values computed by SLAMCH.  This subroutine is needed because
> SLAMCH does not compensate for poor arithmetic in the upper half of
> the exponent range, as is found on a Cray.

Is that still relevant on current Cray machines? 

I would assume all machines are using IEEE and such a routine is obsolete by now.

**Comment by jwdemmel** [comment]
Indeed, slabad should be a no-op on current computers, unless "double"
gets compiled into IEEE754 binary quad precision or decimal double precision.
So ok to omit.

**Comment by weslleyspereira** [comment]
This issue was closed with #805.
