### ISSUE TITLE
How to stand-alone build man pages?

### ISSUE THREAD

**Issue by Dave-Allured** [Reference-LAPACK/lapack#982]
I am trying to update the portfile for LAPACK 3.12.0 on Macports.  The build system for man pages changed between 3.11 and 3.12 in commit https://github.com/Reference-LAPACK/lapack/commit/3c5ca872dad2b7012d395b32e18d6e610aa0d231 .

The previous Macports portfile for 3.11 builds man pages independently, by completely skipping configure, and running **doxygen DOCS/Doxyfile_man** as stand-alone.  Skipping configure is important because it creates an arch-independent, one-time build for docs.

My attempt in 3.12.0 to stand-alone run **doxygen DOCS/Doxyfile** does not seem to generate man pages.  Build log is here:  https://github.com/Dave-Allured/macports-ports/actions/runs/7604057387/job/20706521584 , through "gear icon"/Download log archive.

So, how do I build the man pages stand-alone?  Am I missing something simple from my invocation?

**Comment by christoph-conrads** [comment]
First of all `DOCS/Doxyfile_man` was removed by the commit 3c5ca872dad2b7012d395b32e18d6e610aa0d231 that you mentioned in your post (as you noticed). The new approach by LAPACK works by maintaining only a single Doxygen configuration file in `DOCS/Doxyfile` for all documentation formats. CMake takes this file as an input and applies two change sets to it:
* The [first change set](https://github.com/Reference-LAPACK/lapack/blob/fe843f99d6ad0034cdc85cd3d56f164b923afbe9/CMakeLists.txt#L618-L635) applies options for all documentation formats.
* The [second change set](https://github.com/Reference-LAPACK/lapack/blob/fe843f99d6ad0034cdc85cd3d56f164b923afbe9/CMakeLists.txt#L674-L694) sets options specific to man pages (e.g., it enables building man pages in the first place).

If you want to build man pages without running CMake, you have to customize the existing `Doxyfile` and emulate the changes made by CMake.

**Comment by Dave-Allured** [comment]
@christoph-conrads thank you.  I will take these hints and see if I can fix that doc build for Macports.
